// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package colors

import (
	"github.com/thmalt/colors/space"
)

func Clamp(c Color) Color {
	if !c.space.IsValid() {
		return Color{}
	}

	switch c.space {
	case space.XyzD65:
		return clampXyzD65(c)
	case space.XyY:
		return clampXyY(c)
	case space.XyzD50:
		return clampXyzD50(c)
	case space.LinearSrgb:
		return clampLinearSrgb(c)
	case space.Srgb:
		return clampSrgb(c)
	case space.LinearDisplayP3:
		return clampLinearDisplayP3(c)
	case space.DisplayP3:
		return clampDisplayP3(c)
	case space.LinearA98:
		return clampLinearA98(c)
	case space.A98:
		return clampA98(c)
	case space.LinearProPhoto:
		return clampLinearProPhoto(c)
	case space.ProPhoto:
		return clampProPhoto(c)
	case space.LinearRec2020:
		return clampLinearRec2020(c)
	case space.Rec2020:
		return clampRec2020(c)
	case space.Hsl:
		return clampHsl(c)
	case space.Hsv:
		return clampHsv(c)
	case space.Hwb:
		return clampHwb(c)
	case space.Lab:
		return clampLab(c)
	case space.Lch:
		return clampLch(c)
	case space.Luv:
		return clampLuv(c)
	case space.Lchuv:
		return clampLchuv(c)
	case space.Oklab:
		return clampOklab(c)
	case space.Oklch:
		return clampOklch(c)
	default:
		panic("unreachable")
	}
}

func clampXyzD65(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampXyY(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	c.c2 = clamp(c.c2, 0, 1)
	return c
}

func clampXyzD50(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampLinearSrgb(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampSrgb(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampLinearDisplayP3(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampDisplayP3(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampLinearA98(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampA98(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampLinearProPhoto(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampProPhoto(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampLinearRec2020(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampRec2020(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampHsl(c Color) Color {
	c.c1 = wrap(c.c1, 0, 360)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampHsv(c Color) Color {
	c.c1 = wrap(c.c1, 0, 360)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampHwb(c Color) Color {
	c.c1 = wrap(c.c1, 0, 360)
	c.c2 = clamp(c.c2, 0, 1)
	c.c3 = clamp(c.c3, 0, 1)
	return c
}

func clampLab(c Color) Color {
	c.c1 = clamp(c.c1, 0, 100)
	return c
}

func clampLch(c Color) Color {
	c.c1 = clamp(c.c1, 0, 100)
	c.c3 = wrap(c.c3, 0, 360)
	return c
}

func clampLuv(c Color) Color {
	c.c1 = clamp(c.c1, 0, 100)
	return c
}

func clampLchuv(c Color) Color {
	c.c1 = clamp(c.c1, 0, 100)
	c.c3 = wrap(c.c3, 0, 360)
	return c
}

func clampOklab(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	return c
}

func clampOklch(c Color) Color {
	c.c1 = clamp(c.c1, 0, 1)
	c.c3 = wrap(c.c3, 0, 360)
	return c
}
