// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package colors

import (
	"github.com/thmalt/colors/space"
)

// Clamp clamps the color channels to the valid range of the color space.
func Clamp(c Color) Color {
	switch c.space {
	case space.Oklab:
		c.c1 = clamp(c.c1, 0, 1)
		return c
	case space.LabD50, space.LabD65, space.LuvD50, space.LuvD65:
		c.c1 = clamp(c.c1, 0, 100)
		return c
	case space.Oklch:
		c.c1 = clamp(c.c1, 0, 1)
		c.c3 = wrap(c.c3, 0, 360)
		return c
	case space.XyYD50, space.XyYD65:
		c.c1 = clamp(c.c1, 0, 1)
		c.c2 = clamp(c.c2, 0, 1)
		return c
	case space.LchD50, space.LchD65, space.LchuvD50, space.LchuvD65:
		c.c1 = clamp(c.c1, 0, 100)
		c.c3 = wrap(c.c3, 0, 360)
		return c
	case space.Hsl, space.Hsv, space.Hwb:
		c.c1 = wrap(c.c1, 0, 360)
		c.c2 = clamp(c.c2, 0, 1)
		c.c3 = clamp(c.c3, 0, 1)
		return c
	case space.Srgb, space.LinearSrgb, space.DisplayP3, space.LinearDisplayP3,
		space.A98, space.LinearA98, space.ProPhoto, space.LinearProPhoto,
		space.Rec2020, space.Rec2020OETF, space.LinearRec2020, space.XyzD50,
		space.XyzD65:
		c.c1 = clamp(c.c1, 0, 1)
		c.c2 = clamp(c.c2, 0, 1)
		c.c3 = clamp(c.c3, 0, 1)
		return c
	default:
		return c
	}
}
