// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package colors

import (
	"github.com/thmalt/colors/space"
)

type Color struct {
	space space.Space
	// channels
	c1, c2, c3 float64
	alpha      float64
}

// Get channel in current [space.Space]
func (c Color) Channel(index int) (float64, bool) {
	switch index {
	case 2:
		return c.c3, true
	case 1:
		return c.c2, true
	case 0:
		return c.c1, true
	}
	return 0, false
}

func (c Color) Channels() []float64 {
	info := c.space.Info()
	if info == nil {
		return nil
	}

	switch info.ChannelCount() {
	case 3:
		return []float64{c.c1, c.c2, c.c3}
	case 2:
		return []float64{c.c1, c.c2}
	case 1:
		return []float64{c.c1}
	default:
		return nil
	}
}

func (c Color) AppendChannels(dst []float64) []float64 {
	info := c.space.Info()
	if info == nil {
		return dst
	}

	ch := [...]float64{c.c1, c.c2, c.c3}
	return append(dst, ch[:info.ChannelCount()]...)
}
