// Code generated by running "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package colors

import (
	"github.com/thmalt/colors/space"
)

// LinearSrgb returns a [Color] from Linear sRGB components.
func LinearSrgb(r, g, b float64) Color {
	return Color{space: space.LinearSrgb, c1: r, c2: g, c3: b, alpha: 1}
}

// Srgb returns a [Color] from sRGB components.
func Srgb(r, g, b float64) Color {
	return Color{space: space.Srgb, c1: r, c2: g, c3: b, alpha: 1}
}

// LinearA98 returns a [Color] from Linear Adobe® 98 RGB components.
func LinearA98(r, g, b float64) Color {
	return Color{space: space.LinearA98, c1: r, c2: g, c3: b, alpha: 1}
}

// A98 returns a [Color] from Adobe® 98 RGB components.
func A98(r, g, b float64) Color {
	return Color{space: space.A98, c1: r, c2: g, c3: b, alpha: 1}
}

// LinearDisplayP3 returns a [Color] from Linear Display P3 components.
func LinearDisplayP3(r, g, b float64) Color {
	return Color{space: space.LinearDisplayP3, c1: r, c2: g, c3: b, alpha: 1}
}

// DisplayP3 returns a [Color] from Display P3 components.
func DisplayP3(r, g, b float64) Color {
	return Color{space: space.DisplayP3, c1: r, c2: g, c3: b, alpha: 1}
}

// LinearProPhoto returns a [Color] from Linear ProPhoto components.
func LinearProPhoto(r, g, b float64) Color {
	return Color{space: space.LinearProPhoto, c1: r, c2: g, c3: b, alpha: 1}
}

// ProPhoto returns a [Color] from ProPhoto components.
func ProPhoto(r, g, b float64) Color {
	return Color{space: space.ProPhoto, c1: r, c2: g, c3: b, alpha: 1}
}

// LinearRec2020 returns a [Color] from Linear Rec. 2020 components.
func LinearRec2020(r, g, b float64) Color {
	return Color{space: space.LinearRec2020, c1: r, c2: g, c3: b, alpha: 1}
}

// Rec2020 returns a [Color] from Rec. 2020 components.
func Rec2020(r, g, b float64) Color {
	return Color{space: space.Rec2020, c1: r, c2: g, c3: b, alpha: 1}
}

// Hsl returns a [Color] from HSL components.
func Hsl(h, s, l float64) Color {
	return Color{space: space.Hsl, c1: h, c2: s, c3: l, alpha: 1}
}

// Hsv returns a [Color] from HSV components.
func Hsv(h, s, v float64) Color {
	return Color{space: space.Hsv, c1: h, c2: s, c3: v, alpha: 1}
}

// Hwb returns a [Color] from HWB components.
func Hwb(h, w, b float64) Color {
	return Color{space: space.Hwb, c1: h, c2: w, c3: b, alpha: 1}
}

// XyzD65 returns a [Color] from CIE XYZ D65 components.
func XyzD65(x, y, z float64) Color {
	return Color{space: space.XyzD65, c1: x, c2: y, c3: z, alpha: 1}
}

// XyzD50 returns a [Color] from CIE XYZ D50 components.
func XyzD50(x, y, z float64) Color {
	return Color{space: space.XyzD50, c1: x, c2: y, c3: z, alpha: 1}
}

// Lab returns a [Color] from CIE Lab components.
func Lab(l, a, b float64) Color {
	return Color{space: space.Lab, c1: l, c2: a, c3: b, alpha: 1}
}

// Lch returns a [Color] from CIE Lch components.
func Lch(l, c, h float64) Color {
	return Color{space: space.Lch, c1: l, c2: c, c3: h, alpha: 1}
}

// Oklab returns a [Color] from Oklab components.
func Oklab(l, a, b float64) Color {
	return Color{space: space.Oklab, c1: l, c2: a, c3: b, alpha: 1}
}

// Oklch returns a [Color] from Oklch components.
func Oklch(l, c, h float64) Color {
	return Color{space: space.Oklch, c1: l, c2: c, c3: h, alpha: 1}
}
