// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package colors

import (
	"github.com/thmalt/colors/space"
)

// Color represents a color in a [space.Space].
type Color struct {
	space space.Space

	// channels
	c1 float64
	c2 float64
	c3 float64
	c4 float64

	alpha float64
}

// Channel returns the channel value at index in the order defined by the
// color's [space.Space]. The returned boolean reports whether index is valid.
func (c Color) Channel(index int) (float64, bool) {
	if index < 0 || index >= c.ChannelCount() {
		return 0, false
	}

	switch index {
	case 3:
		return c.c4, true
	case 2:
		return c.c3, true
	case 1:
		return c.c2, true
	case 0:
		return c.c1, true
	}

	return 0, false
}

// Channels returns the channel values of c in the order defined by its [space.Space].
func (c Color) Channels() []float64 {
	switch c.ChannelCount() {
	case 4:
		return []float64{c.c1, c.c2, c.c3, c.c4}
	case 3:
		return []float64{c.c1, c.c2, c.c3}
	case 2:
		return []float64{c.c1, c.c2}
	case 1:
		return []float64{c.c1}
	default:
		return nil
	}
}

func (c Color) AppendChannels(dst []float64) []float64 {
	switch c.ChannelCount() {
	case 4:
		return append(dst, c.c1, c.c2, c.c3, c.c4)
	case 3:
		return append(dst, c.c1, c.c2, c.c3)
	case 2:
		return append(dst, c.c1, c.c2)
	case 1:
		return append(dst, c.c1)
	default:
		return dst
	}
}

// Channel3 returns the first 3 channels.
func (c Color) Channel3() (c1, c2, c3 float64) {
	return c.c1, c.c2, c.c3
}

// Channel4 returns the first 4 channels.
func (c Color) Channel4() (c1, c2, c3, c4 float64) {
	return c.c1, c.c2, c.c3, c.c4
}
