// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package colors

import (
	"github.com/thmalt/colors/space"
)

// mutTo converts the color to the specified color space in place
// and reports whether the conversion succeeded.
func (c *Color) mutTo(dst space.Space) bool {
	if !c.space.IsValid() {
		return false
	}

	if c.space == dst {
		return true
	}

	switch dst {
	case space.Srgb:
		c.c1, c.c2, c.c3 = c.srgb()
		c.c4 = 0
		c.space = space.Srgb
		return true
	case space.LinearSrgb:
		c.c1, c.c2, c.c3 = c.linearSrgb()
		c.c4 = 0
		c.space = space.LinearSrgb
		return true
	case space.DisplayP3:
		c.c1, c.c2, c.c3 = c.displayP3()
		c.c4 = 0
		c.space = space.DisplayP3
		return true
	case space.LinearDisplayP3:
		c.c1, c.c2, c.c3 = c.linearDisplayP3()
		c.c4 = 0
		c.space = space.LinearDisplayP3
		return true
	case space.A98:
		c.c1, c.c2, c.c3 = c.a98()
		c.c4 = 0
		c.space = space.A98
		return true
	case space.LinearA98:
		c.c1, c.c2, c.c3 = c.linearA98()
		c.c4 = 0
		c.space = space.LinearA98
		return true
	case space.ProPhoto:
		c.c1, c.c2, c.c3 = c.proPhoto()
		c.c4 = 0
		c.space = space.ProPhoto
		return true
	case space.LinearProPhoto:
		c.c1, c.c2, c.c3 = c.linearProPhoto()
		c.c4 = 0
		c.space = space.LinearProPhoto
		return true
	case space.Rec2020:
		c.c1, c.c2, c.c3 = c.rec2020()
		c.c4 = 0
		c.space = space.Rec2020
		return true
	case space.Rec2020OETF:
		c.c1, c.c2, c.c3 = c.rec2020OETF()
		c.c4 = 0
		c.space = space.Rec2020OETF
		return true
	case space.LinearRec2020:
		c.c1, c.c2, c.c3 = c.linearRec2020()
		c.c4 = 0
		c.space = space.LinearRec2020
		return true
	case space.LinearRec2100:
		c.c1, c.c2, c.c3 = c.linearRec2100()
		c.c4 = 0
		c.space = space.LinearRec2100
		return true
	case space.Rec2100PQ:
		c.c1, c.c2, c.c3 = c.rec2100PQ()
		c.c4 = 0
		c.space = space.Rec2100PQ
		return true
	case space.Rec2100HLG:
		c.c1, c.c2, c.c3 = c.rec2100HLG()
		c.c4 = 0
		c.space = space.Rec2100HLG
		return true
	case space.XyzD50:
		c.c1, c.c2, c.c3 = c.xyzD50()
		c.c4 = 0
		c.space = space.XyzD50
		return true
	case space.XyzD65:
		c.c1, c.c2, c.c3 = c.xyzD65()
		c.c4 = 0
		c.space = space.XyzD65
		return true
	case space.XyzAbsD65:
		c.c1, c.c2, c.c3 = c.xyzAbsD65()
		c.c4 = 0
		c.space = space.XyzAbsD65
		return true
	case space.XyYD50:
		c.c1, c.c2, c.c3 = c.xyYD50()
		c.c4 = 0
		c.space = space.XyYD50
		return true
	case space.XyYD65:
		c.c1, c.c2, c.c3 = c.xyYD65()
		c.c4 = 0
		c.space = space.XyYD65
		return true
	case space.LabD50:
		c.c1, c.c2, c.c3 = c.labD50()
		c.c4 = 0
		c.space = space.LabD50
		return true
	case space.LchD50:
		c.c1, c.c2, c.c3 = c.lchD50()
		c.c4 = 0
		c.space = space.LchD50
		return true
	case space.LabD65:
		c.c1, c.c2, c.c3 = c.labD65()
		c.c4 = 0
		c.space = space.LabD65
		return true
	case space.LchD65:
		c.c1, c.c2, c.c3 = c.lchD65()
		c.c4 = 0
		c.space = space.LchD65
		return true
	case space.LuvD50:
		c.c1, c.c2, c.c3 = c.luvD50()
		c.c4 = 0
		c.space = space.LuvD50
		return true
	case space.LchuvD50:
		c.c1, c.c2, c.c3 = c.lchuvD50()
		c.c4 = 0
		c.space = space.LchuvD50
		return true
	case space.LuvD65:
		c.c1, c.c2, c.c3 = c.luvD65()
		c.c4 = 0
		c.space = space.LuvD65
		return true
	case space.LchuvD65:
		c.c1, c.c2, c.c3 = c.lchuvD65()
		c.c4 = 0
		c.space = space.LchuvD65
		return true
	case space.Oklab:
		c.c1, c.c2, c.c3 = c.oklab()
		c.c4 = 0
		c.space = space.Oklab
		return true
	case space.Oklch:
		c.c1, c.c2, c.c3 = c.oklch()
		c.c4 = 0
		c.space = space.Oklch
		return true
	case space.Hsl:
		c.c1, c.c2, c.c3 = c.hsl()
		c.c4 = 0
		c.space = space.Hsl
		return true
	case space.Hsv:
		c.c1, c.c2, c.c3 = c.hsv()
		c.c4 = 0
		c.space = space.Hsv
		return true
	case space.Hwb:
		c.c1, c.c2, c.c3 = c.hwb()
		c.c4 = 0
		c.space = space.Hwb
		return true
	default:
		return false
	}
}
