// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package colors

import (
	"strconv"
	"strings"

	"github.com/thmalt/colors/space"
)

func (c Color) String() string {
	if !c.space.IsValid() {
		return "Color(<invalid space: " + strconv.FormatUint(uint64(c.space), 10) + ">)"
	}

	var b strings.Builder
	b.Grow(64)

	switch c.space {
	case space.XyzD65:
		b.WriteString("color(xyz-d65 ")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 8))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 8))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 8))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.XyzD50:
		b.WriteString("color(xyz-d50 ")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 8))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 8))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 8))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.LinearSrgb:
		b.WriteString("color(srgb-linear ")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 6))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.Srgb:
		b.WriteString("color(srgb ")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 6))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.LinearDisplayP3:
		b.WriteString("color(display-p3-linear ")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 6))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.DisplayP3:
		b.WriteString("color(display-p3 ")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 6))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.LinearA98:
		b.WriteString("color(a98-rgb-linear ")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 6))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.A98:
		b.WriteString("color(a98-rgb ")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 6))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.LinearProPhoto:
		b.WriteString("color(prophoto-rgb-linear ")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 6))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.ProPhoto:
		b.WriteString("color(prophoto-rgb ")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 6))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.LinearRec2020:
		b.WriteString("color(rec2020-linear ")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 6))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.Rec2020:
		b.WriteString("color(rec2020 ")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 6))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.Hsl:
		b.WriteString("hsl(")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 2))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2*100, 2))
		b.WriteByte('%')
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3*100, 2))
		b.WriteByte('%')

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.Hsv:
		b.WriteString("hsv(")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 2))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2*100, 2))
		b.WriteByte('%')
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3*100, 2))
		b.WriteByte('%')

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.Hwb:
		b.WriteString("hwb(")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 2))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2*100, 2))
		b.WriteByte('%')
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3*100, 2))
		b.WriteByte('%')

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.Lab:
		b.WriteString("lab(")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 4))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 4))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 4))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.Lch:
		b.WriteString("lch(")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 4))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 4))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 4))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.Oklab:
		b.WriteString("oklab(")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 6))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	case space.Oklch:
		b.WriteString("oklch(")
		b.WriteString(formatNormalizedFloatPrec(c.c1, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c2, 6))
		b.WriteByte(' ')
		b.WriteString(formatNormalizedFloatPrec(c.c3, 4))

		if alpha := normalizeFloat(c.alpha); alpha != 1 {
			b.WriteString(" / ")
			b.WriteString(formatFloatPrec(alpha, 6))
		}

		b.WriteString(")")
	default:
		panic("unreachable")
	}

	return b.String()
}
