// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package colors

import (
	"github.com/thmalt/colors/space"
)

// To converts the color to the destination color space.
func (c Color) To(dst space.Space) (Color, bool) {
	if !c.space.IsValid() {
		return Color{}, false
	}

	if c.space == dst {
		return c, true
	}

	switch dst {
	case space.Srgb:
		r, g, b := c.Srgb()
		return Color{space: space.Srgb, c1: r, c2: g, c3: b, alpha: c.alpha}, true
	case space.LinearSrgb:
		r, g, b := c.LinearSrgb()
		return Color{space: space.LinearSrgb, c1: r, c2: g, c3: b, alpha: c.alpha}, true
	case space.DisplayP3:
		r, g, b := c.DisplayP3()
		return Color{space: space.DisplayP3, c1: r, c2: g, c3: b, alpha: c.alpha}, true
	case space.LinearDisplayP3:
		r, g, b := c.LinearDisplayP3()
		return Color{space: space.LinearDisplayP3, c1: r, c2: g, c3: b, alpha: c.alpha}, true
	case space.A98:
		r, g, b := c.A98()
		return Color{space: space.A98, c1: r, c2: g, c3: b, alpha: c.alpha}, true
	case space.LinearA98:
		r, g, b := c.LinearA98()
		return Color{space: space.LinearA98, c1: r, c2: g, c3: b, alpha: c.alpha}, true
	case space.ProPhoto:
		r, g, b := c.ProPhoto()
		return Color{space: space.ProPhoto, c1: r, c2: g, c3: b, alpha: c.alpha}, true
	case space.LinearProPhoto:
		r, g, b := c.LinearProPhoto()
		return Color{space: space.LinearProPhoto, c1: r, c2: g, c3: b, alpha: c.alpha}, true
	case space.Rec2020:
		r, g, b := c.Rec2020()
		return Color{space: space.Rec2020, c1: r, c2: g, c3: b, alpha: c.alpha}, true
	case space.Rec2020OETF:
		r, g, b := c.Rec2020OETF()
		return Color{space: space.Rec2020OETF, c1: r, c2: g, c3: b, alpha: c.alpha}, true
	case space.LinearRec2020:
		r, g, b := c.LinearRec2020()
		return Color{space: space.LinearRec2020, c1: r, c2: g, c3: b, alpha: c.alpha}, true
	case space.LinearRec2100:
		r, g, b := c.LinearRec2100()
		return Color{space: space.LinearRec2100, c1: r, c2: g, c3: b, alpha: c.alpha}, true
	case space.Rec2100PQ:
		r, g, b := c.Rec2100PQ()
		return Color{space: space.Rec2100PQ, c1: r, c2: g, c3: b, alpha: c.alpha}, true
	case space.Rec2100HLG:
		r, g, b := c.Rec2100HLG()
		return Color{space: space.Rec2100HLG, c1: r, c2: g, c3: b, alpha: c.alpha}, true
	case space.XyzD50:
		x, y, z := c.XyzD50()
		return Color{space: space.XyzD50, c1: x, c2: y, c3: z, alpha: c.alpha}, true
	case space.XyzD65:
		x, y, z := c.XyzD65()
		return Color{space: space.XyzD65, c1: x, c2: y, c3: z, alpha: c.alpha}, true
	case space.XyzAbsD65:
		x, y, z := c.XyzAbsD65()
		return Color{space: space.XyzAbsD65, c1: x, c2: y, c3: z, alpha: c.alpha}, true
	case space.XyYD50:
		x, y, luminance := c.XyYD50()
		return Color{space: space.XyYD50, c1: x, c2: y, c3: luminance, alpha: c.alpha}, true
	case space.XyYD65:
		x, y, luminance := c.XyYD65()
		return Color{space: space.XyYD65, c1: x, c2: y, c3: luminance, alpha: c.alpha}, true
	case space.LabD50:
		l, a, b := c.LabD50()
		return Color{space: space.LabD50, c1: l, c2: a, c3: b, alpha: c.alpha}, true
	case space.LchD50:
		l, c1, h := c.LchD50()
		return Color{space: space.LchD50, c1: l, c2: c1, c3: h, alpha: c.alpha}, true
	case space.LabD65:
		l, a, b := c.LabD65()
		return Color{space: space.LabD65, c1: l, c2: a, c3: b, alpha: c.alpha}, true
	case space.LchD65:
		l, c1, h := c.LchD65()
		return Color{space: space.LchD65, c1: l, c2: c1, c3: h, alpha: c.alpha}, true
	case space.LuvD50:
		l, u, v := c.LuvD50()
		return Color{space: space.LuvD50, c1: l, c2: u, c3: v, alpha: c.alpha}, true
	case space.LchuvD50:
		l, c1, h := c.LchuvD50()
		return Color{space: space.LchuvD50, c1: l, c2: c1, c3: h, alpha: c.alpha}, true
	case space.LuvD65:
		l, u, v := c.LuvD65()
		return Color{space: space.LuvD65, c1: l, c2: u, c3: v, alpha: c.alpha}, true
	case space.LchuvD65:
		l, c1, h := c.LchuvD65()
		return Color{space: space.LchuvD65, c1: l, c2: c1, c3: h, alpha: c.alpha}, true
	case space.Oklab:
		l, a, b := c.Oklab()
		return Color{space: space.Oklab, c1: l, c2: a, c3: b, alpha: c.alpha}, true
	case space.Oklch:
		l, c1, h := c.Oklch()
		return Color{space: space.Oklch, c1: l, c2: c1, c3: h, alpha: c.alpha}, true
	case space.Hsl:
		h, s, l := c.Hsl()
		return Color{space: space.Hsl, c1: h, c2: s, c3: l, alpha: c.alpha}, true
	case space.Hsv:
		h, s, v := c.Hsv()
		return Color{space: space.Hsv, c1: h, c2: s, c3: v, alpha: c.alpha}, true
	case space.Hwb:
		h, w, b := c.Hwb()
		return Color{space: space.Hwb, c1: h, c2: w, c3: b, alpha: c.alpha}, true
	default:
		return Color{}, false
	}
}
