// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package colors

import (
	"github.com/thmalt/colors/space"
)

func Mix(c1, c2 Color, t float64, opts MixOptions) Color {
	if c1.space.IsValid() && c2.space.IsValid() && !opts.Space.IsValid() {
		return Color{}
	}

	c1 = c1.MustTo(opts.Space)
	c2 = c2.MustTo(opts.Space)

	switch opts.Space {
	case space.XyzD65:
		return mixXyzD65(c1, c2, t, opts)
	case space.XyzD50:
		return mixXyzD50(c1, c2, t, opts)
	case space.LinearSrgb:
		return mixLinearSrgb(c1, c2, t, opts)
	case space.Srgb:
		return mixSrgb(c1, c2, t, opts)
	case space.LinearDisplayP3:
		return mixLinearDisplayP3(c1, c2, t, opts)
	case space.DisplayP3:
		return mixDisplayP3(c1, c2, t, opts)
	case space.LinearA98:
		return mixLinearA98(c1, c2, t, opts)
	case space.A98:
		return mixA98(c1, c2, t, opts)
	case space.LinearProPhoto:
		return mixLinearProPhoto(c1, c2, t, opts)
	case space.ProPhoto:
		return mixProPhoto(c1, c2, t, opts)
	case space.LinearRec2020:
		return mixLinearRec2020(c1, c2, t, opts)
	case space.Rec2020:
		return mixRec2020(c1, c2, t, opts)
	case space.Hsl:
		return mixHsl(c1, c2, t, opts)
	case space.Hsv:
		return mixHsv(c1, c2, t, opts)
	case space.Hwb:
		return mixHwb(c1, c2, t, opts)
	case space.Lab:
		return mixLab(c1, c2, t, opts)
	case space.Lch:
		return mixLch(c1, c2, t, opts)
	case space.Oklab:
		return mixOklab(c1, c2, t, opts)
	case space.Oklch:
		return mixOklch(c1, c2, t, opts)
	}

	panic("unreachable")
}

func mixXyzD65(cl1, cl2 Color, t float64, opts MixOptions) Color {
	x1, y1, z1 := cl1.XyzD65()
	x2, y2, z2 := cl2.XyzD65()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		x1 *= alpha1
		y1 *= alpha1
		z1 *= alpha1

		x2 *= alpha2
		y2 *= alpha2
		z2 *= alpha2
	}

	x := lerp(x1, x2, t)
	y := lerp(y1, y2, t)
	z := lerp(z1, z2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			x *= inv
			y *= inv
			z *= inv
		}
	}

	return Color{space: space.XyzD65, c1: x, c2: y, c3: z, alpha: alpha}
}

func mixXyzD50(cl1, cl2 Color, t float64, opts MixOptions) Color {
	x1, y1, z1 := cl1.XyzD50()
	x2, y2, z2 := cl2.XyzD50()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		x1 *= alpha1
		y1 *= alpha1
		z1 *= alpha1

		x2 *= alpha2
		y2 *= alpha2
		z2 *= alpha2
	}

	x := lerp(x1, x2, t)
	y := lerp(y1, y2, t)
	z := lerp(z1, z2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			x *= inv
			y *= inv
			z *= inv
		}
	}

	return Color{space: space.XyzD50, c1: x, c2: y, c3: z, alpha: alpha}
}

func mixLinearSrgb(cl1, cl2 Color, t float64, opts MixOptions) Color {
	r1, g1, b1 := cl1.LinearSrgb()
	r2, g2, b2 := cl2.LinearSrgb()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		r1 *= alpha1
		g1 *= alpha1
		b1 *= alpha1

		r2 *= alpha2
		g2 *= alpha2
		b2 *= alpha2
	}

	r := lerp(r1, r2, t)
	g := lerp(g1, g2, t)
	b := lerp(b1, b2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			r *= inv
			g *= inv
			b *= inv
		}
	}

	return Color{space: space.LinearSrgb, c1: r, c2: g, c3: b, alpha: alpha}
}

func mixSrgb(cl1, cl2 Color, t float64, opts MixOptions) Color {
	r1, g1, b1 := cl1.Srgb()
	r2, g2, b2 := cl2.Srgb()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		r1 *= alpha1
		g1 *= alpha1
		b1 *= alpha1

		r2 *= alpha2
		g2 *= alpha2
		b2 *= alpha2
	}

	r := lerp(r1, r2, t)
	g := lerp(g1, g2, t)
	b := lerp(b1, b2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			r *= inv
			g *= inv
			b *= inv
		}
	}

	return Color{space: space.Srgb, c1: r, c2: g, c3: b, alpha: alpha}
}

func mixLinearDisplayP3(cl1, cl2 Color, t float64, opts MixOptions) Color {
	r1, g1, b1 := cl1.LinearDisplayP3()
	r2, g2, b2 := cl2.LinearDisplayP3()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		r1 *= alpha1
		g1 *= alpha1
		b1 *= alpha1

		r2 *= alpha2
		g2 *= alpha2
		b2 *= alpha2
	}

	r := lerp(r1, r2, t)
	g := lerp(g1, g2, t)
	b := lerp(b1, b2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			r *= inv
			g *= inv
			b *= inv
		}
	}

	return Color{space: space.LinearDisplayP3, c1: r, c2: g, c3: b, alpha: alpha}
}

func mixDisplayP3(cl1, cl2 Color, t float64, opts MixOptions) Color {
	r1, g1, b1 := cl1.DisplayP3()
	r2, g2, b2 := cl2.DisplayP3()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		r1 *= alpha1
		g1 *= alpha1
		b1 *= alpha1

		r2 *= alpha2
		g2 *= alpha2
		b2 *= alpha2
	}

	r := lerp(r1, r2, t)
	g := lerp(g1, g2, t)
	b := lerp(b1, b2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			r *= inv
			g *= inv
			b *= inv
		}
	}

	return Color{space: space.DisplayP3, c1: r, c2: g, c3: b, alpha: alpha}
}

func mixLinearA98(cl1, cl2 Color, t float64, opts MixOptions) Color {
	r1, g1, b1 := cl1.LinearA98()
	r2, g2, b2 := cl2.LinearA98()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		r1 *= alpha1
		g1 *= alpha1
		b1 *= alpha1

		r2 *= alpha2
		g2 *= alpha2
		b2 *= alpha2
	}

	r := lerp(r1, r2, t)
	g := lerp(g1, g2, t)
	b := lerp(b1, b2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			r *= inv
			g *= inv
			b *= inv
		}
	}

	return Color{space: space.LinearA98, c1: r, c2: g, c3: b, alpha: alpha}
}

func mixA98(cl1, cl2 Color, t float64, opts MixOptions) Color {
	r1, g1, b1 := cl1.A98()
	r2, g2, b2 := cl2.A98()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		r1 *= alpha1
		g1 *= alpha1
		b1 *= alpha1

		r2 *= alpha2
		g2 *= alpha2
		b2 *= alpha2
	}

	r := lerp(r1, r2, t)
	g := lerp(g1, g2, t)
	b := lerp(b1, b2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			r *= inv
			g *= inv
			b *= inv
		}
	}

	return Color{space: space.A98, c1: r, c2: g, c3: b, alpha: alpha}
}

func mixLinearProPhoto(cl1, cl2 Color, t float64, opts MixOptions) Color {
	r1, g1, b1 := cl1.LinearProPhoto()
	r2, g2, b2 := cl2.LinearProPhoto()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		r1 *= alpha1
		g1 *= alpha1
		b1 *= alpha1

		r2 *= alpha2
		g2 *= alpha2
		b2 *= alpha2
	}

	r := lerp(r1, r2, t)
	g := lerp(g1, g2, t)
	b := lerp(b1, b2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			r *= inv
			g *= inv
			b *= inv
		}
	}

	return Color{space: space.LinearProPhoto, c1: r, c2: g, c3: b, alpha: alpha}
}

func mixProPhoto(cl1, cl2 Color, t float64, opts MixOptions) Color {
	r1, g1, b1 := cl1.ProPhoto()
	r2, g2, b2 := cl2.ProPhoto()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		r1 *= alpha1
		g1 *= alpha1
		b1 *= alpha1

		r2 *= alpha2
		g2 *= alpha2
		b2 *= alpha2
	}

	r := lerp(r1, r2, t)
	g := lerp(g1, g2, t)
	b := lerp(b1, b2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			r *= inv
			g *= inv
			b *= inv
		}
	}

	return Color{space: space.ProPhoto, c1: r, c2: g, c3: b, alpha: alpha}
}

func mixLinearRec2020(cl1, cl2 Color, t float64, opts MixOptions) Color {
	r1, g1, b1 := cl1.LinearRec2020()
	r2, g2, b2 := cl2.LinearRec2020()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		r1 *= alpha1
		g1 *= alpha1
		b1 *= alpha1

		r2 *= alpha2
		g2 *= alpha2
		b2 *= alpha2
	}

	r := lerp(r1, r2, t)
	g := lerp(g1, g2, t)
	b := lerp(b1, b2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			r *= inv
			g *= inv
			b *= inv
		}
	}

	return Color{space: space.LinearRec2020, c1: r, c2: g, c3: b, alpha: alpha}
}

func mixRec2020(cl1, cl2 Color, t float64, opts MixOptions) Color {
	r1, g1, b1 := cl1.Rec2020()
	r2, g2, b2 := cl2.Rec2020()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		r1 *= alpha1
		g1 *= alpha1
		b1 *= alpha1

		r2 *= alpha2
		g2 *= alpha2
		b2 *= alpha2
	}

	r := lerp(r1, r2, t)
	g := lerp(g1, g2, t)
	b := lerp(b1, b2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			r *= inv
			g *= inv
			b *= inv
		}
	}

	return Color{space: space.Rec2020, c1: r, c2: g, c3: b, alpha: alpha}
}

func mixHsl(cl1, cl2 Color, t float64, opts MixOptions) Color {
	h1, s1, l1 := cl1.Hsl()
	h2, s2, l2 := cl2.Hsl()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		s1 *= alpha1
		l1 *= alpha1

		s2 *= alpha2
		l2 *= alpha2
	}

	var h float64
	switch opts.Hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	s := lerp(s1, s2, t)
	l := lerp(l1, l2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			s *= inv
			l *= inv
		}
	}

	return Color{space: space.Hsl, c1: h, c2: s, c3: l, alpha: alpha}
}

func mixHsv(cl1, cl2 Color, t float64, opts MixOptions) Color {
	h1, s1, v1 := cl1.Hsv()
	h2, s2, v2 := cl2.Hsv()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		s1 *= alpha1
		v1 *= alpha1

		s2 *= alpha2
		v2 *= alpha2
	}

	var h float64
	switch opts.Hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	s := lerp(s1, s2, t)
	v := lerp(v1, v2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			s *= inv
			v *= inv
		}
	}

	return Color{space: space.Hsv, c1: h, c2: s, c3: v, alpha: alpha}
}

func mixHwb(cl1, cl2 Color, t float64, opts MixOptions) Color {
	h1, w1, b1 := cl1.Hwb()
	h2, w2, b2 := cl2.Hwb()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		w1 *= alpha1
		b1 *= alpha1

		w2 *= alpha2
		b2 *= alpha2
	}

	var h float64
	switch opts.Hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	w := lerp(w1, w2, t)
	b := lerp(b1, b2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			w *= inv
			b *= inv
		}
	}

	return Color{space: space.Hwb, c1: h, c2: w, c3: b, alpha: alpha}
}

func mixLab(cl1, cl2 Color, t float64, opts MixOptions) Color {
	l1, a1, b1 := cl1.Lab()
	l2, a2, b2 := cl2.Lab()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		l1 *= alpha1
		a1 *= alpha1
		b1 *= alpha1

		l2 *= alpha2
		a2 *= alpha2
		b2 *= alpha2
	}

	l := lerp(l1, l2, t)
	a := lerp(a1, a2, t)
	b := lerp(b1, b2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			l *= inv
			a *= inv
			b *= inv
		}
	}

	return Color{space: space.Lab, c1: l, c2: a, c3: b, alpha: alpha}
}

func mixLch(cl1, cl2 Color, t float64, opts MixOptions) Color {
	l1, c1, h1 := cl1.Lch()
	l2, c2, h2 := cl2.Lch()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		l1 *= alpha1
		c1 *= alpha1

		l2 *= alpha2
		c2 *= alpha2
	}

	l := lerp(l1, l2, t)
	c := lerp(c1, c2, t)

	var h float64
	switch opts.Hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			l *= inv
			c *= inv
		}
	}

	return Color{space: space.Lch, c1: l, c2: c, c3: h, alpha: alpha}
}

func mixOklab(cl1, cl2 Color, t float64, opts MixOptions) Color {
	l1, a1, b1 := cl1.Oklab()
	l2, a2, b2 := cl2.Oklab()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		l1 *= alpha1
		a1 *= alpha1
		b1 *= alpha1

		l2 *= alpha2
		a2 *= alpha2
		b2 *= alpha2
	}

	l := lerp(l1, l2, t)
	a := lerp(a1, a2, t)
	b := lerp(b1, b2, t)

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			l *= inv
			a *= inv
			b *= inv
		}
	}

	return Color{space: space.Oklab, c1: l, c2: a, c3: b, alpha: alpha}
}

func mixOklch(cl1, cl2 Color, t float64, opts MixOptions) Color {
	l1, c1, h1 := cl1.Oklch()
	l2, c2, h2 := cl2.Oklch()

	alpha1, alpha2 := cl1.Alpha(), cl2.Alpha()

	alpha := lerp(alpha1, alpha2, t)

	if opts.Premultiplied {
		l1 *= alpha1
		c1 *= alpha1

		l2 *= alpha2
		c2 *= alpha2
	}

	l := lerp(l1, l2, t)
	c := lerp(c1, c2, t)

	var h float64
	switch opts.Hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	if opts.Premultiplied {
		if alpha != 0 {
			inv := 1 / alpha

			l *= inv
			c *= inv
		}
	}

	return Color{space: space.Oklch, c1: l, c2: c, c3: h, alpha: alpha}
}
