// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package colors

import (
	"github.com/thmalt/colors/internal/ascii"
	"github.com/thmalt/colors/space"
)

func (p *parser) parseColorSpace(originColor Color) (Color, error) {
	var buf [20]byte
	n := copy(buf[:], p.t.Text())
	ascii.ToLowerBytes(buf[:n])

	p.t.Next()

	switch string(buf[:n]) {
	case "srgb":
		return p.parseColorSpace01(originColor, space.Srgb, space.ChIdentFlagsRGB)
	case "srgb-linear":
		return p.parseColorSpace01(originColor, space.LinearSrgb, space.ChIdentFlagsRGB)
	case "display-p3":
		return p.parseColorSpace01(originColor, space.DisplayP3, space.ChIdentFlagsRGB)
	case "display-p3-linear":
		return p.parseColorSpace01(originColor, space.LinearDisplayP3, space.ChIdentFlagsRGB)
	case "a98-rgb":
		return p.parseColorSpace01(originColor, space.A98, space.ChIdentFlagsRGB)
	case "a98-rgb-linear":
		return p.parseColorSpace01(originColor, space.LinearA98, space.ChIdentFlagsRGB)
	case "prophoto-rgb":
		return p.parseColorSpace01(originColor, space.ProPhoto, space.ChIdentFlagsRGB)
	case "prophoto-rgb-linear":
		return p.parseColorSpace01(originColor, space.LinearProPhoto, space.ChIdentFlagsRGB)
	case "rec2020":
		return p.parseColorSpace01(originColor, space.Rec2020, space.ChIdentFlagsRGB)
	case "rec2020-oetf":
		return p.parseColorSpace01(originColor, space.Rec2020OETF, space.ChIdentFlagsRGB)
	case "rec2020-linear":
		return p.parseColorSpace01(originColor, space.LinearRec2020, space.ChIdentFlagsRGB)
	case "rec2100-linear":
		return p.parseColorSpace01(originColor, space.LinearRec2100, space.ChIdentFlagsRGB)
	case "rec2100-pq":
		return p.parseColorSpace01(originColor, space.Rec2100PQ, space.ChIdentFlagsRGB)
	case "rec2100-hlg":
		return p.parseColorSpace01(originColor, space.Rec2100HLG, space.ChIdentFlagsRGB)
	case "xyz-d50":
		return p.parseColorSpace01(originColor, space.XyzD50, space.ChIdentFlagsXYZ)
	case "xyz-d65", "xyz":
		return p.parseColorSpace01(originColor, space.XyzD65, space.ChIdentFlagsXYZ)
	case "xyz-abs-d65":
		return p.parseColorSpace01(originColor, space.XyzAbsD65, space.ChIdentFlagsXYZ)
	case "xyy-d50":
		return p.parseColorSpace01(originColor, space.XyYD50, space.ChIdentFlagsXYLuminance)
	case "xyy-d65", "xyy":
		return p.parseColorSpace01(originColor, space.XyYD65, space.ChIdentFlagsXYLuminance)
	case "lab-d65":
		return p.parseLabLike(originColor, space.LabD65, 100, 125)
	case "lch-d65":
		return p.parseLchLike(originColor, space.LchD65, 100, 150)
	case "luv-d65":
		return p.parseLabLike(originColor, space.LuvD65, 100, 215)
	case "lchuv-d65":
		return p.parseLchLike(originColor, space.LchuvD65, 100, 220)
	default:
		return Color{}, errUnknownColorSpace
	}
}
