// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package interp

func Srgb(r1, g1, b1 float64, r2, g2, b2 float64, t float64) (r, g, b float64) {
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func SrgbAlpha(r1, g1, b1, alpha1 float64, r2, g2, b2, alpha2 float64, t float64) (r, g, b, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func LinearSrgb(r1, g1, b1 float64, r2, g2, b2 float64, t float64) (r, g, b float64) {
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func LinearSrgbAlpha(r1, g1, b1, alpha1 float64, r2, g2, b2, alpha2 float64, t float64) (r, g, b, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func DisplayP3(r1, g1, b1 float64, r2, g2, b2 float64, t float64) (r, g, b float64) {
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func DisplayP3Alpha(r1, g1, b1, alpha1 float64, r2, g2, b2, alpha2 float64, t float64) (r, g, b, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func LinearDisplayP3(r1, g1, b1 float64, r2, g2, b2 float64, t float64) (r, g, b float64) {
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func LinearDisplayP3Alpha(r1, g1, b1, alpha1 float64, r2, g2, b2, alpha2 float64, t float64) (r, g, b, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func A98(r1, g1, b1 float64, r2, g2, b2 float64, t float64) (r, g, b float64) {
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func A98Alpha(r1, g1, b1, alpha1 float64, r2, g2, b2, alpha2 float64, t float64) (r, g, b, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func LinearA98(r1, g1, b1 float64, r2, g2, b2 float64, t float64) (r, g, b float64) {
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func LinearA98Alpha(r1, g1, b1, alpha1 float64, r2, g2, b2, alpha2 float64, t float64) (r, g, b, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func ProPhoto(r1, g1, b1 float64, r2, g2, b2 float64, t float64) (r, g, b float64) {
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func ProPhotoAlpha(r1, g1, b1, alpha1 float64, r2, g2, b2, alpha2 float64, t float64) (r, g, b, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func LinearProPhoto(r1, g1, b1 float64, r2, g2, b2 float64, t float64) (r, g, b float64) {
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func LinearProPhotoAlpha(r1, g1, b1, alpha1 float64, r2, g2, b2, alpha2 float64, t float64) (r, g, b, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func Rec2020(r1, g1, b1 float64, r2, g2, b2 float64, t float64) (r, g, b float64) {
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func Rec2020Alpha(r1, g1, b1, alpha1 float64, r2, g2, b2, alpha2 float64, t float64) (r, g, b, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func LinearRec2020(r1, g1, b1 float64, r2, g2, b2 float64, t float64) (r, g, b float64) {
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func LinearRec2020Alpha(r1, g1, b1, alpha1 float64, r2, g2, b2, alpha2 float64, t float64) (r, g, b, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	r = lerp(r1, r2, t)
	g = lerp(g1, g2, t)
	b = lerp(b1, b2, t)
	return
}

func XyzD50(x1, y1, z1 float64, x2, y2, z2 float64, t float64) (x, y, z float64) {
	x = lerp(x1, x2, t)
	y = lerp(y1, y2, t)
	z = lerp(z1, z2, t)
	return
}

func XyzD50Alpha(x1, y1, z1, alpha1 float64, x2, y2, z2, alpha2 float64, t float64) (x, y, z, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	x = lerp(x1, x2, t)
	y = lerp(y1, y2, t)
	z = lerp(z1, z2, t)
	return
}

func XyzD65(x1, y1, z1 float64, x2, y2, z2 float64, t float64) (x, y, z float64) {
	x = lerp(x1, x2, t)
	y = lerp(y1, y2, t)
	z = lerp(z1, z2, t)
	return
}

func XyzD65Alpha(x1, y1, z1, alpha1 float64, x2, y2, z2, alpha2 float64, t float64) (x, y, z, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	x = lerp(x1, x2, t)
	y = lerp(y1, y2, t)
	z = lerp(z1, z2, t)
	return
}

func XyYD50(x1, y1, luminance1 float64, x2, y2, luminance2 float64, t float64) (x, y, luminance float64) {
	x = lerp(x1, x2, t)
	y = lerp(y1, y2, t)
	luminance = lerp(luminance1, luminance2, t)
	return
}

func XyYD50Alpha(x1, y1, luminance1, alpha1 float64, x2, y2, luminance2, alpha2 float64, t float64) (x, y, luminance, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	x = lerp(x1, x2, t)
	y = lerp(y1, y2, t)
	luminance = lerp(luminance1, luminance2, t)
	return
}

func XyYD65(x1, y1, luminance1 float64, x2, y2, luminance2 float64, t float64) (x, y, luminance float64) {
	x = lerp(x1, x2, t)
	y = lerp(y1, y2, t)
	luminance = lerp(luminance1, luminance2, t)
	return
}

func XyYD65Alpha(x1, y1, luminance1, alpha1 float64, x2, y2, luminance2, alpha2 float64, t float64) (x, y, luminance, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	x = lerp(x1, x2, t)
	y = lerp(y1, y2, t)
	luminance = lerp(luminance1, luminance2, t)
	return
}

func LabD50(l1, a1, b1 float64, l2, a2, b2 float64, t float64) (l, a, b float64) {
	l = lerp(l1, l2, t)
	a = lerp(a1, a2, t)
	b = lerp(b1, b2, t)
	return
}

func LabD50Alpha(l1, a1, b1, alpha1 float64, l2, a2, b2, alpha2 float64, t float64) (l, a, b, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	l = lerp(l1, l2, t)
	a = lerp(a1, a2, t)
	b = lerp(b1, b2, t)
	return
}

func LchD50(l1, c1, h1 float64, l2, c2, h2 float64, t float64, hue HueInterpolation) (l, c, h float64) {
	l = lerp(l1, l2, t)
	c = lerp(c1, c2, t)

	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	return
}

func LchD50Alpha(l1, c1, h1, alpha1 float64, l2, c2, h2, alpha2 float64, t float64, hue HueInterpolation) (l, c, h, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	l = lerp(l1, l2, t)
	c = lerp(c1, c2, t)

	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	return
}

func LabD65(l1, a1, b1 float64, l2, a2, b2 float64, t float64) (l, a, b float64) {
	l = lerp(l1, l2, t)
	a = lerp(a1, a2, t)
	b = lerp(b1, b2, t)
	return
}

func LabD65Alpha(l1, a1, b1, alpha1 float64, l2, a2, b2, alpha2 float64, t float64) (l, a, b, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	l = lerp(l1, l2, t)
	a = lerp(a1, a2, t)
	b = lerp(b1, b2, t)
	return
}

func LchD65(l1, c1, h1 float64, l2, c2, h2 float64, t float64, hue HueInterpolation) (l, c, h float64) {
	l = lerp(l1, l2, t)
	c = lerp(c1, c2, t)

	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	return
}

func LchD65Alpha(l1, c1, h1, alpha1 float64, l2, c2, h2, alpha2 float64, t float64, hue HueInterpolation) (l, c, h, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	l = lerp(l1, l2, t)
	c = lerp(c1, c2, t)

	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	return
}

func LuvD50(l1, u1, v1 float64, l2, u2, v2 float64, t float64, hue HueInterpolation) (l, u, v float64) {
	l = lerp(l1, l2, t)
	u = lerp(u1, u2, t)
	v = lerp(v1, v2, t)
	return
}

func LuvD50Alpha(l1, u1, v1, alpha1 float64, l2, u2, v2, alpha2 float64, t float64, hue HueInterpolation) (l, u, v, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	l = lerp(l1, l2, t)
	u = lerp(u1, u2, t)
	v = lerp(v1, v2, t)
	return
}

func LchuvD50(l1, c1, h1 float64, l2, c2, h2 float64, t float64, hue HueInterpolation) (l, c, h float64) {
	l = lerp(l1, l2, t)
	c = lerp(c1, c2, t)

	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	return
}

func LchuvD50Alpha(l1, c1, h1, alpha1 float64, l2, c2, h2, alpha2 float64, t float64, hue HueInterpolation) (l, c, h, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	l = lerp(l1, l2, t)
	c = lerp(c1, c2, t)

	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	return
}

func LuvD65(l1, u1, v1 float64, l2, u2, v2 float64, t float64, hue HueInterpolation) (l, u, v float64) {
	l = lerp(l1, l2, t)
	u = lerp(u1, u2, t)
	v = lerp(v1, v2, t)
	return
}

func LuvD65Alpha(l1, u1, v1, alpha1 float64, l2, u2, v2, alpha2 float64, t float64, hue HueInterpolation) (l, u, v, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	l = lerp(l1, l2, t)
	u = lerp(u1, u2, t)
	v = lerp(v1, v2, t)
	return
}

func LchuvD65(l1, c1, h1 float64, l2, c2, h2 float64, t float64, hue HueInterpolation) (l, c, h float64) {
	l = lerp(l1, l2, t)
	c = lerp(c1, c2, t)

	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	return
}

func LchuvD65Alpha(l1, c1, h1, alpha1 float64, l2, c2, h2, alpha2 float64, t float64, hue HueInterpolation) (l, c, h, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	l = lerp(l1, l2, t)
	c = lerp(c1, c2, t)

	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	return
}

func Oklab(l1, a1, b1 float64, l2, a2, b2 float64, t float64) (l, a, b float64) {
	l = lerp(l1, l2, t)
	a = lerp(a1, a2, t)
	b = lerp(b1, b2, t)
	return
}

func OklabAlpha(l1, a1, b1, alpha1 float64, l2, a2, b2, alpha2 float64, t float64) (l, a, b, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	l = lerp(l1, l2, t)
	a = lerp(a1, a2, t)
	b = lerp(b1, b2, t)
	return
}

func Oklch(l1, c1, h1 float64, l2, c2, h2 float64, t float64, hue HueInterpolation) (l, c, h float64) {
	l = lerp(l1, l2, t)
	c = lerp(c1, c2, t)

	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	return
}

func OklchAlpha(l1, c1, h1, alpha1 float64, l2, c2, h2, alpha2 float64, t float64, hue HueInterpolation) (l, c, h, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	l = lerp(l1, l2, t)
	c = lerp(c1, c2, t)

	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	return
}

func Hsl(h1, s1, l1 float64, h2, s2, l2 float64, t float64, hue HueInterpolation) (h, s, l float64) {
	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	s = lerp(s1, s2, t)
	l = lerp(l1, l2, t)
	return
}

func HslAlpha(h1, s1, l1, alpha1 float64, h2, s2, l2, alpha2 float64, t float64, hue HueInterpolation) (h, s, l, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	s = lerp(s1, s2, t)
	l = lerp(l1, l2, t)
	return
}

func Hsv(h1, s1, v1 float64, h2, s2, v2 float64, t float64, hue HueInterpolation) (h, s, v float64) {
	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	s = lerp(s1, s2, t)
	v = lerp(v1, v2, t)
	return
}

func HsvAlpha(h1, s1, v1, alpha1 float64, h2, s2, v2, alpha2 float64, t float64, hue HueInterpolation) (h, s, v, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	s = lerp(s1, s2, t)
	v = lerp(v1, v2, t)
	return
}

func Hwb(h1, w1, b1 float64, h2, w2, b2 float64, t float64, hue HueInterpolation) (h, w, b float64) {
	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	w = lerp(w1, w2, t)
	b = lerp(b1, b2, t)
	return
}

func HwbAlpha(h1, w1, b1, alpha1 float64, h2, w2, b2, alpha2 float64, t float64, hue HueInterpolation) (h, w, b, alpha float64) {
	alpha = lerp(alpha1, alpha2, t)
	switch hue {
	case HueShorter:
		h = lerpHueShorter(h1, h2, t)
	case HueLonger:
		h = lerpHueLonger(h1, h2, t)
	case HueIncreasing:
		h = lerpHueIncreasing(h1, h2, t)
	case HueDecreasing:
		h = lerpHueDecreasing(h1, h2, t)
	}

	w = lerp(w1, w2, t)
	b = lerp(b1, b2, t)
	return
}
