// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package space

import (
	"github.com/thmalt/colors/internal/ascii"
)

const MaxChannelCount = 4

type ChIdentFlags uint32

const (
	ChIdentAlpha     ChIdentFlags = 1 << iota // alpha
	ChIdentA                                  // a
	ChIdentB                                  // b
	ChIdentC                                  // c
	ChIdentG                                  // g
	ChIdentH                                  // h
	ChIdentL                                  // l
	ChIdentR                                  // r
	ChIdentS                                  // s
	ChIdentU                                  // u
	ChIdentV                                  // v
	ChIdentW                                  // w
	ChIdentX                                  // x
	ChIdentY                                  // y
	ChIdentZ                                  // z
	ChIdentLuminance                          // luminance
)

const (
	ChIdentFlagsRGB         = ChIdentR | ChIdentG | ChIdentB | ChIdentAlpha         // r, g, b, alpha
	ChIdentFlagsXYZ         = ChIdentX | ChIdentY | ChIdentZ | ChIdentAlpha         // x, y, z, alpha
	ChIdentFlagsXYLuminance = ChIdentX | ChIdentY | ChIdentLuminance | ChIdentAlpha // x, y, luminance, alpha
	ChIdentFlagsLAB         = ChIdentL | ChIdentA | ChIdentB | ChIdentAlpha         // l, a, b, alpha
	ChIdentFlagsLCH         = ChIdentL | ChIdentC | ChIdentH | ChIdentAlpha         // l, c, h, alpha
	ChIdentFlagsLUV         = ChIdentL | ChIdentU | ChIdentV | ChIdentAlpha         // l, u, v, alpha
	ChIdentFlagsHSL         = ChIdentH | ChIdentS | ChIdentL | ChIdentAlpha         // h, s, l, alpha
	ChIdentFlagsHSV         = ChIdentH | ChIdentS | ChIdentV | ChIdentAlpha         // h, s, v, alpha
	ChIdentFlagsHWB         = ChIdentH | ChIdentW | ChIdentB | ChIdentAlpha         // h, w, b, alpha
)

func (f ChIdentFlags) Has(flags ChIdentFlags) bool {
	return f&flags == flags
}

func (f ChIdentFlags) String() string {
	switch f {
	case 0:
		return "<nil>"

	case ChIdentAlpha:
		return "alpha"
	case ChIdentA:
		return "a"
	case ChIdentB:
		return "b"
	case ChIdentC:
		return "c"
	case ChIdentG:
		return "g"
	case ChIdentH:
		return "h"
	case ChIdentL:
		return "l"
	case ChIdentR:
		return "r"
	case ChIdentS:
		return "s"
	case ChIdentU:
		return "u"
	case ChIdentV:
		return "v"
	case ChIdentW:
		return "w"
	case ChIdentX:
		return "x"
	case ChIdentY:
		return "y"
	case ChIdentZ:
		return "z"
	case ChIdentLuminance:
		return "luminance"

	default:
		if f&(f-1) == 0 {
			return "<unknown>"
		}
		return "<multi flags>"
	}
}

func LookupChIdentFlags(ident string) ChIdentFlags {
	switch len(ident) {
	case 1:
		switch ident[0] | ('a' - 'A') {
		case 'a':
			return ChIdentA
		case 'b':
			return ChIdentB
		case 'c':
			return ChIdentC
		case 'g':
			return ChIdentG
		case 'h':
			return ChIdentH
		case 'l':
			return ChIdentL
		case 'r':
			return ChIdentR
		case 's':
			return ChIdentS
		case 'u':
			return ChIdentU
		case 'v':
			return ChIdentV
		case 'w':
			return ChIdentW
		case 'x':
			return ChIdentX
		case 'y':
			return ChIdentY
		case 'z':
			return ChIdentZ
		}
	case 5:
		if ascii.EqualFold(ident, "alpha") {
			return ChIdentAlpha
		}
	case 9:
		if ascii.EqualFold(ident, "luminance") {
			return ChIdentLuminance
		}
	}
	return 0
}

func (s Space) ChIdentFlags() ChIdentFlags {
	switch s {
	case Srgb, LinearSrgb, DisplayP3, LinearDisplayP3,
		A98, LinearA98, ProPhoto, LinearProPhoto,
		Rec2020, Rec2020OETF, LinearRec2020, LinearRec2100,
		Rec2100PQ, Rec2100HLG:
		return ChIdentFlagsRGB
	case XyzD50, XyzD65, XyzAbsD65:
		return ChIdentFlagsXYZ
	case XyYD50, XyYD65:
		return ChIdentFlagsXYLuminance
	case LabD50, LabD65, Oklab:
		return ChIdentFlagsLAB
	case LchD50, LchD65, LchuvD50, LchuvD65,
		Oklch:
		return ChIdentFlagsLCH
	case LuvD50, LuvD65:
		return ChIdentFlagsLUV
	case Hsl:
		return ChIdentFlagsHSL
	case Hsv:
		return ChIdentFlagsHSV
	case Hwb:
		return ChIdentFlagsHWB
	default:
		return 0
	}
}

func (s Space) ChIndex(flag ChIdentFlags) int {
	switch s {
	case Srgb, LinearSrgb, DisplayP3, LinearDisplayP3,
		A98, LinearA98, ProPhoto, LinearProPhoto,
		Rec2020, Rec2020OETF, LinearRec2020, LinearRec2100,
		Rec2100PQ, Rec2100HLG:
		switch flag {
		case ChIdentR:
			return 0
		case ChIdentG:
			return 1
		case ChIdentB:
			return 2
		}
	case XyzD50, XyzD65, XyzAbsD65:
		switch flag {
		case ChIdentX:
			return 0
		case ChIdentY:
			return 1
		case ChIdentZ:
			return 2
		}
	case XyYD50, XyYD65:
		switch flag {
		case ChIdentX:
			return 0
		case ChIdentY:
			return 1
		case ChIdentLuminance:
			return 2
		}
	case LabD50, LabD65, Oklab:
		switch flag {
		case ChIdentL:
			return 0
		case ChIdentA:
			return 1
		case ChIdentB:
			return 2
		}
	case LchD50, LchD65, LchuvD50, LchuvD65,
		Oklch:
		switch flag {
		case ChIdentL:
			return 0
		case ChIdentC:
			return 1
		case ChIdentH:
			return 2
		}
	case LuvD50, LuvD65:
		switch flag {
		case ChIdentL:
			return 0
		case ChIdentU:
			return 1
		case ChIdentV:
			return 2
		}
	case Hsl:
		switch flag {
		case ChIdentH:
			return 0
		case ChIdentS:
			return 1
		case ChIdentL:
			return 2
		}
	case Hsv:
		switch flag {
		case ChIdentH:
			return 0
		case ChIdentS:
			return 1
		case ChIdentV:
			return 2
		}
	case Hwb:
		switch flag {
		case ChIdentH:
			return 0
		case ChIdentW:
			return 1
		case ChIdentB:
			return 2
		}
	}

	if flag == ChIdentAlpha {
		if n := s.ChannelCount(); n > 0 {
			return n
		}
	}

	return -1
}
