// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package space

import (
	"strconv"
)

type Space uint8

const (
	InvalidSpace Space = iota

	Srgb
	LinearSrgb
	DisplayP3
	LinearDisplayP3
	A98
	LinearA98
	ProPhoto
	LinearProPhoto
	Rec2020
	Rec2020OETF
	LinearRec2020
	LinearRec2100
	Rec2100PQ
	Rec2100HLG
	XyzD50
	XyzD65
	XyzAbsD65
	XyYD50
	XyYD65
	LabD50
	LchD50
	LabD65
	LchD65
	LuvD50
	LchuvD50
	LuvD65
	LchuvD65
	Oklab
	Oklch
	Hsl
	Hsv
	Hwb

	// SpaceCount is the number of defined spaces, including InvalidSpace.
	SpaceCount

	// FirstSpace is the first valid color space.
	FirstSpace = Srgb

	// LastSpace is the last valid color space.
	LastSpace = Hwb
)

const (
	// Xyz is an alias for [XyzD65].
	Xyz = XyzD65
	// XyY is an alias for [XyYD65].
	XyY = XyYD65
	// Lab is an alias for [LabD50].
	Lab = LabD50
	// Lch is an alias for [LchD50].
	Lch = LchD50
	// Luv is an alias for [LuvD50].
	Luv = LuvD50
	// Lchuv is an alias for [LchuvD50].
	Lchuv = LchuvD50
)

func (s Space) String() string {
	switch s {
	case InvalidSpace:
		return "Invalid"
	case Srgb:
		return "Srgb"
	case LinearSrgb:
		return "LinearSrgb"
	case DisplayP3:
		return "DisplayP3"
	case LinearDisplayP3:
		return "LinearDisplayP3"
	case A98:
		return "A98"
	case LinearA98:
		return "LinearA98"
	case ProPhoto:
		return "ProPhoto"
	case LinearProPhoto:
		return "LinearProPhoto"
	case Rec2020:
		return "Rec2020"
	case Rec2020OETF:
		return "Rec2020OETF"
	case LinearRec2020:
		return "LinearRec2020"
	case LinearRec2100:
		return "LinearRec2100"
	case Rec2100PQ:
		return "Rec2100PQ"
	case Rec2100HLG:
		return "Rec2100HLG"
	case XyzD50:
		return "XyzD50"
	case XyzD65:
		return "XyzD65"
	case XyzAbsD65:
		return "XyzAbsD65"
	case XyYD50:
		return "XyYD50"
	case XyYD65:
		return "XyYD65"
	case LabD50:
		return "LabD50"
	case LchD50:
		return "LchD50"
	case LabD65:
		return "LabD65"
	case LchD65:
		return "LchD65"
	case LuvD50:
		return "LuvD50"
	case LchuvD50:
		return "LchuvD50"
	case LuvD65:
		return "LuvD65"
	case LchuvD65:
		return "LchuvD65"
	case Oklab:
		return "Oklab"
	case Oklch:
		return "Oklch"
	case Hsl:
		return "Hsl"
	case Hsv:
		return "Hsv"
	case Hwb:
		return "Hwb"
	default:
		return "Space(" + strconv.FormatUint(uint64(s), 10) + ")"
	}
}
