// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package space

import (
	"strconv"
)

type Space uint8

const (
	XyzD65 Space = iota
	XyzD50
	LinearSrgb
	Srgb
	LinearDisplayP3
	DisplayP3
	LinearA98
	A98
	LinearProPhoto
	ProPhoto
	LinearRec2020
	Rec2020
	Hsl
	Hsv
	Hwb
	Lab
	Lch
	Oklab
	Oklch

	// Available space count
	SpaceCount
)

var spaceInfos = [...]*spaceInfo{
	&xyzD65Info,
	&xyzD50Info,
	&linearSrgbInfo,
	&srgbInfo,
	&linearDisplayP3Info,
	&displayP3Info,
	&linearA98Info,
	&a98Info,
	&linearProPhotoInfo,
	&proPhotoInfo,
	&linearRec2020Info,
	&rec2020Info,
	&hslInfo,
	&hsvInfo,
	&hwbInfo,
	&labInfo,
	&lchInfo,
	&oklabInfo,
	&oklchInfo,
}

var xyzD65Info = spaceInfo{
	name:        "XyzD65",
	displayName: "CIE XYZ D65",
	cssName:     "xyz-d65",
	whitePoint:  D65,
	channels: []Channel{
		{
			Name:        "X",
			Symbol:      "x",
			DisplayName: "X",
			Min:         0,
			Max:         1,
			Precision:   8,
		},
		{
			Name:        "Y",
			Symbol:      "y",
			DisplayName: "Y",
			Min:         0,
			Max:         1,
			Precision:   8,
		},
		{
			Name:        "Z",
			Symbol:      "z",
			DisplayName: "Z",
			Min:         0,
			Max:         1,
			Precision:   8,
		},
	},
	useColorFunction: true,
}

var xyzD50Info = spaceInfo{
	name:        "XyzD50",
	displayName: "CIE XYZ D50",
	cssName:     "xyz-d50",
	whitePoint:  D50,
	channels: []Channel{
		{
			Name:        "X",
			Symbol:      "x",
			DisplayName: "X",
			Min:         0,
			Max:         1,
			Precision:   8,
		},
		{
			Name:        "Y",
			Symbol:      "y",
			DisplayName: "Y",
			Min:         0,
			Max:         1,
			Precision:   8,
		},
		{
			Name:        "Z",
			Symbol:      "z",
			DisplayName: "Z",
			Min:         0,
			Max:         1,
			Precision:   8,
		},
	},
	useColorFunction: true,
}

var linearSrgbInfo = spaceInfo{
	name:        "LinearSrgb",
	displayName: "Linear sRGB",
	cssName:     "srgb-linear",
	whitePoint:  D65,
	channels: []Channel{
		{
			Name:        "Red",
			Symbol:      "r",
			DisplayName: "Red",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Green",
			Symbol:      "g",
			DisplayName: "Green",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Blue",
			Symbol:      "b",
			DisplayName: "Blue",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
	},
	useColorFunction: true,
}

var srgbInfo = spaceInfo{
	name:        "Srgb",
	displayName: "sRGB",
	cssName:     "srgb",
	whitePoint:  D65,
	channels: []Channel{
		{
			Name:        "Red",
			Symbol:      "r",
			DisplayName: "Red",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Green",
			Symbol:      "g",
			DisplayName: "Green",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Blue",
			Symbol:      "b",
			DisplayName: "Blue",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
	},
	useColorFunction: true,
}

var linearDisplayP3Info = spaceInfo{
	name:        "LinearDisplayP3",
	displayName: "Linear Display P3",
	cssName:     "display-p3-linear",
	whitePoint:  D65,
	channels: []Channel{
		{
			Name:        "Red",
			Symbol:      "r",
			DisplayName: "Red",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Green",
			Symbol:      "g",
			DisplayName: "Green",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Blue",
			Symbol:      "b",
			DisplayName: "Blue",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
	},
	useColorFunction: true,
}

var displayP3Info = spaceInfo{
	name:        "DisplayP3",
	displayName: "Display P3",
	cssName:     "display-p3",
	whitePoint:  D65,
	channels: []Channel{
		{
			Name:        "Red",
			Symbol:      "r",
			DisplayName: "Red",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Green",
			Symbol:      "g",
			DisplayName: "Green",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Blue",
			Symbol:      "b",
			DisplayName: "Blue",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
	},
	useColorFunction: true,
}

var linearA98Info = spaceInfo{
	name:        "LinearA98",
	displayName: "Linear Adobe RGB (1998)",
	cssName:     "a98-rgb-linear",
	whitePoint:  D65,
	channels: []Channel{
		{
			Name:        "Red",
			Symbol:      "r",
			DisplayName: "Red",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Green",
			Symbol:      "g",
			DisplayName: "Green",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Blue",
			Symbol:      "b",
			DisplayName: "Blue",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
	},
	useColorFunction: true,
}

var a98Info = spaceInfo{
	name:        "A98",
	displayName: "Adobe RGB (1998)",
	cssName:     "a98-rgb",
	whitePoint:  D65,
	channels: []Channel{
		{
			Name:        "Red",
			Symbol:      "r",
			DisplayName: "Red",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Green",
			Symbol:      "g",
			DisplayName: "Green",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Blue",
			Symbol:      "b",
			DisplayName: "Blue",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
	},
	useColorFunction: true,
}

var linearProPhotoInfo = spaceInfo{
	name:        "LinearProPhoto",
	displayName: "Linear ProPhoto",
	cssName:     "prophoto-rgb-linear",
	whitePoint:  D50,
	channels: []Channel{
		{
			Name:        "Red",
			Symbol:      "r",
			DisplayName: "Red",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Green",
			Symbol:      "g",
			DisplayName: "Green",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Blue",
			Symbol:      "b",
			DisplayName: "Blue",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
	},
	useColorFunction: true,
}

var proPhotoInfo = spaceInfo{
	name:        "ProPhoto",
	displayName: "ProPhoto",
	cssName:     "prophoto-rgb",
	whitePoint:  D50,
	channels: []Channel{
		{
			Name:        "Red",
			Symbol:      "r",
			DisplayName: "Red",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Green",
			Symbol:      "g",
			DisplayName: "Green",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Blue",
			Symbol:      "b",
			DisplayName: "Blue",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
	},
	useColorFunction: true,
}

var linearRec2020Info = spaceInfo{
	name:        "LinearRec2020",
	displayName: "Linear Rec. 2020",
	cssName:     "rec2020-linear",
	whitePoint:  D65,
	channels: []Channel{
		{
			Name:        "Red",
			Symbol:      "r",
			DisplayName: "Red",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Green",
			Symbol:      "g",
			DisplayName: "Green",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Blue",
			Symbol:      "b",
			DisplayName: "Blue",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
	},
	useColorFunction: true,
}

var rec2020Info = spaceInfo{
	name:        "Rec2020",
	displayName: "Rec. 2020",
	cssName:     "rec2020",
	whitePoint:  D65,
	channels: []Channel{
		{
			Name:        "Red",
			Symbol:      "r",
			DisplayName: "Red",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Green",
			Symbol:      "g",
			DisplayName: "Green",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:        "Blue",
			Symbol:      "b",
			DisplayName: "Blue",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
	},
	useColorFunction: true,
}

var hslInfo = spaceInfo{
	name:        "Hsl",
	displayName: "HSL",
	cssName:     "hsl",
	whitePoint:  D65,
	channels: []Channel{
		{
			Name:        "Hue",
			Symbol:      "h",
			DisplayName: "Hue",
			Min:         0,
			Max:         360,
			Circular:    true,
			Unit:        UnitDegree,
			Precision:   2,
		},
		{
			Name:        "Saturation",
			Symbol:      "s",
			DisplayName: "Saturation",
			Min:         0,
			Max:         1,
			Unit:        UnitPercent,
			Precision:   4,
		},
		{
			Name:        "Lightness",
			Symbol:      "l",
			DisplayName: "Lightness",
			Min:         0,
			Max:         1,
			Unit:        UnitPercent,
			Precision:   4,
		},
	},
}

var hsvInfo = spaceInfo{
	name:        "Hsv",
	displayName: "HSV",
	cssName:     "hsv",
	whitePoint:  D65,
	channels: []Channel{
		{
			Name:        "Hue",
			Symbol:      "h",
			DisplayName: "Hue",
			Min:         0,
			Max:         360,
			Circular:    true,
			Unit:        UnitDegree,
			Precision:   2,
		},
		{
			Name:        "Saturation",
			Symbol:      "s",
			DisplayName: "Saturation",
			Min:         0,
			Max:         1,
			Unit:        UnitPercent,
			Precision:   4,
		},
		{
			Name:        "Value",
			Symbol:      "v",
			DisplayName: "Value",
			Min:         0,
			Max:         1,
			Unit:        UnitPercent,
			Precision:   4,
		},
	},
}

var hwbInfo = spaceInfo{
	name:        "Hwb",
	displayName: "HWB",
	cssName:     "hwb",
	whitePoint:  D65,
	channels: []Channel{
		{
			Name:        "Hue",
			Symbol:      "h",
			DisplayName: "Hue",
			Min:         0,
			Max:         360,
			Circular:    true,
			Unit:        UnitDegree,
			Precision:   2,
		},
		{
			Name:        "Whiteness",
			Symbol:      "w",
			DisplayName: "Whiteness",
			Min:         0,
			Max:         1,
			Unit:        UnitPercent,
			Precision:   4,
		},
		{
			Name:        "Blackness",
			Symbol:      "b",
			DisplayName: "Blackness",
			Min:         0,
			Max:         1,
			Unit:        UnitPercent,
			Precision:   4,
		},
	},
}

var labInfo = spaceInfo{
	name:        "Lab",
	displayName: "CIE Lab",
	cssName:     "lab",
	whitePoint:  D50,
	channels: []Channel{
		{
			Name:        "Lightness",
			Symbol:      "l",
			DisplayName: "Lightness",
			Min:         0,
			Max:         100,
			Precision:   4,
		},
		{
			Name:         "A",
			Symbol:       "a",
			DisplayName:  "Green-Red",
			Min:          -125,
			Max:          125,
			Unrestricted: true,
			Precision:    4,
		},
		{
			Name:         "B",
			Symbol:       "b",
			DisplayName:  "Blue-Yellow",
			Min:          -125,
			Max:          125,
			Unrestricted: true,
			Precision:    4,
		},
	},
}

var lchInfo = spaceInfo{
	name:        "Lch",
	displayName: "CIE LCh",
	cssName:     "lch",
	whitePoint:  D50,
	channels: []Channel{
		{
			Name:        "Lightness",
			Symbol:      "l",
			DisplayName: "Lightness",
			Min:         0,
			Max:         100,
			Precision:   4,
		},
		{
			Name:         "Chroma",
			Symbol:       "c",
			DisplayName:  "Chroma",
			Min:          0,
			Max:          150,
			Unrestricted: true,
			Precision:    4,
		},
		{
			Name:        "Hue",
			Symbol:      "h",
			DisplayName: "Hue",
			Min:         0,
			Max:         360,
			Circular:    true,
			Unit:        UnitDegree,
			Precision:   4,
		},
	},
}

var oklabInfo = spaceInfo{
	name:        "Oklab",
	displayName: "Oklab",
	cssName:     "oklab",
	whitePoint:  D65,
	channels: []Channel{
		{
			Name:        "Lightness",
			Symbol:      "l",
			DisplayName: "Lightness",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:         "A",
			Symbol:       "a",
			DisplayName:  "Green-Red",
			Min:          -0.4,
			Max:          0.4,
			Unrestricted: true,
			Precision:    6,
		},
		{
			Name:         "B",
			Symbol:       "b",
			DisplayName:  "Blue-Yellow",
			Min:          -0.4,
			Max:          0.4,
			Unrestricted: true,
			Precision:    6,
		},
	},
}

var oklchInfo = spaceInfo{
	name:        "Oklch",
	displayName: "Oklch",
	cssName:     "oklch",
	whitePoint:  D65,
	channels: []Channel{
		{
			Name:        "Lightness",
			Symbol:      "l",
			DisplayName: "Lightness",
			Min:         0,
			Max:         1,
			Precision:   6,
		},
		{
			Name:         "Chroma",
			Symbol:       "c",
			DisplayName:  "Chroma",
			Min:          0,
			Max:          0.4,
			Unrestricted: true,
			Precision:    6,
		},
		{
			Name:        "Hue",
			Symbol:      "h",
			DisplayName: "Hue",
			Min:         0,
			Max:         360,
			Circular:    true,
			Unit:        UnitDegree,
			Precision:   4,
		},
	},
}

func (s Space) String() string {
	switch s {
	case XyzD65:
		return "XyzD65"
	case XyzD50:
		return "XyzD50"
	case LinearSrgb:
		return "LinearSrgb"
	case Srgb:
		return "Srgb"
	case LinearDisplayP3:
		return "LinearDisplayP3"
	case DisplayP3:
		return "DisplayP3"
	case LinearA98:
		return "LinearA98"
	case A98:
		return "A98"
	case LinearProPhoto:
		return "LinearProPhoto"
	case ProPhoto:
		return "ProPhoto"
	case LinearRec2020:
		return "LinearRec2020"
	case Rec2020:
		return "Rec2020"
	case Hsl:
		return "Hsl"
	case Hsv:
		return "Hsv"
	case Hwb:
		return "Hwb"
	case Lab:
		return "Lab"
	case Lch:
		return "Lch"
	case Oklab:
		return "Oklab"
	case Oklch:
		return "Oklch"
	default:
		return "Space(" + strconv.FormatUint(uint64(s), 10) + ")"
	}
}
