// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package space

var spaceInfos = [...]*spaceInfo{
	nil,
	&xyzD65Info,
	&xyYInfo,
	&xyzD50Info,
	&linearSrgbInfo,
	&srgbInfo,
	&linearDisplayP3Info,
	&displayP3Info,
	&linearA98Info,
	&a98Info,
	&linearProPhotoInfo,
	&proPhotoInfo,
	&linearRec2020Info,
	&rec2020Info,
	&hslInfo,
	&hsvInfo,
	&hwbInfo,
	&labInfo,
	&lchInfo,
	&luvInfo,
	&lchuvInfo,
	&oklabInfo,
	&oklchInfo,
}
var spaceChannelCounts = [...]uint8{
	0, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3,
}

var coordinateSystems = [...]CoordinateSystem{
	Cartesian, Cartesian, Cartesian, Cartesian, Cartesian, Cartesian, Cartesian, Cartesian,
	Cartesian, Cartesian, Cartesian, Cartesian, Cartesian, Cartesian, Polar, Polar,
	Polar, Cartesian, Polar, Polar, Polar, Cartesian, Polar,
}
