// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package space

import (
	"strconv"
)

type Space uint8

const (
	InvalidSpace Space = iota

	XyzD65
	// XyY is the CIE xyY color space using the D65 reference white.
	// Conversions involving other reference whites automatically perform
	// chromatic adaptation.
	XyY
	XyzD50
	LinearSrgb
	Srgb
	LinearDisplayP3
	DisplayP3
	LinearA98
	A98
	LinearProPhoto
	ProPhoto
	LinearRec2020
	Rec2020
	Hsl
	Hsv
	Hwb
	Lab
	Lch
	Luv
	Lchuv
	Oklab
	Oklch

	// SpaceCount is the number of defined spaces, including InvalidSpace.
	SpaceCount

	// FirstSpace is the first valid color space.
	FirstSpace = XyzD65

	// LastSpace is the last valid color space.
	LastSpace = Oklch
)

func (s Space) String() string {
	switch s {
	case InvalidSpace:
		return "Invalid"
	case XyzD65:
		return "XyzD65"
	case XyY:
		return "XyY"
	case XyzD50:
		return "XyzD50"
	case LinearSrgb:
		return "LinearSrgb"
	case Srgb:
		return "Srgb"
	case LinearDisplayP3:
		return "LinearDisplayP3"
	case DisplayP3:
		return "DisplayP3"
	case LinearA98:
		return "LinearA98"
	case A98:
		return "A98"
	case LinearProPhoto:
		return "LinearProPhoto"
	case ProPhoto:
		return "ProPhoto"
	case LinearRec2020:
		return "LinearRec2020"
	case Rec2020:
		return "Rec2020"
	case Hsl:
		return "Hsl"
	case Hsv:
		return "Hsv"
	case Hwb:
		return "Hwb"
	case Lab:
		return "Lab"
	case Lch:
		return "Lch"
	case Luv:
		return "Luv"
	case Lchuv:
		return "Lchuv"
	case Oklab:
		return "Oklab"
	case Oklch:
		return "Oklch"
	default:
		return "Space(" + strconv.FormatUint(uint64(s), 10) + ")"
	}
}
