// Code generated by running "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package space

type WhitePoint struct {
	Name string

	X float64
	Y float64
	Z float64
}

var (
	D50 = WhitePoint{
		Name: "D50",
		X:    0.9642956764295677,
		Y:    1,
		Z:    0.8251046025104602,
	}

	D65 = WhitePoint{
		Name: "D65",
		X:    0.9504559270516716,
		Y:    1,
		Z:    1.0890577507598784,
	}
)
