// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package convert

// XyzToLab is an alias for [XyzD65ToLabD50]
func XyzToLab(x, y, z float64) (l, a, b float64) {
	return XyzD65ToLabD50(x, y, z)
}

// LabToXyz is an alias for [LabD50ToXyzD65]
func LabToXyz(l, a, b float64) (x, y, z float64) {
	return LabD50ToXyzD65(l, a, b)
}

// XyzToLch is an alias for [XyzD65ToLchD50]
func XyzToLch(x, y, z float64) (l, c, h float64) {
	return XyzD65ToLchD50(x, y, z)
}

// LchToXyz is an alias for [LchD50ToXyzD65]
func LchToXyz(l, c, h float64) (x, y, z float64) {
	return LchD50ToXyzD65(l, c, h)
}

// XyzToLuv is an alias for [XyzD65ToLuvD50]
func XyzToLuv(x, y, z float64) (l, u, v float64) {
	return XyzD65ToLuvD50(x, y, z)
}

// LuvToXyz is an alias for [LuvD50ToXyzD65]
func LuvToXyz(l, u, v float64) (x, y, z float64) {
	return LuvD50ToXyzD65(l, u, v)
}

// XyzToLchuv is an alias for [XyzD65ToLchuvD50]
func XyzToLchuv(x, y, z float64) (l, c, h float64) {
	return XyzD65ToLchuvD50(x, y, z)
}

// LchuvToXyz is an alias for [LchuvD50ToXyzD65]
func LchuvToXyz(l, c, h float64) (x, y, z float64) {
	return LchuvD50ToXyzD65(l, c, h)
}

// XyYToLab is an alias for [XyYD65ToLabD50]
func XyYToLab(x, y, luminance float64) (l, a, b float64) {
	return XyYD65ToLabD50(x, y, luminance)
}

// LabToXyY is an alias for [LabD50ToXyYD65]
func LabToXyY(l, a, b float64) (x, y, luminance float64) {
	return LabD50ToXyYD65(l, a, b)
}

// XyYToLch is an alias for [XyYD65ToLchD50]
func XyYToLch(x, y, luminance float64) (l, c, h float64) {
	return XyYD65ToLchD50(x, y, luminance)
}

// LchToXyY is an alias for [LchD50ToXyYD65]
func LchToXyY(l, c, h float64) (x, y, luminance float64) {
	return LchD50ToXyYD65(l, c, h)
}

// XyYToLuv is an alias for [XyYD65ToLuvD50]
func XyYToLuv(x, y, luminance float64) (l, u, v float64) {
	return XyYD65ToLuvD50(x, y, luminance)
}

// LuvToXyY is an alias for [LuvD50ToXyYD65]
func LuvToXyY(l, u, v float64) (x, y, luminance float64) {
	return LuvD50ToXyYD65(l, u, v)
}

// XyYToLchuv is an alias for [XyYD65ToLchuvD50]
func XyYToLchuv(x, y, luminance float64) (l, c, h float64) {
	return XyYD65ToLchuvD50(x, y, luminance)
}

// LchuvToXyY is an alias for [LchuvD50ToXyYD65]
func LchuvToXyY(l, c, h float64) (x, y, luminance float64) {
	return LchuvD50ToXyYD65(l, c, h)
}

// LabToLch is an alias for [LabD50ToLchD50]
func LabToLch(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLchD50(l, a, b)
}

// LchToLab is an alias for [LchD50ToLabD50]
func LchToLab(l, c, h float64) (float64, float64, float64) {
	return LchD50ToLabD50(l, c, h)
}

// LabToLuv is an alias for [LabD50ToLuvD50]
func LabToLuv(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLuvD50(l, a, b)
}

// LuvToLab is an alias for [LuvD50ToLabD50]
func LuvToLab(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToLabD50(l, u, v)
}

// LabToLchuv is an alias for [LabD50ToLchuvD50]
func LabToLchuv(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLchuvD50(l, a, b)
}

// LchuvToLab is an alias for [LchuvD50ToLabD50]
func LchuvToLab(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToLabD50(l, c, h)
}

// LchToLuv is an alias for [LchD50ToLuvD50]
func LchToLuv(l, c, h float64) (float64, float64, float64) {
	return LchD50ToLuvD50(l, c, h)
}

// LuvToLch is an alias for [LuvD50ToLchD50]
func LuvToLch(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToLchD50(l, u, v)
}

// LchToLchuv is an alias for [LchD50ToLchuvD50]
func LchToLchuv(l, c, h float64) (float64, float64, float64) {
	return LchD50ToLchuvD50(l, c, h)
}

// LchuvToLch is an alias for [LchuvD50ToLchD50]
func LchuvToLch(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToLchD50(l, c, h)
}

// LuvToLchuv is an alias for [LuvD50ToLchuvD50]
func LuvToLchuv(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToLchuvD50(l, u, v)
}

// LchuvToLuv is an alias for [LchuvD50ToLuvD50]
func LchuvToLuv(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToLuvD50(l, c, h)
}

// XyzToSrgb is an alias for [XyzD65ToSrgb]
func XyzToSrgb(x, y, z float64) (r, g, b float64) {
	return XyzD65ToSrgb(x, y, z)
}

// SrgbToXyz is an alias for [SrgbToXyzD65]
func SrgbToXyz(r, g, b float64) (x, y, z float64) {
	return SrgbToXyzD65(r, g, b)
}

// XyzToLinearSrgb is an alias for [XyzD65ToLinearSrgb]
func XyzToLinearSrgb(x, y, z float64) (r, g, b float64) {
	return XyzD65ToLinearSrgb(x, y, z)
}

// LinearSrgbToXyz is an alias for [LinearSrgbToXyzD65]
func LinearSrgbToXyz(r, g, b float64) (x, y, z float64) {
	return LinearSrgbToXyzD65(r, g, b)
}

// XyzToDisplayP3 is an alias for [XyzD65ToDisplayP3]
func XyzToDisplayP3(x, y, z float64) (r, g, b float64) {
	return XyzD65ToDisplayP3(x, y, z)
}

// DisplayP3ToXyz is an alias for [DisplayP3ToXyzD65]
func DisplayP3ToXyz(r, g, b float64) (x, y, z float64) {
	return DisplayP3ToXyzD65(r, g, b)
}

// XyzToLinearDisplayP3 is an alias for [XyzD65ToLinearDisplayP3]
func XyzToLinearDisplayP3(x, y, z float64) (r, g, b float64) {
	return XyzD65ToLinearDisplayP3(x, y, z)
}

// LinearDisplayP3ToXyz is an alias for [LinearDisplayP3ToXyzD65]
func LinearDisplayP3ToXyz(r, g, b float64) (x, y, z float64) {
	return LinearDisplayP3ToXyzD65(r, g, b)
}

// XyzToA98 is an alias for [XyzD65ToA98]
func XyzToA98(x, y, z float64) (r, g, b float64) {
	return XyzD65ToA98(x, y, z)
}

// A98ToXyz is an alias for [A98ToXyzD65]
func A98ToXyz(r, g, b float64) (x, y, z float64) {
	return A98ToXyzD65(r, g, b)
}

// XyzToLinearA98 is an alias for [XyzD65ToLinearA98]
func XyzToLinearA98(x, y, z float64) (r, g, b float64) {
	return XyzD65ToLinearA98(x, y, z)
}

// LinearA98ToXyz is an alias for [LinearA98ToXyzD65]
func LinearA98ToXyz(r, g, b float64) (x, y, z float64) {
	return LinearA98ToXyzD65(r, g, b)
}

// XyzToProPhoto is an alias for [XyzD65ToProPhoto]
func XyzToProPhoto(x, y, z float64) (r, g, b float64) {
	return XyzD65ToProPhoto(x, y, z)
}

// ProPhotoToXyz is an alias for [ProPhotoToXyzD65]
func ProPhotoToXyz(r, g, b float64) (x, y, z float64) {
	return ProPhotoToXyzD65(r, g, b)
}

// XyzToLinearProPhoto is an alias for [XyzD65ToLinearProPhoto]
func XyzToLinearProPhoto(x, y, z float64) (r, g, b float64) {
	return XyzD65ToLinearProPhoto(x, y, z)
}

// LinearProPhotoToXyz is an alias for [LinearProPhotoToXyzD65]
func LinearProPhotoToXyz(r, g, b float64) (x, y, z float64) {
	return LinearProPhotoToXyzD65(r, g, b)
}

// XyzToRec2020 is an alias for [XyzD65ToRec2020]
func XyzToRec2020(x, y, z float64) (r, g, b float64) {
	return XyzD65ToRec2020(x, y, z)
}

// Rec2020ToXyz is an alias for [Rec2020ToXyzD65]
func Rec2020ToXyz(r, g, b float64) (x, y, z float64) {
	return Rec2020ToXyzD65(r, g, b)
}

// XyzToRec2020OETF is an alias for [XyzD65ToRec2020OETF]
func XyzToRec2020OETF(x, y, z float64) (r, g, b float64) {
	return XyzD65ToRec2020OETF(x, y, z)
}

// Rec2020OETFToXyz is an alias for [Rec2020OETFToXyzD65]
func Rec2020OETFToXyz(r, g, b float64) (x, y, z float64) {
	return Rec2020OETFToXyzD65(r, g, b)
}

// XyzToLinearRec2020 is an alias for [XyzD65ToLinearRec2020]
func XyzToLinearRec2020(x, y, z float64) (r, g, b float64) {
	return XyzD65ToLinearRec2020(x, y, z)
}

// LinearRec2020ToXyz is an alias for [LinearRec2020ToXyzD65]
func LinearRec2020ToXyz(r, g, b float64) (x, y, z float64) {
	return LinearRec2020ToXyzD65(r, g, b)
}

// XyzToLinearRec2100 is an alias for [XyzD65ToLinearRec2100]
func XyzToLinearRec2100(x, y, z float64) (r, g, b float64) {
	return XyzD65ToLinearRec2100(x, y, z)
}

// LinearRec2100ToXyz is an alias for [LinearRec2100ToXyzD65]
func LinearRec2100ToXyz(r, g, b float64) (x, y, z float64) {
	return LinearRec2100ToXyzD65(r, g, b)
}

// XyzToRec2100PQ is an alias for [XyzD65ToRec2100PQ]
func XyzToRec2100PQ(x, y, z float64) (r, g, b float64) {
	return XyzD65ToRec2100PQ(x, y, z)
}

// Rec2100PQToXyz is an alias for [Rec2100PQToXyzD65]
func Rec2100PQToXyz(r, g, b float64) (x, y, z float64) {
	return Rec2100PQToXyzD65(r, g, b)
}

// XyzToRec2100HLG is an alias for [XyzD65ToRec2100HLG]
func XyzToRec2100HLG(x, y, z float64) (r, g, b float64) {
	return XyzD65ToRec2100HLG(x, y, z)
}

// Rec2100HLGToXyz is an alias for [Rec2100HLGToXyzD65]
func Rec2100HLGToXyz(r, g, b float64) (x, y, z float64) {
	return Rec2100HLGToXyzD65(r, g, b)
}

// XyzToXyzD50 is an alias for [XyzD65ToXyzD50]
func XyzToXyzD50(x, y, z float64) (float64, float64, float64) {
	return XyzD65ToXyzD50(x, y, z)
}

// XyzD50ToXyz is an alias for [XyzD50ToXyzD65]
func XyzD50ToXyz(x, y, z float64) (float64, float64, float64) {
	return XyzD50ToXyzD65(x, y, z)
}

// XyzToXyzAbsD65 is an alias for [XyzD65ToXyzAbsD65]
func XyzToXyzAbsD65(x, y, z float64) (float64, float64, float64) {
	return XyzD65ToXyzAbsD65(x, y, z)
}

// XyzAbsD65ToXyz is an alias for [XyzAbsD65ToXyzD65]
func XyzAbsD65ToXyz(x, y, z float64) (float64, float64, float64) {
	return XyzAbsD65ToXyzD65(x, y, z)
}

// XyzToXyYD50 is an alias for [XyzD65ToXyYD50]
func XyzToXyYD50(x, y, z float64) (float64, float64, float64) {
	return XyzD65ToXyYD50(x, y, z)
}

// XyYD50ToXyz is an alias for [XyYD50ToXyzD65]
func XyYD50ToXyz(x, y, luminance float64) (float64, float64, float64) {
	return XyYD50ToXyzD65(x, y, luminance)
}

// XyzToXyYD65 is an alias for [XyzD65ToXyYD65]
func XyzToXyYD65(x, y, z float64) (float64, float64, float64) {
	return XyzD65ToXyYD65(x, y, z)
}

// XyYD65ToXyz is an alias for [XyYD65ToXyzD65]
func XyYD65ToXyz(x, y, luminance float64) (float64, float64, float64) {
	return XyYD65ToXyzD65(x, y, luminance)
}

// XyzToLabD50 is an alias for [XyzD65ToLabD50]
func XyzToLabD50(x, y, z float64) (l, a, b float64) {
	return XyzD65ToLabD50(x, y, z)
}

// LabD50ToXyz is an alias for [LabD50ToXyzD65]
func LabD50ToXyz(l, a, b float64) (x, y, z float64) {
	return LabD50ToXyzD65(l, a, b)
}

// XyzToLchD50 is an alias for [XyzD65ToLchD50]
func XyzToLchD50(x, y, z float64) (l, c, h float64) {
	return XyzD65ToLchD50(x, y, z)
}

// LchD50ToXyz is an alias for [LchD50ToXyzD65]
func LchD50ToXyz(l, c, h float64) (x, y, z float64) {
	return LchD50ToXyzD65(l, c, h)
}

// XyzToLabD65 is an alias for [XyzD65ToLabD65]
func XyzToLabD65(x, y, z float64) (l, a, b float64) {
	return XyzD65ToLabD65(x, y, z)
}

// LabD65ToXyz is an alias for [LabD65ToXyzD65]
func LabD65ToXyz(l, a, b float64) (x, y, z float64) {
	return LabD65ToXyzD65(l, a, b)
}

// XyzToLchD65 is an alias for [XyzD65ToLchD65]
func XyzToLchD65(x, y, z float64) (l, c, h float64) {
	return XyzD65ToLchD65(x, y, z)
}

// LchD65ToXyz is an alias for [LchD65ToXyzD65]
func LchD65ToXyz(l, c, h float64) (x, y, z float64) {
	return LchD65ToXyzD65(l, c, h)
}

// XyzToLuvD50 is an alias for [XyzD65ToLuvD50]
func XyzToLuvD50(x, y, z float64) (l, u, v float64) {
	return XyzD65ToLuvD50(x, y, z)
}

// LuvD50ToXyz is an alias for [LuvD50ToXyzD65]
func LuvD50ToXyz(l, u, v float64) (x, y, z float64) {
	return LuvD50ToXyzD65(l, u, v)
}

// XyzToLchuvD50 is an alias for [XyzD65ToLchuvD50]
func XyzToLchuvD50(x, y, z float64) (l, c, h float64) {
	return XyzD65ToLchuvD50(x, y, z)
}

// LchuvD50ToXyz is an alias for [LchuvD50ToXyzD65]
func LchuvD50ToXyz(l, c, h float64) (x, y, z float64) {
	return LchuvD50ToXyzD65(l, c, h)
}

// XyzToLuvD65 is an alias for [XyzD65ToLuvD65]
func XyzToLuvD65(x, y, z float64) (l, u, v float64) {
	return XyzD65ToLuvD65(x, y, z)
}

// LuvD65ToXyz is an alias for [LuvD65ToXyzD65]
func LuvD65ToXyz(l, u, v float64) (x, y, z float64) {
	return LuvD65ToXyzD65(l, u, v)
}

// XyzToLchuvD65 is an alias for [XyzD65ToLchuvD65]
func XyzToLchuvD65(x, y, z float64) (l, c, h float64) {
	return XyzD65ToLchuvD65(x, y, z)
}

// LchuvD65ToXyz is an alias for [LchuvD65ToXyzD65]
func LchuvD65ToXyz(l, c, h float64) (x, y, z float64) {
	return LchuvD65ToXyzD65(l, c, h)
}

// XyzToOklab is an alias for [XyzD65ToOklab]
func XyzToOklab(x, y, z float64) (l, a, b float64) {
	return XyzD65ToOklab(x, y, z)
}

// OklabToXyz is an alias for [OklabToXyzD65]
func OklabToXyz(l, a, b float64) (x, y, z float64) {
	return OklabToXyzD65(l, a, b)
}

// XyzToOklch is an alias for [XyzD65ToOklch]
func XyzToOklch(x, y, z float64) (l, c, h float64) {
	return XyzD65ToOklch(x, y, z)
}

// OklchToXyz is an alias for [OklchToXyzD65]
func OklchToXyz(l, c, h float64) (x, y, z float64) {
	return OklchToXyzD65(l, c, h)
}

// XyzToHsl is an alias for [XyzD65ToHsl]
func XyzToHsl(x, y, z float64) (h, s, l float64) {
	return XyzD65ToHsl(x, y, z)
}

// HslToXyz is an alias for [HslToXyzD65]
func HslToXyz(h, s, l float64) (x, y, z float64) {
	return HslToXyzD65(h, s, l)
}

// XyzToHsv is an alias for [XyzD65ToHsv]
func XyzToHsv(x, y, z float64) (h, s, v float64) {
	return XyzD65ToHsv(x, y, z)
}

// HsvToXyz is an alias for [HsvToXyzD65]
func HsvToXyz(h, s, v float64) (x, y, z float64) {
	return HsvToXyzD65(h, s, v)
}

// XyzToHwb is an alias for [XyzD65ToHwb]
func XyzToHwb(x, y, z float64) (h, w, b float64) {
	return XyzD65ToHwb(x, y, z)
}

// HwbToXyz is an alias for [HwbToXyzD65]
func HwbToXyz(h, w, b float64) (x, y, z float64) {
	return HwbToXyzD65(h, w, b)
}

// XyYToSrgb is an alias for [XyYD65ToSrgb]
func XyYToSrgb(x, y, luminance float64) (r, g, b float64) {
	return XyYD65ToSrgb(x, y, luminance)
}

// SrgbToXyY is an alias for [SrgbToXyYD65]
func SrgbToXyY(r, g, b float64) (x, y, luminance float64) {
	return SrgbToXyYD65(r, g, b)
}

// XyYToLinearSrgb is an alias for [XyYD65ToLinearSrgb]
func XyYToLinearSrgb(x, y, luminance float64) (r, g, b float64) {
	return XyYD65ToLinearSrgb(x, y, luminance)
}

// LinearSrgbToXyY is an alias for [LinearSrgbToXyYD65]
func LinearSrgbToXyY(r, g, b float64) (x, y, luminance float64) {
	return LinearSrgbToXyYD65(r, g, b)
}

// XyYToDisplayP3 is an alias for [XyYD65ToDisplayP3]
func XyYToDisplayP3(x, y, luminance float64) (r, g, b float64) {
	return XyYD65ToDisplayP3(x, y, luminance)
}

// DisplayP3ToXyY is an alias for [DisplayP3ToXyYD65]
func DisplayP3ToXyY(r, g, b float64) (x, y, luminance float64) {
	return DisplayP3ToXyYD65(r, g, b)
}

// XyYToLinearDisplayP3 is an alias for [XyYD65ToLinearDisplayP3]
func XyYToLinearDisplayP3(x, y, luminance float64) (r, g, b float64) {
	return XyYD65ToLinearDisplayP3(x, y, luminance)
}

// LinearDisplayP3ToXyY is an alias for [LinearDisplayP3ToXyYD65]
func LinearDisplayP3ToXyY(r, g, b float64) (x, y, luminance float64) {
	return LinearDisplayP3ToXyYD65(r, g, b)
}

// XyYToA98 is an alias for [XyYD65ToA98]
func XyYToA98(x, y, luminance float64) (r, g, b float64) {
	return XyYD65ToA98(x, y, luminance)
}

// A98ToXyY is an alias for [A98ToXyYD65]
func A98ToXyY(r, g, b float64) (x, y, luminance float64) {
	return A98ToXyYD65(r, g, b)
}

// XyYToLinearA98 is an alias for [XyYD65ToLinearA98]
func XyYToLinearA98(x, y, luminance float64) (r, g, b float64) {
	return XyYD65ToLinearA98(x, y, luminance)
}

// LinearA98ToXyY is an alias for [LinearA98ToXyYD65]
func LinearA98ToXyY(r, g, b float64) (x, y, luminance float64) {
	return LinearA98ToXyYD65(r, g, b)
}

// XyYToProPhoto is an alias for [XyYD65ToProPhoto]
func XyYToProPhoto(x, y, luminance float64) (r, g, b float64) {
	return XyYD65ToProPhoto(x, y, luminance)
}

// ProPhotoToXyY is an alias for [ProPhotoToXyYD65]
func ProPhotoToXyY(r, g, b float64) (x, y, luminance float64) {
	return ProPhotoToXyYD65(r, g, b)
}

// XyYToLinearProPhoto is an alias for [XyYD65ToLinearProPhoto]
func XyYToLinearProPhoto(x, y, luminance float64) (r, g, b float64) {
	return XyYD65ToLinearProPhoto(x, y, luminance)
}

// LinearProPhotoToXyY is an alias for [LinearProPhotoToXyYD65]
func LinearProPhotoToXyY(r, g, b float64) (x, y, luminance float64) {
	return LinearProPhotoToXyYD65(r, g, b)
}

// XyYToRec2020 is an alias for [XyYD65ToRec2020]
func XyYToRec2020(x, y, luminance float64) (r, g, b float64) {
	return XyYD65ToRec2020(x, y, luminance)
}

// Rec2020ToXyY is an alias for [Rec2020ToXyYD65]
func Rec2020ToXyY(r, g, b float64) (x, y, luminance float64) {
	return Rec2020ToXyYD65(r, g, b)
}

// XyYToRec2020OETF is an alias for [XyYD65ToRec2020OETF]
func XyYToRec2020OETF(x, y, luminance float64) (r, g, b float64) {
	return XyYD65ToRec2020OETF(x, y, luminance)
}

// Rec2020OETFToXyY is an alias for [Rec2020OETFToXyYD65]
func Rec2020OETFToXyY(r, g, b float64) (x, y, luminance float64) {
	return Rec2020OETFToXyYD65(r, g, b)
}

// XyYToLinearRec2020 is an alias for [XyYD65ToLinearRec2020]
func XyYToLinearRec2020(x, y, luminance float64) (r, g, b float64) {
	return XyYD65ToLinearRec2020(x, y, luminance)
}

// LinearRec2020ToXyY is an alias for [LinearRec2020ToXyYD65]
func LinearRec2020ToXyY(r, g, b float64) (x, y, luminance float64) {
	return LinearRec2020ToXyYD65(r, g, b)
}

// XyYToLinearRec2100 is an alias for [XyYD65ToLinearRec2100]
func XyYToLinearRec2100(x, y, luminance float64) (r, g, b float64) {
	return XyYD65ToLinearRec2100(x, y, luminance)
}

// LinearRec2100ToXyY is an alias for [LinearRec2100ToXyYD65]
func LinearRec2100ToXyY(r, g, b float64) (x, y, luminance float64) {
	return LinearRec2100ToXyYD65(r, g, b)
}

// XyYToRec2100PQ is an alias for [XyYD65ToRec2100PQ]
func XyYToRec2100PQ(x, y, luminance float64) (r, g, b float64) {
	return XyYD65ToRec2100PQ(x, y, luminance)
}

// Rec2100PQToXyY is an alias for [Rec2100PQToXyYD65]
func Rec2100PQToXyY(r, g, b float64) (x, y, luminance float64) {
	return Rec2100PQToXyYD65(r, g, b)
}

// XyYToRec2100HLG is an alias for [XyYD65ToRec2100HLG]
func XyYToRec2100HLG(x, y, luminance float64) (r, g, b float64) {
	return XyYD65ToRec2100HLG(x, y, luminance)
}

// Rec2100HLGToXyY is an alias for [Rec2100HLGToXyYD65]
func Rec2100HLGToXyY(r, g, b float64) (x, y, luminance float64) {
	return Rec2100HLGToXyYD65(r, g, b)
}

// XyYToXyzD50 is an alias for [XyYD65ToXyzD50]
func XyYToXyzD50(x, y, luminance float64) (float64, float64, float64) {
	return XyYD65ToXyzD50(x, y, luminance)
}

// XyzD50ToXyY is an alias for [XyzD50ToXyYD65]
func XyzD50ToXyY(x, y, z float64) (float64, float64, float64) {
	return XyzD50ToXyYD65(x, y, z)
}

// XyYToXyzD65 is an alias for [XyYD65ToXyzD65]
func XyYToXyzD65(x, y, luminance float64) (float64, float64, float64) {
	return XyYD65ToXyzD65(x, y, luminance)
}

// XyzD65ToXyY is an alias for [XyzD65ToXyYD65]
func XyzD65ToXyY(x, y, z float64) (float64, float64, float64) {
	return XyzD65ToXyYD65(x, y, z)
}

// XyYToXyzAbsD65 is an alias for [XyYD65ToXyzAbsD65]
func XyYToXyzAbsD65(x, y, luminance float64) (float64, float64, float64) {
	return XyYD65ToXyzAbsD65(x, y, luminance)
}

// XyzAbsD65ToXyY is an alias for [XyzAbsD65ToXyYD65]
func XyzAbsD65ToXyY(x, y, z float64) (float64, float64, float64) {
	return XyzAbsD65ToXyYD65(x, y, z)
}

// XyYToXyYD50 is an alias for [XyYD65ToXyYD50]
func XyYToXyYD50(x, y, luminance float64) (float64, float64, float64) {
	return XyYD65ToXyYD50(x, y, luminance)
}

// XyYD50ToXyY is an alias for [XyYD50ToXyYD65]
func XyYD50ToXyY(x, y, luminance float64) (float64, float64, float64) {
	return XyYD50ToXyYD65(x, y, luminance)
}

// XyYToLabD50 is an alias for [XyYD65ToLabD50]
func XyYToLabD50(x, y, luminance float64) (l, a, b float64) {
	return XyYD65ToLabD50(x, y, luminance)
}

// LabD50ToXyY is an alias for [LabD50ToXyYD65]
func LabD50ToXyY(l, a, b float64) (x, y, luminance float64) {
	return LabD50ToXyYD65(l, a, b)
}

// XyYToLchD50 is an alias for [XyYD65ToLchD50]
func XyYToLchD50(x, y, luminance float64) (l, c, h float64) {
	return XyYD65ToLchD50(x, y, luminance)
}

// LchD50ToXyY is an alias for [LchD50ToXyYD65]
func LchD50ToXyY(l, c, h float64) (x, y, luminance float64) {
	return LchD50ToXyYD65(l, c, h)
}

// XyYToLabD65 is an alias for [XyYD65ToLabD65]
func XyYToLabD65(x, y, luminance float64) (l, a, b float64) {
	return XyYD65ToLabD65(x, y, luminance)
}

// LabD65ToXyY is an alias for [LabD65ToXyYD65]
func LabD65ToXyY(l, a, b float64) (x, y, luminance float64) {
	return LabD65ToXyYD65(l, a, b)
}

// XyYToLchD65 is an alias for [XyYD65ToLchD65]
func XyYToLchD65(x, y, luminance float64) (l, c, h float64) {
	return XyYD65ToLchD65(x, y, luminance)
}

// LchD65ToXyY is an alias for [LchD65ToXyYD65]
func LchD65ToXyY(l, c, h float64) (x, y, luminance float64) {
	return LchD65ToXyYD65(l, c, h)
}

// XyYToLuvD50 is an alias for [XyYD65ToLuvD50]
func XyYToLuvD50(x, y, luminance float64) (l, u, v float64) {
	return XyYD65ToLuvD50(x, y, luminance)
}

// LuvD50ToXyY is an alias for [LuvD50ToXyYD65]
func LuvD50ToXyY(l, u, v float64) (x, y, luminance float64) {
	return LuvD50ToXyYD65(l, u, v)
}

// XyYToLchuvD50 is an alias for [XyYD65ToLchuvD50]
func XyYToLchuvD50(x, y, luminance float64) (l, c, h float64) {
	return XyYD65ToLchuvD50(x, y, luminance)
}

// LchuvD50ToXyY is an alias for [LchuvD50ToXyYD65]
func LchuvD50ToXyY(l, c, h float64) (x, y, luminance float64) {
	return LchuvD50ToXyYD65(l, c, h)
}

// XyYToLuvD65 is an alias for [XyYD65ToLuvD65]
func XyYToLuvD65(x, y, luminance float64) (l, u, v float64) {
	return XyYD65ToLuvD65(x, y, luminance)
}

// LuvD65ToXyY is an alias for [LuvD65ToXyYD65]
func LuvD65ToXyY(l, u, v float64) (x, y, luminance float64) {
	return LuvD65ToXyYD65(l, u, v)
}

// XyYToLchuvD65 is an alias for [XyYD65ToLchuvD65]
func XyYToLchuvD65(x, y, luminance float64) (l, c, h float64) {
	return XyYD65ToLchuvD65(x, y, luminance)
}

// LchuvD65ToXyY is an alias for [LchuvD65ToXyYD65]
func LchuvD65ToXyY(l, c, h float64) (x, y, luminance float64) {
	return LchuvD65ToXyYD65(l, c, h)
}

// XyYToOklab is an alias for [XyYD65ToOklab]
func XyYToOklab(x, y, luminance float64) (l, a, b float64) {
	return XyYD65ToOklab(x, y, luminance)
}

// OklabToXyY is an alias for [OklabToXyYD65]
func OklabToXyY(l, a, b float64) (x, y, luminance float64) {
	return OklabToXyYD65(l, a, b)
}

// XyYToOklch is an alias for [XyYD65ToOklch]
func XyYToOklch(x, y, luminance float64) (l, c, h float64) {
	return XyYD65ToOklch(x, y, luminance)
}

// OklchToXyY is an alias for [OklchToXyYD65]
func OklchToXyY(l, c, h float64) (x, y, luminance float64) {
	return OklchToXyYD65(l, c, h)
}

// XyYToHsl is an alias for [XyYD65ToHsl]
func XyYToHsl(x, y, luminance float64) (h, s, l float64) {
	return XyYD65ToHsl(x, y, luminance)
}

// HslToXyY is an alias for [HslToXyYD65]
func HslToXyY(h, s, l float64) (x, y, luminance float64) {
	return HslToXyYD65(h, s, l)
}

// XyYToHsv is an alias for [XyYD65ToHsv]
func XyYToHsv(x, y, luminance float64) (h, s, v float64) {
	return XyYD65ToHsv(x, y, luminance)
}

// HsvToXyY is an alias for [HsvToXyYD65]
func HsvToXyY(h, s, v float64) (x, y, luminance float64) {
	return HsvToXyYD65(h, s, v)
}

// XyYToHwb is an alias for [XyYD65ToHwb]
func XyYToHwb(x, y, luminance float64) (h, w, b float64) {
	return XyYD65ToHwb(x, y, luminance)
}

// HwbToXyY is an alias for [HwbToXyYD65]
func HwbToXyY(h, w, b float64) (x, y, luminance float64) {
	return HwbToXyYD65(h, w, b)
}

// LabToSrgb is an alias for [LabD50ToSrgb]
func LabToSrgb(l, a, b float64) (float64, float64, float64) {
	return LabD50ToSrgb(l, a, b)
}

// SrgbToLab is an alias for [SrgbToLabD50]
func SrgbToLab(r, g, b float64) (float64, float64, float64) {
	return SrgbToLabD50(r, g, b)
}

// LabToLinearSrgb is an alias for [LabD50ToLinearSrgb]
func LabToLinearSrgb(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLinearSrgb(l, a, b)
}

// LinearSrgbToLab is an alias for [LinearSrgbToLabD50]
func LinearSrgbToLab(r, g, b float64) (float64, float64, float64) {
	return LinearSrgbToLabD50(r, g, b)
}

// LabToDisplayP3 is an alias for [LabD50ToDisplayP3]
func LabToDisplayP3(l, a, b float64) (float64, float64, float64) {
	return LabD50ToDisplayP3(l, a, b)
}

// DisplayP3ToLab is an alias for [DisplayP3ToLabD50]
func DisplayP3ToLab(r, g, b float64) (float64, float64, float64) {
	return DisplayP3ToLabD50(r, g, b)
}

// LabToLinearDisplayP3 is an alias for [LabD50ToLinearDisplayP3]
func LabToLinearDisplayP3(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLinearDisplayP3(l, a, b)
}

// LinearDisplayP3ToLab is an alias for [LinearDisplayP3ToLabD50]
func LinearDisplayP3ToLab(r, g, b float64) (float64, float64, float64) {
	return LinearDisplayP3ToLabD50(r, g, b)
}

// LabToA98 is an alias for [LabD50ToA98]
func LabToA98(l, a, b float64) (float64, float64, float64) {
	return LabD50ToA98(l, a, b)
}

// A98ToLab is an alias for [A98ToLabD50]
func A98ToLab(r, g, b float64) (float64, float64, float64) {
	return A98ToLabD50(r, g, b)
}

// LabToLinearA98 is an alias for [LabD50ToLinearA98]
func LabToLinearA98(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLinearA98(l, a, b)
}

// LinearA98ToLab is an alias for [LinearA98ToLabD50]
func LinearA98ToLab(r, g, b float64) (float64, float64, float64) {
	return LinearA98ToLabD50(r, g, b)
}

// LabToProPhoto is an alias for [LabD50ToProPhoto]
func LabToProPhoto(l, a, b float64) (float64, float64, float64) {
	return LabD50ToProPhoto(l, a, b)
}

// ProPhotoToLab is an alias for [ProPhotoToLabD50]
func ProPhotoToLab(r, g, b float64) (float64, float64, float64) {
	return ProPhotoToLabD50(r, g, b)
}

// LabToLinearProPhoto is an alias for [LabD50ToLinearProPhoto]
func LabToLinearProPhoto(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLinearProPhoto(l, a, b)
}

// LinearProPhotoToLab is an alias for [LinearProPhotoToLabD50]
func LinearProPhotoToLab(r, g, b float64) (float64, float64, float64) {
	return LinearProPhotoToLabD50(r, g, b)
}

// LabToRec2020 is an alias for [LabD50ToRec2020]
func LabToRec2020(l, a, b float64) (float64, float64, float64) {
	return LabD50ToRec2020(l, a, b)
}

// Rec2020ToLab is an alias for [Rec2020ToLabD50]
func Rec2020ToLab(r, g, b float64) (float64, float64, float64) {
	return Rec2020ToLabD50(r, g, b)
}

// LabToRec2020OETF is an alias for [LabD50ToRec2020OETF]
func LabToRec2020OETF(l, a, b float64) (float64, float64, float64) {
	return LabD50ToRec2020OETF(l, a, b)
}

// Rec2020OETFToLab is an alias for [Rec2020OETFToLabD50]
func Rec2020OETFToLab(r, g, b float64) (float64, float64, float64) {
	return Rec2020OETFToLabD50(r, g, b)
}

// LabToLinearRec2020 is an alias for [LabD50ToLinearRec2020]
func LabToLinearRec2020(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLinearRec2020(l, a, b)
}

// LinearRec2020ToLab is an alias for [LinearRec2020ToLabD50]
func LinearRec2020ToLab(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToLabD50(r, g, b)
}

// LabToLinearRec2100 is an alias for [LabD50ToLinearRec2100]
func LabToLinearRec2100(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLinearRec2100(l, a, b)
}

// LinearRec2100ToLab is an alias for [LinearRec2100ToLabD50]
func LinearRec2100ToLab(r, g, b float64) (float64, float64, float64) {
	return LinearRec2100ToLabD50(r, g, b)
}

// LabToRec2100PQ is an alias for [LabD50ToRec2100PQ]
func LabToRec2100PQ(l, a, b float64) (float64, float64, float64) {
	return LabD50ToRec2100PQ(l, a, b)
}

// Rec2100PQToLab is an alias for [Rec2100PQToLabD50]
func Rec2100PQToLab(r, g, b float64) (float64, float64, float64) {
	return Rec2100PQToLabD50(r, g, b)
}

// LabToRec2100HLG is an alias for [LabD50ToRec2100HLG]
func LabToRec2100HLG(l, a, b float64) (float64, float64, float64) {
	return LabD50ToRec2100HLG(l, a, b)
}

// Rec2100HLGToLab is an alias for [Rec2100HLGToLabD50]
func Rec2100HLGToLab(r, g, b float64) (float64, float64, float64) {
	return Rec2100HLGToLabD50(r, g, b)
}

// LabToXyzD50 is an alias for [LabD50ToXyzD50]
func LabToXyzD50(l, a, b float64) (x, y, z float64) {
	return LabD50ToXyzD50(l, a, b)
}

// XyzD50ToLab is an alias for [XyzD50ToLabD50]
func XyzD50ToLab(x, y, z float64) (l, a, b float64) {
	return XyzD50ToLabD50(x, y, z)
}

// LabToXyzD65 is an alias for [LabD50ToXyzD65]
func LabToXyzD65(l, a, b float64) (x, y, z float64) {
	return LabD50ToXyzD65(l, a, b)
}

// XyzD65ToLab is an alias for [XyzD65ToLabD50]
func XyzD65ToLab(x, y, z float64) (l, a, b float64) {
	return XyzD65ToLabD50(x, y, z)
}

// LabToXyzAbsD65 is an alias for [LabD50ToXyzAbsD65]
func LabToXyzAbsD65(l, a, b float64) (x, y, z float64) {
	return LabD50ToXyzAbsD65(l, a, b)
}

// XyzAbsD65ToLab is an alias for [XyzAbsD65ToLabD50]
func XyzAbsD65ToLab(x, y, z float64) (l, a, b float64) {
	return XyzAbsD65ToLabD50(x, y, z)
}

// LabToXyYD50 is an alias for [LabD50ToXyYD50]
func LabToXyYD50(l, a, b float64) (x, y, luminance float64) {
	return LabD50ToXyYD50(l, a, b)
}

// XyYD50ToLab is an alias for [XyYD50ToLabD50]
func XyYD50ToLab(x, y, luminance float64) (l, a, b float64) {
	return XyYD50ToLabD50(x, y, luminance)
}

// LabToXyYD65 is an alias for [LabD50ToXyYD65]
func LabToXyYD65(l, a, b float64) (x, y, luminance float64) {
	return LabD50ToXyYD65(l, a, b)
}

// XyYD65ToLab is an alias for [XyYD65ToLabD50]
func XyYD65ToLab(x, y, luminance float64) (l, a, b float64) {
	return XyYD65ToLabD50(x, y, luminance)
}

// LabToLchD50 is an alias for [LabD50ToLchD50]
func LabToLchD50(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLchD50(l, a, b)
}

// LchD50ToLab is an alias for [LchD50ToLabD50]
func LchD50ToLab(l, c, h float64) (float64, float64, float64) {
	return LchD50ToLabD50(l, c, h)
}

// LabToLabD65 is an alias for [LabD50ToLabD65]
func LabToLabD65(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLabD65(l, a, b)
}

// LabD65ToLab is an alias for [LabD65ToLabD50]
func LabD65ToLab(l, a, b float64) (float64, float64, float64) {
	return LabD65ToLabD50(l, a, b)
}

// LabToLchD65 is an alias for [LabD50ToLchD65]
func LabToLchD65(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLchD65(l, a, b)
}

// LchD65ToLab is an alias for [LchD65ToLabD50]
func LchD65ToLab(l, c, h float64) (float64, float64, float64) {
	return LchD65ToLabD50(l, c, h)
}

// LabToLuvD50 is an alias for [LabD50ToLuvD50]
func LabToLuvD50(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLuvD50(l, a, b)
}

// LuvD50ToLab is an alias for [LuvD50ToLabD50]
func LuvD50ToLab(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToLabD50(l, u, v)
}

// LabToLchuvD50 is an alias for [LabD50ToLchuvD50]
func LabToLchuvD50(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLchuvD50(l, a, b)
}

// LchuvD50ToLab is an alias for [LchuvD50ToLabD50]
func LchuvD50ToLab(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToLabD50(l, c, h)
}

// LabToLuvD65 is an alias for [LabD50ToLuvD65]
func LabToLuvD65(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLuvD65(l, a, b)
}

// LuvD65ToLab is an alias for [LuvD65ToLabD50]
func LuvD65ToLab(l, u, v float64) (float64, float64, float64) {
	return LuvD65ToLabD50(l, u, v)
}

// LabToLchuvD65 is an alias for [LabD50ToLchuvD65]
func LabToLchuvD65(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLchuvD65(l, a, b)
}

// LchuvD65ToLab is an alias for [LchuvD65ToLabD50]
func LchuvD65ToLab(l, c, h float64) (float64, float64, float64) {
	return LchuvD65ToLabD50(l, c, h)
}

// LabToOklab is an alias for [LabD50ToOklab]
func LabToOklab(l, a, b float64) (float64, float64, float64) {
	return LabD50ToOklab(l, a, b)
}

// OklabToLab is an alias for [OklabToLabD50]
func OklabToLab(l, a, b float64) (float64, float64, float64) {
	return OklabToLabD50(l, a, b)
}

// LabToOklch is an alias for [LabD50ToOklch]
func LabToOklch(l, a, b float64) (float64, float64, float64) {
	return LabD50ToOklch(l, a, b)
}

// OklchToLab is an alias for [OklchToLabD50]
func OklchToLab(l, c, h float64) (float64, float64, float64) {
	return OklchToLabD50(l, c, h)
}

// LabToHsl is an alias for [LabD50ToHsl]
func LabToHsl(l, a, b float64) (float64, float64, float64) {
	return LabD50ToHsl(l, a, b)
}

// HslToLab is an alias for [HslToLabD50]
func HslToLab(h, s, l float64) (float64, float64, float64) {
	return HslToLabD50(h, s, l)
}

// LabToHsv is an alias for [LabD50ToHsv]
func LabToHsv(l, a, b float64) (h, s, v float64) {
	return LabD50ToHsv(l, a, b)
}

// HsvToLab is an alias for [HsvToLabD50]
func HsvToLab(h, s, v float64) (l, a, b float64) {
	return HsvToLabD50(h, s, v)
}

// LabToHwb is an alias for [LabD50ToHwb]
func LabToHwb(l, a, b float64) (float64, float64, float64) {
	return LabD50ToHwb(l, a, b)
}

// HwbToLab is an alias for [HwbToLabD50]
func HwbToLab(h, w, b float64) (float64, float64, float64) {
	return HwbToLabD50(h, w, b)
}

// LchToSrgb is an alias for [LchD50ToSrgb]
func LchToSrgb(l, c, h float64) (r, g, b float64) {
	return LchD50ToSrgb(l, c, h)
}

// SrgbToLch is an alias for [SrgbToLchD50]
func SrgbToLch(r, g, b float64) (l, c, h float64) {
	return SrgbToLchD50(r, g, b)
}

// LchToLinearSrgb is an alias for [LchD50ToLinearSrgb]
func LchToLinearSrgb(l, c, h float64) (r, g, b float64) {
	return LchD50ToLinearSrgb(l, c, h)
}

// LinearSrgbToLch is an alias for [LinearSrgbToLchD50]
func LinearSrgbToLch(r, g, b float64) (l, c, h float64) {
	return LinearSrgbToLchD50(r, g, b)
}

// LchToDisplayP3 is an alias for [LchD50ToDisplayP3]
func LchToDisplayP3(l, c, h float64) (r, g, b float64) {
	return LchD50ToDisplayP3(l, c, h)
}

// DisplayP3ToLch is an alias for [DisplayP3ToLchD50]
func DisplayP3ToLch(r, g, b float64) (l, c, h float64) {
	return DisplayP3ToLchD50(r, g, b)
}

// LchToLinearDisplayP3 is an alias for [LchD50ToLinearDisplayP3]
func LchToLinearDisplayP3(l, c, h float64) (r, g, b float64) {
	return LchD50ToLinearDisplayP3(l, c, h)
}

// LinearDisplayP3ToLch is an alias for [LinearDisplayP3ToLchD50]
func LinearDisplayP3ToLch(r, g, b float64) (l, c, h float64) {
	return LinearDisplayP3ToLchD50(r, g, b)
}

// LchToA98 is an alias for [LchD50ToA98]
func LchToA98(l, c, h float64) (r, g, b float64) {
	return LchD50ToA98(l, c, h)
}

// A98ToLch is an alias for [A98ToLchD50]
func A98ToLch(r, g, b float64) (l, c, h float64) {
	return A98ToLchD50(r, g, b)
}

// LchToLinearA98 is an alias for [LchD50ToLinearA98]
func LchToLinearA98(l, c, h float64) (r, g, b float64) {
	return LchD50ToLinearA98(l, c, h)
}

// LinearA98ToLch is an alias for [LinearA98ToLchD50]
func LinearA98ToLch(r, g, b float64) (l, c, h float64) {
	return LinearA98ToLchD50(r, g, b)
}

// LchToProPhoto is an alias for [LchD50ToProPhoto]
func LchToProPhoto(l, c, h float64) (r, g, b float64) {
	return LchD50ToProPhoto(l, c, h)
}

// ProPhotoToLch is an alias for [ProPhotoToLchD50]
func ProPhotoToLch(r, g, b float64) (l, c, h float64) {
	return ProPhotoToLchD50(r, g, b)
}

// LchToLinearProPhoto is an alias for [LchD50ToLinearProPhoto]
func LchToLinearProPhoto(l, c, h float64) (r, g, b float64) {
	return LchD50ToLinearProPhoto(l, c, h)
}

// LinearProPhotoToLch is an alias for [LinearProPhotoToLchD50]
func LinearProPhotoToLch(r, g, b float64) (l, c, h float64) {
	return LinearProPhotoToLchD50(r, g, b)
}

// LchToRec2020 is an alias for [LchD50ToRec2020]
func LchToRec2020(l, c, h float64) (r, g, b float64) {
	return LchD50ToRec2020(l, c, h)
}

// Rec2020ToLch is an alias for [Rec2020ToLchD50]
func Rec2020ToLch(r, g, b float64) (l, c, h float64) {
	return Rec2020ToLchD50(r, g, b)
}

// LchToRec2020OETF is an alias for [LchD50ToRec2020OETF]
func LchToRec2020OETF(l, c, h float64) (r, g, b float64) {
	return LchD50ToRec2020OETF(l, c, h)
}

// Rec2020OETFToLch is an alias for [Rec2020OETFToLchD50]
func Rec2020OETFToLch(r, g, b float64) (l, c, h float64) {
	return Rec2020OETFToLchD50(r, g, b)
}

// LchToLinearRec2020 is an alias for [LchD50ToLinearRec2020]
func LchToLinearRec2020(l, c, h float64) (r, g, b float64) {
	return LchD50ToLinearRec2020(l, c, h)
}

// LinearRec2020ToLch is an alias for [LinearRec2020ToLchD50]
func LinearRec2020ToLch(r, g, b float64) (l, c, h float64) {
	return LinearRec2020ToLchD50(r, g, b)
}

// LchToLinearRec2100 is an alias for [LchD50ToLinearRec2100]
func LchToLinearRec2100(l, c, h float64) (r, g, b float64) {
	return LchD50ToLinearRec2100(l, c, h)
}

// LinearRec2100ToLch is an alias for [LinearRec2100ToLchD50]
func LinearRec2100ToLch(r, g, b float64) (l, c, h float64) {
	return LinearRec2100ToLchD50(r, g, b)
}

// LchToRec2100PQ is an alias for [LchD50ToRec2100PQ]
func LchToRec2100PQ(l, c, h float64) (r, g, b float64) {
	return LchD50ToRec2100PQ(l, c, h)
}

// Rec2100PQToLch is an alias for [Rec2100PQToLchD50]
func Rec2100PQToLch(r, g, b float64) (l, c, h float64) {
	return Rec2100PQToLchD50(r, g, b)
}

// LchToRec2100HLG is an alias for [LchD50ToRec2100HLG]
func LchToRec2100HLG(l, c, h float64) (r, g, b float64) {
	return LchD50ToRec2100HLG(l, c, h)
}

// Rec2100HLGToLch is an alias for [Rec2100HLGToLchD50]
func Rec2100HLGToLch(r, g, b float64) (l, c, h float64) {
	return Rec2100HLGToLchD50(r, g, b)
}

// LchToXyzD50 is an alias for [LchD50ToXyzD50]
func LchToXyzD50(l, c, h float64) (x, y, z float64) {
	return LchD50ToXyzD50(l, c, h)
}

// XyzD50ToLch is an alias for [XyzD50ToLchD50]
func XyzD50ToLch(x, y, z float64) (l, c, h float64) {
	return XyzD50ToLchD50(x, y, z)
}

// LchToXyzD65 is an alias for [LchD50ToXyzD65]
func LchToXyzD65(l, c, h float64) (x, y, z float64) {
	return LchD50ToXyzD65(l, c, h)
}

// XyzD65ToLch is an alias for [XyzD65ToLchD50]
func XyzD65ToLch(x, y, z float64) (l, c, h float64) {
	return XyzD65ToLchD50(x, y, z)
}

// LchToXyzAbsD65 is an alias for [LchD50ToXyzAbsD65]
func LchToXyzAbsD65(l, c, h float64) (x, y, z float64) {
	return LchD50ToXyzAbsD65(l, c, h)
}

// XyzAbsD65ToLch is an alias for [XyzAbsD65ToLchD50]
func XyzAbsD65ToLch(x, y, z float64) (l, c, h float64) {
	return XyzAbsD65ToLchD50(x, y, z)
}

// LchToXyYD50 is an alias for [LchD50ToXyYD50]
func LchToXyYD50(l, c, h float64) (x, y, luminance float64) {
	return LchD50ToXyYD50(l, c, h)
}

// XyYD50ToLch is an alias for [XyYD50ToLchD50]
func XyYD50ToLch(x, y, luminance float64) (l, c, h float64) {
	return XyYD50ToLchD50(x, y, luminance)
}

// LchToXyYD65 is an alias for [LchD50ToXyYD65]
func LchToXyYD65(l, c, h float64) (x, y, luminance float64) {
	return LchD50ToXyYD65(l, c, h)
}

// XyYD65ToLch is an alias for [XyYD65ToLchD50]
func XyYD65ToLch(x, y, luminance float64) (l, c, h float64) {
	return XyYD65ToLchD50(x, y, luminance)
}

// LchToLabD50 is an alias for [LchD50ToLabD50]
func LchToLabD50(l, c, h float64) (float64, float64, float64) {
	return LchD50ToLabD50(l, c, h)
}

// LabD50ToLch is an alias for [LabD50ToLchD50]
func LabD50ToLch(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLchD50(l, a, b)
}

// LchToLabD65 is an alias for [LchD50ToLabD65]
func LchToLabD65(l, c, h float64) (float64, float64, float64) {
	return LchD50ToLabD65(l, c, h)
}

// LabD65ToLch is an alias for [LabD65ToLchD50]
func LabD65ToLch(l, a, b float64) (float64, float64, float64) {
	return LabD65ToLchD50(l, a, b)
}

// LchToLchD65 is an alias for [LchD50ToLchD65]
func LchToLchD65(l, c, h float64) (float64, float64, float64) {
	return LchD50ToLchD65(l, c, h)
}

// LchD65ToLch is an alias for [LchD65ToLchD50]
func LchD65ToLch(l, c, h float64) (float64, float64, float64) {
	return LchD65ToLchD50(l, c, h)
}

// LchToLuvD50 is an alias for [LchD50ToLuvD50]
func LchToLuvD50(l, c, h float64) (float64, float64, float64) {
	return LchD50ToLuvD50(l, c, h)
}

// LuvD50ToLch is an alias for [LuvD50ToLchD50]
func LuvD50ToLch(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToLchD50(l, u, v)
}

// LchToLchuvD50 is an alias for [LchD50ToLchuvD50]
func LchToLchuvD50(l, c, h float64) (float64, float64, float64) {
	return LchD50ToLchuvD50(l, c, h)
}

// LchuvD50ToLch is an alias for [LchuvD50ToLchD50]
func LchuvD50ToLch(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToLchD50(l, c, h)
}

// LchToLuvD65 is an alias for [LchD50ToLuvD65]
func LchToLuvD65(l, c, h float64) (float64, float64, float64) {
	return LchD50ToLuvD65(l, c, h)
}

// LuvD65ToLch is an alias for [LuvD65ToLchD50]
func LuvD65ToLch(l, u, v float64) (float64, float64, float64) {
	return LuvD65ToLchD50(l, u, v)
}

// LchToLchuvD65 is an alias for [LchD50ToLchuvD65]
func LchToLchuvD65(l, c, h float64) (float64, float64, float64) {
	return LchD50ToLchuvD65(l, c, h)
}

// LchuvD65ToLch is an alias for [LchuvD65ToLchD50]
func LchuvD65ToLch(l, c, h float64) (float64, float64, float64) {
	return LchuvD65ToLchD50(l, c, h)
}

// LchToOklab is an alias for [LchD50ToOklab]
func LchToOklab(l, c, h float64) (float64, float64, float64) {
	return LchD50ToOklab(l, c, h)
}

// OklabToLch is an alias for [OklabToLchD50]
func OklabToLch(l, a, b float64) (float64, float64, float64) {
	return OklabToLchD50(l, a, b)
}

// LchToOklch is an alias for [LchD50ToOklch]
func LchToOklch(l, c, h float64) (float64, float64, float64) {
	return LchD50ToOklch(l, c, h)
}

// OklchToLch is an alias for [OklchToLchD50]
func OklchToLch(l, c, h float64) (float64, float64, float64) {
	return OklchToLchD50(l, c, h)
}

// LchToHsl is an alias for [LchD50ToHsl]
func LchToHsl(l, c, h float64) (float64, float64, float64) {
	return LchD50ToHsl(l, c, h)
}

// HslToLch is an alias for [HslToLchD50]
func HslToLch(h, s, l float64) (float64, float64, float64) {
	return HslToLchD50(h, s, l)
}

// LchToHsv is an alias for [LchD50ToHsv]
func LchToHsv(l, c, h float64) (float64, float64, float64) {
	return LchD50ToHsv(l, c, h)
}

// HsvToLch is an alias for [HsvToLchD50]
func HsvToLch(h, s, v float64) (float64, float64, float64) {
	return HsvToLchD50(h, s, v)
}

// LchToHwb is an alias for [LchD50ToHwb]
func LchToHwb(l, c, h float64) (float64, float64, float64) {
	return LchD50ToHwb(l, c, h)
}

// HwbToLch is an alias for [HwbToLchD50]
func HwbToLch(h, w, b float64) (float64, float64, float64) {
	return HwbToLchD50(h, w, b)
}

// LuvToSrgb is an alias for [LuvD50ToSrgb]
func LuvToSrgb(l, u, v float64) (r, g, b float64) {
	return LuvD50ToSrgb(l, u, v)
}

// SrgbToLuv is an alias for [SrgbToLuvD50]
func SrgbToLuv(r, g, b float64) (l, u, v float64) {
	return SrgbToLuvD50(r, g, b)
}

// LuvToLinearSrgb is an alias for [LuvD50ToLinearSrgb]
func LuvToLinearSrgb(l, u, v float64) (r, g, b float64) {
	return LuvD50ToLinearSrgb(l, u, v)
}

// LinearSrgbToLuv is an alias for [LinearSrgbToLuvD50]
func LinearSrgbToLuv(r, g, b float64) (l, u, v float64) {
	return LinearSrgbToLuvD50(r, g, b)
}

// LuvToDisplayP3 is an alias for [LuvD50ToDisplayP3]
func LuvToDisplayP3(l, u, v float64) (r, g, b float64) {
	return LuvD50ToDisplayP3(l, u, v)
}

// DisplayP3ToLuv is an alias for [DisplayP3ToLuvD50]
func DisplayP3ToLuv(r, g, b float64) (l, u, v float64) {
	return DisplayP3ToLuvD50(r, g, b)
}

// LuvToLinearDisplayP3 is an alias for [LuvD50ToLinearDisplayP3]
func LuvToLinearDisplayP3(l, u, v float64) (r, g, b float64) {
	return LuvD50ToLinearDisplayP3(l, u, v)
}

// LinearDisplayP3ToLuv is an alias for [LinearDisplayP3ToLuvD50]
func LinearDisplayP3ToLuv(r, g, b float64) (l, u, v float64) {
	return LinearDisplayP3ToLuvD50(r, g, b)
}

// LuvToA98 is an alias for [LuvD50ToA98]
func LuvToA98(l, u, v float64) (r, g, b float64) {
	return LuvD50ToA98(l, u, v)
}

// A98ToLuv is an alias for [A98ToLuvD50]
func A98ToLuv(r, g, b float64) (l, u, v float64) {
	return A98ToLuvD50(r, g, b)
}

// LuvToLinearA98 is an alias for [LuvD50ToLinearA98]
func LuvToLinearA98(l, u, v float64) (r, g, b float64) {
	return LuvD50ToLinearA98(l, u, v)
}

// LinearA98ToLuv is an alias for [LinearA98ToLuvD50]
func LinearA98ToLuv(r, g, b float64) (l, u, v float64) {
	return LinearA98ToLuvD50(r, g, b)
}

// LuvToProPhoto is an alias for [LuvD50ToProPhoto]
func LuvToProPhoto(l, u, v float64) (r, g, b float64) {
	return LuvD50ToProPhoto(l, u, v)
}

// ProPhotoToLuv is an alias for [ProPhotoToLuvD50]
func ProPhotoToLuv(r, g, b float64) (l, u, v float64) {
	return ProPhotoToLuvD50(r, g, b)
}

// LuvToLinearProPhoto is an alias for [LuvD50ToLinearProPhoto]
func LuvToLinearProPhoto(l, u, v float64) (r, g, b float64) {
	return LuvD50ToLinearProPhoto(l, u, v)
}

// LinearProPhotoToLuv is an alias for [LinearProPhotoToLuvD50]
func LinearProPhotoToLuv(r, g, b float64) (l, u, v float64) {
	return LinearProPhotoToLuvD50(r, g, b)
}

// LuvToRec2020 is an alias for [LuvD50ToRec2020]
func LuvToRec2020(l, u, v float64) (r, g, b float64) {
	return LuvD50ToRec2020(l, u, v)
}

// Rec2020ToLuv is an alias for [Rec2020ToLuvD50]
func Rec2020ToLuv(r, g, b float64) (l, u, v float64) {
	return Rec2020ToLuvD50(r, g, b)
}

// LuvToRec2020OETF is an alias for [LuvD50ToRec2020OETF]
func LuvToRec2020OETF(l, u, v float64) (r, g, b float64) {
	return LuvD50ToRec2020OETF(l, u, v)
}

// Rec2020OETFToLuv is an alias for [Rec2020OETFToLuvD50]
func Rec2020OETFToLuv(r, g, b float64) (l, u, v float64) {
	return Rec2020OETFToLuvD50(r, g, b)
}

// LuvToLinearRec2020 is an alias for [LuvD50ToLinearRec2020]
func LuvToLinearRec2020(l, u, v float64) (r, g, b float64) {
	return LuvD50ToLinearRec2020(l, u, v)
}

// LinearRec2020ToLuv is an alias for [LinearRec2020ToLuvD50]
func LinearRec2020ToLuv(r, g, b float64) (l, u, v float64) {
	return LinearRec2020ToLuvD50(r, g, b)
}

// LuvToLinearRec2100 is an alias for [LuvD50ToLinearRec2100]
func LuvToLinearRec2100(l, u, v float64) (r, g, b float64) {
	return LuvD50ToLinearRec2100(l, u, v)
}

// LinearRec2100ToLuv is an alias for [LinearRec2100ToLuvD50]
func LinearRec2100ToLuv(r, g, b float64) (l, u, v float64) {
	return LinearRec2100ToLuvD50(r, g, b)
}

// LuvToRec2100PQ is an alias for [LuvD50ToRec2100PQ]
func LuvToRec2100PQ(l, u, v float64) (r, g, b float64) {
	return LuvD50ToRec2100PQ(l, u, v)
}

// Rec2100PQToLuv is an alias for [Rec2100PQToLuvD50]
func Rec2100PQToLuv(r, g, b float64) (l, u, v float64) {
	return Rec2100PQToLuvD50(r, g, b)
}

// LuvToRec2100HLG is an alias for [LuvD50ToRec2100HLG]
func LuvToRec2100HLG(l, u, v float64) (r, g, b float64) {
	return LuvD50ToRec2100HLG(l, u, v)
}

// Rec2100HLGToLuv is an alias for [Rec2100HLGToLuvD50]
func Rec2100HLGToLuv(r, g, b float64) (l, u, v float64) {
	return Rec2100HLGToLuvD50(r, g, b)
}

// LuvToXyzD50 is an alias for [LuvD50ToXyzD50]
func LuvToXyzD50(l, u, v float64) (x, y, z float64) {
	return LuvD50ToXyzD50(l, u, v)
}

// XyzD50ToLuv is an alias for [XyzD50ToLuvD50]
func XyzD50ToLuv(x, y, z float64) (l, u, v float64) {
	return XyzD50ToLuvD50(x, y, z)
}

// LuvToXyzD65 is an alias for [LuvD50ToXyzD65]
func LuvToXyzD65(l, u, v float64) (x, y, z float64) {
	return LuvD50ToXyzD65(l, u, v)
}

// XyzD65ToLuv is an alias for [XyzD65ToLuvD50]
func XyzD65ToLuv(x, y, z float64) (l, u, v float64) {
	return XyzD65ToLuvD50(x, y, z)
}

// LuvToXyzAbsD65 is an alias for [LuvD50ToXyzAbsD65]
func LuvToXyzAbsD65(l, u, v float64) (x, y, z float64) {
	return LuvD50ToXyzAbsD65(l, u, v)
}

// XyzAbsD65ToLuv is an alias for [XyzAbsD65ToLuvD50]
func XyzAbsD65ToLuv(x, y, z float64) (l, u, v float64) {
	return XyzAbsD65ToLuvD50(x, y, z)
}

// LuvToXyYD50 is an alias for [LuvD50ToXyYD50]
func LuvToXyYD50(l, u, v float64) (x, y, luminance float64) {
	return LuvD50ToXyYD50(l, u, v)
}

// XyYD50ToLuv is an alias for [XyYD50ToLuvD50]
func XyYD50ToLuv(x, y, luminance float64) (l, u, v float64) {
	return XyYD50ToLuvD50(x, y, luminance)
}

// LuvToXyYD65 is an alias for [LuvD50ToXyYD65]
func LuvToXyYD65(l, u, v float64) (x, y, luminance float64) {
	return LuvD50ToXyYD65(l, u, v)
}

// XyYD65ToLuv is an alias for [XyYD65ToLuvD50]
func XyYD65ToLuv(x, y, luminance float64) (l, u, v float64) {
	return XyYD65ToLuvD50(x, y, luminance)
}

// LuvToLabD50 is an alias for [LuvD50ToLabD50]
func LuvToLabD50(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToLabD50(l, u, v)
}

// LabD50ToLuv is an alias for [LabD50ToLuvD50]
func LabD50ToLuv(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLuvD50(l, a, b)
}

// LuvToLchD50 is an alias for [LuvD50ToLchD50]
func LuvToLchD50(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToLchD50(l, u, v)
}

// LchD50ToLuv is an alias for [LchD50ToLuvD50]
func LchD50ToLuv(l, c, h float64) (float64, float64, float64) {
	return LchD50ToLuvD50(l, c, h)
}

// LuvToLabD65 is an alias for [LuvD50ToLabD65]
func LuvToLabD65(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToLabD65(l, u, v)
}

// LabD65ToLuv is an alias for [LabD65ToLuvD50]
func LabD65ToLuv(l, a, b float64) (float64, float64, float64) {
	return LabD65ToLuvD50(l, a, b)
}

// LuvToLchD65 is an alias for [LuvD50ToLchD65]
func LuvToLchD65(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToLchD65(l, u, v)
}

// LchD65ToLuv is an alias for [LchD65ToLuvD50]
func LchD65ToLuv(l, c, h float64) (float64, float64, float64) {
	return LchD65ToLuvD50(l, c, h)
}

// LuvToLchuvD50 is an alias for [LuvD50ToLchuvD50]
func LuvToLchuvD50(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToLchuvD50(l, u, v)
}

// LchuvD50ToLuv is an alias for [LchuvD50ToLuvD50]
func LchuvD50ToLuv(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToLuvD50(l, c, h)
}

// LuvToLuvD65 is an alias for [LuvD50ToLuvD65]
func LuvToLuvD65(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToLuvD65(l, u, v)
}

// LuvD65ToLuv is an alias for [LuvD65ToLuvD50]
func LuvD65ToLuv(l, u, v float64) (float64, float64, float64) {
	return LuvD65ToLuvD50(l, u, v)
}

// LuvToLchuvD65 is an alias for [LuvD50ToLchuvD65]
func LuvToLchuvD65(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToLchuvD65(l, u, v)
}

// LchuvD65ToLuv is an alias for [LchuvD65ToLuvD50]
func LchuvD65ToLuv(l, c, h float64) (float64, float64, float64) {
	return LchuvD65ToLuvD50(l, c, h)
}

// LuvToOklab is an alias for [LuvD50ToOklab]
func LuvToOklab(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToOklab(l, u, v)
}

// OklabToLuv is an alias for [OklabToLuvD50]
func OklabToLuv(l, a, b float64) (float64, float64, float64) {
	return OklabToLuvD50(l, a, b)
}

// LuvToOklch is an alias for [LuvD50ToOklch]
func LuvToOklch(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToOklch(l, u, v)
}

// OklchToLuv is an alias for [OklchToLuvD50]
func OklchToLuv(l, c, h float64) (float64, float64, float64) {
	return OklchToLuvD50(l, c, h)
}

// LuvToHsl is an alias for [LuvD50ToHsl]
func LuvToHsl(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToHsl(l, u, v)
}

// HslToLuv is an alias for [HslToLuvD50]
func HslToLuv(h, s, l float64) (float64, float64, float64) {
	return HslToLuvD50(h, s, l)
}

// LuvToHsv is an alias for [LuvD50ToHsv]
func LuvToHsv(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToHsv(l, u, v)
}

// HsvToLuv is an alias for [HsvToLuvD50]
func HsvToLuv(h, s, v float64) (float64, float64, float64) {
	return HsvToLuvD50(h, s, v)
}

// LuvToHwb is an alias for [LuvD50ToHwb]
func LuvToHwb(l, u, v float64) (h, w, b float64) {
	return LuvD50ToHwb(l, u, v)
}

// HwbToLuv is an alias for [HwbToLuvD50]
func HwbToLuv(h, w, b float64) (l, u, v float64) {
	return HwbToLuvD50(h, w, b)
}

// LchuvToSrgb is an alias for [LchuvD50ToSrgb]
func LchuvToSrgb(l, c, h float64) (r, g, b float64) {
	return LchuvD50ToSrgb(l, c, h)
}

// SrgbToLchuv is an alias for [SrgbToLchuvD50]
func SrgbToLchuv(r, g, b float64) (l, c, h float64) {
	return SrgbToLchuvD50(r, g, b)
}

// LchuvToLinearSrgb is an alias for [LchuvD50ToLinearSrgb]
func LchuvToLinearSrgb(l, c, h float64) (r, g, b float64) {
	return LchuvD50ToLinearSrgb(l, c, h)
}

// LinearSrgbToLchuv is an alias for [LinearSrgbToLchuvD50]
func LinearSrgbToLchuv(r, g, b float64) (l, c, h float64) {
	return LinearSrgbToLchuvD50(r, g, b)
}

// LchuvToDisplayP3 is an alias for [LchuvD50ToDisplayP3]
func LchuvToDisplayP3(l, c, h float64) (r, g, b float64) {
	return LchuvD50ToDisplayP3(l, c, h)
}

// DisplayP3ToLchuv is an alias for [DisplayP3ToLchuvD50]
func DisplayP3ToLchuv(r, g, b float64) (l, c, h float64) {
	return DisplayP3ToLchuvD50(r, g, b)
}

// LchuvToLinearDisplayP3 is an alias for [LchuvD50ToLinearDisplayP3]
func LchuvToLinearDisplayP3(l, c, h float64) (r, g, b float64) {
	return LchuvD50ToLinearDisplayP3(l, c, h)
}

// LinearDisplayP3ToLchuv is an alias for [LinearDisplayP3ToLchuvD50]
func LinearDisplayP3ToLchuv(r, g, b float64) (l, c, h float64) {
	return LinearDisplayP3ToLchuvD50(r, g, b)
}

// LchuvToA98 is an alias for [LchuvD50ToA98]
func LchuvToA98(l, c, h float64) (r, g, b float64) {
	return LchuvD50ToA98(l, c, h)
}

// A98ToLchuv is an alias for [A98ToLchuvD50]
func A98ToLchuv(r, g, b float64) (l, c, h float64) {
	return A98ToLchuvD50(r, g, b)
}

// LchuvToLinearA98 is an alias for [LchuvD50ToLinearA98]
func LchuvToLinearA98(l, c, h float64) (r, g, b float64) {
	return LchuvD50ToLinearA98(l, c, h)
}

// LinearA98ToLchuv is an alias for [LinearA98ToLchuvD50]
func LinearA98ToLchuv(r, g, b float64) (l, c, h float64) {
	return LinearA98ToLchuvD50(r, g, b)
}

// LchuvToProPhoto is an alias for [LchuvD50ToProPhoto]
func LchuvToProPhoto(l, c, h float64) (r, g, b float64) {
	return LchuvD50ToProPhoto(l, c, h)
}

// ProPhotoToLchuv is an alias for [ProPhotoToLchuvD50]
func ProPhotoToLchuv(r, g, b float64) (l, c, h float64) {
	return ProPhotoToLchuvD50(r, g, b)
}

// LchuvToLinearProPhoto is an alias for [LchuvD50ToLinearProPhoto]
func LchuvToLinearProPhoto(l, c, h float64) (r, g, b float64) {
	return LchuvD50ToLinearProPhoto(l, c, h)
}

// LinearProPhotoToLchuv is an alias for [LinearProPhotoToLchuvD50]
func LinearProPhotoToLchuv(r, g, b float64) (l, c, h float64) {
	return LinearProPhotoToLchuvD50(r, g, b)
}

// LchuvToRec2020 is an alias for [LchuvD50ToRec2020]
func LchuvToRec2020(l, c, h float64) (r, g, b float64) {
	return LchuvD50ToRec2020(l, c, h)
}

// Rec2020ToLchuv is an alias for [Rec2020ToLchuvD50]
func Rec2020ToLchuv(r, g, b float64) (l, c, h float64) {
	return Rec2020ToLchuvD50(r, g, b)
}

// LchuvToRec2020OETF is an alias for [LchuvD50ToRec2020OETF]
func LchuvToRec2020OETF(l, c, h float64) (r, g, b float64) {
	return LchuvD50ToRec2020OETF(l, c, h)
}

// Rec2020OETFToLchuv is an alias for [Rec2020OETFToLchuvD50]
func Rec2020OETFToLchuv(r, g, b float64) (l, c, h float64) {
	return Rec2020OETFToLchuvD50(r, g, b)
}

// LchuvToLinearRec2020 is an alias for [LchuvD50ToLinearRec2020]
func LchuvToLinearRec2020(l, c, h float64) (r, g, b float64) {
	return LchuvD50ToLinearRec2020(l, c, h)
}

// LinearRec2020ToLchuv is an alias for [LinearRec2020ToLchuvD50]
func LinearRec2020ToLchuv(r, g, b float64) (l, c, h float64) {
	return LinearRec2020ToLchuvD50(r, g, b)
}

// LchuvToLinearRec2100 is an alias for [LchuvD50ToLinearRec2100]
func LchuvToLinearRec2100(l, c, h float64) (r, g, b float64) {
	return LchuvD50ToLinearRec2100(l, c, h)
}

// LinearRec2100ToLchuv is an alias for [LinearRec2100ToLchuvD50]
func LinearRec2100ToLchuv(r, g, b float64) (l, c, h float64) {
	return LinearRec2100ToLchuvD50(r, g, b)
}

// LchuvToRec2100PQ is an alias for [LchuvD50ToRec2100PQ]
func LchuvToRec2100PQ(l, c, h float64) (r, g, b float64) {
	return LchuvD50ToRec2100PQ(l, c, h)
}

// Rec2100PQToLchuv is an alias for [Rec2100PQToLchuvD50]
func Rec2100PQToLchuv(r, g, b float64) (l, c, h float64) {
	return Rec2100PQToLchuvD50(r, g, b)
}

// LchuvToRec2100HLG is an alias for [LchuvD50ToRec2100HLG]
func LchuvToRec2100HLG(l, c, h float64) (r, g, b float64) {
	return LchuvD50ToRec2100HLG(l, c, h)
}

// Rec2100HLGToLchuv is an alias for [Rec2100HLGToLchuvD50]
func Rec2100HLGToLchuv(r, g, b float64) (l, c, h float64) {
	return Rec2100HLGToLchuvD50(r, g, b)
}

// LchuvToXyzD50 is an alias for [LchuvD50ToXyzD50]
func LchuvToXyzD50(l, c, h float64) (x, y, z float64) {
	return LchuvD50ToXyzD50(l, c, h)
}

// XyzD50ToLchuv is an alias for [XyzD50ToLchuvD50]
func XyzD50ToLchuv(x, y, z float64) (l, c, h float64) {
	return XyzD50ToLchuvD50(x, y, z)
}

// LchuvToXyzD65 is an alias for [LchuvD50ToXyzD65]
func LchuvToXyzD65(l, c, h float64) (x, y, z float64) {
	return LchuvD50ToXyzD65(l, c, h)
}

// XyzD65ToLchuv is an alias for [XyzD65ToLchuvD50]
func XyzD65ToLchuv(x, y, z float64) (l, c, h float64) {
	return XyzD65ToLchuvD50(x, y, z)
}

// LchuvToXyzAbsD65 is an alias for [LchuvD50ToXyzAbsD65]
func LchuvToXyzAbsD65(l, c, h float64) (x, y, z float64) {
	return LchuvD50ToXyzAbsD65(l, c, h)
}

// XyzAbsD65ToLchuv is an alias for [XyzAbsD65ToLchuvD50]
func XyzAbsD65ToLchuv(x, y, z float64) (l, c, h float64) {
	return XyzAbsD65ToLchuvD50(x, y, z)
}

// LchuvToXyYD50 is an alias for [LchuvD50ToXyYD50]
func LchuvToXyYD50(l, c, h float64) (x, y, luminance float64) {
	return LchuvD50ToXyYD50(l, c, h)
}

// XyYD50ToLchuv is an alias for [XyYD50ToLchuvD50]
func XyYD50ToLchuv(x, y, luminance float64) (l, c, h float64) {
	return XyYD50ToLchuvD50(x, y, luminance)
}

// LchuvToXyYD65 is an alias for [LchuvD50ToXyYD65]
func LchuvToXyYD65(l, c, h float64) (x, y, luminance float64) {
	return LchuvD50ToXyYD65(l, c, h)
}

// XyYD65ToLchuv is an alias for [XyYD65ToLchuvD50]
func XyYD65ToLchuv(x, y, luminance float64) (l, c, h float64) {
	return XyYD65ToLchuvD50(x, y, luminance)
}

// LchuvToLabD50 is an alias for [LchuvD50ToLabD50]
func LchuvToLabD50(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToLabD50(l, c, h)
}

// LabD50ToLchuv is an alias for [LabD50ToLchuvD50]
func LabD50ToLchuv(l, a, b float64) (float64, float64, float64) {
	return LabD50ToLchuvD50(l, a, b)
}

// LchuvToLchD50 is an alias for [LchuvD50ToLchD50]
func LchuvToLchD50(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToLchD50(l, c, h)
}

// LchD50ToLchuv is an alias for [LchD50ToLchuvD50]
func LchD50ToLchuv(l, c, h float64) (float64, float64, float64) {
	return LchD50ToLchuvD50(l, c, h)
}

// LchuvToLabD65 is an alias for [LchuvD50ToLabD65]
func LchuvToLabD65(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToLabD65(l, c, h)
}

// LabD65ToLchuv is an alias for [LabD65ToLchuvD50]
func LabD65ToLchuv(l, a, b float64) (float64, float64, float64) {
	return LabD65ToLchuvD50(l, a, b)
}

// LchuvToLchD65 is an alias for [LchuvD50ToLchD65]
func LchuvToLchD65(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToLchD65(l, c, h)
}

// LchD65ToLchuv is an alias for [LchD65ToLchuvD50]
func LchD65ToLchuv(l, c, h float64) (float64, float64, float64) {
	return LchD65ToLchuvD50(l, c, h)
}

// LchuvToLuvD50 is an alias for [LchuvD50ToLuvD50]
func LchuvToLuvD50(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToLuvD50(l, c, h)
}

// LuvD50ToLchuv is an alias for [LuvD50ToLchuvD50]
func LuvD50ToLchuv(l, u, v float64) (float64, float64, float64) {
	return LuvD50ToLchuvD50(l, u, v)
}

// LchuvToLuvD65 is an alias for [LchuvD50ToLuvD65]
func LchuvToLuvD65(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToLuvD65(l, c, h)
}

// LuvD65ToLchuv is an alias for [LuvD65ToLchuvD50]
func LuvD65ToLchuv(l, u, v float64) (float64, float64, float64) {
	return LuvD65ToLchuvD50(l, u, v)
}

// LchuvToLchuvD65 is an alias for [LchuvD50ToLchuvD65]
func LchuvToLchuvD65(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToLchuvD65(l, c, h)
}

// LchuvD65ToLchuv is an alias for [LchuvD65ToLchuvD50]
func LchuvD65ToLchuv(l, c, h float64) (float64, float64, float64) {
	return LchuvD65ToLchuvD50(l, c, h)
}

// LchuvToOklab is an alias for [LchuvD50ToOklab]
func LchuvToOklab(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToOklab(l, c, h)
}

// OklabToLchuv is an alias for [OklabToLchuvD50]
func OklabToLchuv(l, a, b float64) (float64, float64, float64) {
	return OklabToLchuvD50(l, a, b)
}

// LchuvToOklch is an alias for [LchuvD50ToOklch]
func LchuvToOklch(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToOklch(l, c, h)
}

// OklchToLchuv is an alias for [OklchToLchuvD50]
func OklchToLchuv(l, c, h float64) (float64, float64, float64) {
	return OklchToLchuvD50(l, c, h)
}

// LchuvToHsl is an alias for [LchuvD50ToHsl]
func LchuvToHsl(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToHsl(l, c, h)
}

// HslToLchuv is an alias for [HslToLchuvD50]
func HslToLchuv(h, s, l float64) (float64, float64, float64) {
	return HslToLchuvD50(h, s, l)
}

// LchuvToHsv is an alias for [LchuvD50ToHsv]
func LchuvToHsv(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToHsv(l, c, h)
}

// HsvToLchuv is an alias for [HsvToLchuvD50]
func HsvToLchuv(h, s, v float64) (float64, float64, float64) {
	return HsvToLchuvD50(h, s, v)
}

// LchuvToHwb is an alias for [LchuvD50ToHwb]
func LchuvToHwb(l, c, h float64) (float64, float64, float64) {
	return LchuvD50ToHwb(l, c, h)
}

// HwbToLchuv is an alias for [HwbToLchuvD50]
func HwbToLchuv(h, w, b float64) (float64, float64, float64) {
	return HwbToLchuvD50(h, w, b)
}
