// Code generated by running "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package convert

import (
	"math"
)

// Conversion path (3 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> Linear sRGB
func DisplayP3ToLinearSrgb(r, g, b float64) (float64, float64, float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 1.22494017628056*r - 0.22494017628056012*g
	f2 := -0.04205695470968811*r + 1.042056954709688*g
	f3 := -0.019637554590334446*r - 0.07863604555063179*g + 1.0982736001409663*b

	return f1, f2, f3
}

// Conversion path (4 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
func DisplayP3ToSrgb(r, g, b float64) (float64, float64, float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 1.22494017628056*r - 0.22494017628056012*g
	f2 := -0.04205695470968811*r + 1.042056954709688*g
	f3 := -0.019637554590334446*r - 0.07863604555063179*g + 1.0982736001409663*b

	return LinearSrgbToSrgb(f1, f2, f3)
}

// Conversion path (3 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> Linear Adobe RGB (1998)
func DisplayP3ToLinearA98(r, g, b float64) (float64, float64, float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 0.8640051374740486*r + 0.13599486252595194*g
	f2 := -0.04205695470968806*r + 1.0420569547096883*g
	f3 := -0.02056038078232987*r - 0.03250613804550801*g + 1.0530665188278385*b

	return f1, f2, f3
}

// Conversion path (4 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> Linear Adobe RGB (1998)
//	-> Adobe RGB (1998)
func DisplayP3ToA98(r, g, b float64) (float64, float64, float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 0.8640051374740486*r + 0.13599486252595194*g
	f2 := -0.04205695470968806*r + 1.0420569547096883*g
	f3 := -0.02056038078232987*r - 0.03250613804550801*g + 1.0530665188278385*b

	return LinearA98ToA98(f1, f2, f3)
}

// Conversion path (4 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> Linear ProPhoto
func DisplayP3ToLinearProPhoto(r, g, b float64) (float64, float64, float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 0.6316912201865842*r + 0.2139281848429237*g + 0.154380594970492*b
	f2 := 0.08320431685860853*r + 0.8858575096463889*g + 0.03093817349500224*b
	f3 := -0.0012727345647388431*r + 0.050755104336657406*g + 0.9505176302280817*b

	return f1, f2, f3
}

// Conversion path (5 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> Linear ProPhoto
//	-> ProPhoto
func DisplayP3ToProPhoto(r, g, b float64) (float64, float64, float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 0.6316912201865842*r + 0.2139281848429237*g + 0.154380594970492*b
	f2 := 0.08320431685860853*r + 0.8858575096463889*g + 0.03093817349500224*b
	f3 := -0.0012727345647388431*r + 0.050755104336657406*g + 0.9505176302280817*b

	return LinearProPhotoToProPhoto(f1, f2, f3)
}

// Conversion path (3 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> Linear Rec. 2020
func DisplayP3ToLinearRec2020(r, g, b float64) (float64, float64, float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 0.7538330343617219*r + 0.1985973690526164*g + 0.047569596585661844*b
	f2 := 0.0457438489653583*r + 0.9417772198116937*g + 0.012478931222948117*b
	f3 := -0.0012103403545183947*r + 0.01760171730108999*g + 0.9836086230534284*b

	return f1, f2, f3
}

// Conversion path (4 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> Linear Rec. 2020
//	-> Rec. 2020
func DisplayP3ToRec2020(r, g, b float64) (float64, float64, float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 0.7538330343617219*r + 0.1985973690526164*g + 0.047569596585661844*b
	f2 := 0.0457438489653583*r + 0.9417772198116937*g + 0.012478931222948117*b
	f3 := -0.0012103403545183947*r + 0.01760171730108999*g + 0.9836086230534284*b

	return LinearRec2020ToRec2020(f1, f2, f3)
}

// Conversion path (5 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HSL
func DisplayP3ToHsl(r, g, b float64) (h, s, l float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 1.22494017628056*r - 0.22494017628056012*g
	f2 := -0.04205695470968811*r + 1.042056954709688*g
	f3 := -0.019637554590334446*r - 0.07863604555063179*g + 1.0982736001409663*b

	r, g, b = LinearSrgbToSrgb(f1, f2, f3)
	return SrgbToHsl(r, g, b)
}

// Conversion path (5 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HSV
func DisplayP3ToHsv(r, g, b float64) (h, s, v float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 1.22494017628056*r - 0.22494017628056012*g
	f2 := -0.04205695470968811*r + 1.042056954709688*g
	f3 := -0.019637554590334446*r - 0.07863604555063179*g + 1.0982736001409663*b

	r, g, b = LinearSrgbToSrgb(f1, f2, f3)
	return SrgbToHsv(r, g, b)
}

// Conversion path (5 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HWB
func DisplayP3ToHwb(r, g, b float64) (float64, float64, float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 1.22494017628056*r - 0.22494017628056012*g
	f2 := -0.04205695470968811*r + 1.042056954709688*g
	f3 := -0.019637554590334446*r - 0.07863604555063179*g + 1.0982736001409663*b

	r, g, b = LinearSrgbToSrgb(f1, f2, f3)
	return SrgbToHwb(r, g, b)
}

// Conversion path (2 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
func DisplayP3ToXyzD65(r, g, b float64) (x, y, z float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	x = 0.4865709486482162*r + 0.265667693169093*g + 0.19821728523436252*b
	y = 0.2289745640697488*r + 0.6917385218365062*g + 0.07928691409374501*b
	z = 0.045113381858902624*g + 1.043944368900976*b

	return
}

// Conversion path (3 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> CIE XYZ D50
func DisplayP3ToXyzD50(r, g, b float64) (x, y, z float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	x = 0.5151464429681158*r + 0.29200998206385786*g + 0.15713925139759397*b
	y = 0.2412003221252552*r + 0.6922225411313817*g + 0.06657713674336295*b
	z = -0.0010501391471401667*r + 0.04187827018907464*g + 0.7842764714685259*b

	return
}

// Conversion path (4 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE Lab
func DisplayP3ToLab(r, g, b float64) (float64, float64, float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 0.5151464429681158*r + 0.29200998206385786*g + 0.15713925139759397*b
	f2 := 0.2412003221252552*r + 0.6922225411313817*g + 0.06657713674336295*b
	f3 := -0.0010501391471401667*r + 0.04187827018907464*g + 0.7842764714685259*b

	return XyzD50ToLab(f1, f2, f3)
}

// Conversion path (5 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE Lab
//	-> CIE LCh
func DisplayP3ToLch(r, g, b float64) (l, c, h float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 0.5151464429681158*r + 0.29200998206385786*g + 0.15713925139759397*b
	f2 := 0.2412003221252552*r + 0.6922225411313817*g + 0.06657713674336295*b
	f3 := -0.0010501391471401667*r + 0.04187827018907464*g + 0.7842764714685259*b

	l, a, b := XyzD50ToLab(f1, f2, f3)
	return LabToLch(l, a, b)
}

// Conversion path (3 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> Oklab
func DisplayP3ToOklab(r, g, b float64) (float64, float64, float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 0.4813798527499544*r + 0.46211837101131814*g + 0.05650177623872756*b
	f2 := 0.22883194181124472*r + 0.6532168193835677*g + 0.1179512388051878*b
	f3 := 0.08394575232299314*r + 0.22416527097756644*g + 0.6918889766994405*b

	f1 = math.Cbrt(f1)
	f2 = math.Cbrt(f2)
	f3 = math.Cbrt(f3)

	f4 := 0.210454268309314*f1 + 0.7936177747023054*f2 - 0.0040720430116193*f3
	f5 := 1.9779985324311684*f1 - 2.42859224204858*f2 + 0.450593709617411*f3
	f6 := 0.0259040424655478*f1 + 0.7827717124575296*f2 - 0.8086757549230774*f3

	return f4, f5, f6
}

// Conversion path (4 steps):
//
//	Display P3
//	-> Linear Display P3
//	-> CIE XYZ D65
//	-> Oklab
//	-> Oklch
func DisplayP3ToOklch(r, g, b float64) (l, c, h float64) {
	r, g, b = DisplayP3ToLinearDisplayP3(r, g, b)

	f1 := 0.4813798527499544*r + 0.46211837101131814*g + 0.05650177623872756*b
	f2 := 0.22883194181124472*r + 0.6532168193835677*g + 0.1179512388051878*b
	f3 := 0.08394575232299314*r + 0.22416527097756644*g + 0.6918889766994405*b

	f1 = math.Cbrt(f1)
	f2 = math.Cbrt(f2)
	f3 = math.Cbrt(f3)

	f4 := 0.210454268309314*f1 + 0.7936177747023054*f2 - 0.0040720430116193*f3
	f5 := 1.9779985324311684*f1 - 2.42859224204858*f2 + 0.450593709617411*f3
	f6 := 0.0259040424655478*f1 + 0.7827717124575296*f2 - 0.8086757549230774*f3

	return LabToLch(f4, f5, f6)
}
