// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package convert

import (
	"math"
)

// Conversion path (3 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
func LchToXyzD65(l, c, h float64) (x, y, z float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z = LabToXyzD50(l, a, b)

	f1 := 0.955473421488075*x - 0.023098454948764637*y + 0.06325924320057065*z
	f2 := -0.028369709333863714*x + 1.009995398081304*y + 0.021041441191917323*z
	f3 := 0.012314014864481988*x - 0.020507649298898947*y + 1.330365926242124*z

	return f1, f2, f3
}

// Conversion path (4 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
//	-> CIE xyY
func LchToXyY(l, c, h float64) (x, y, luminance float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	f1 := 0.955473421488075*x - 0.023098454948764637*y + 0.06325924320057065*z
	f2 := -0.028369709333863714*x + 1.009995398081304*y + 0.021041441191917323*z
	f3 := 0.012314014864481988*x - 0.020507649298898947*y + 1.330365926242124*z

	return XyzD65ToXyY(f1, f2, f3)
}

// Conversion path (2 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
func LchToXyzD50(l, c, h float64) (x, y, z float64) {
	l, a, b := LchToLab(l, c, h)
	return LabToXyzD50(l, a, b)
}

// Conversion path (4 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
//	-> Linear sRGB
func LchToLinearSrgb(l, c, h float64) (r, g, b float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	r = 3.1341358529001186*x - 1.6173859980180432*y - 0.4906622179110977*z
	g = -0.9787954765557776*x + 1.916254377395988*y + 0.03344287339036697*z
	b = 0.07195539255794736*x - 0.2289767598151819*y + 1.4053860351131178*z

	return
}

// Conversion path (5 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
func LchToSrgb(l, c, h float64) (r, g, b float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	r = 3.1341358529001186*x - 1.6173859980180432*y - 0.4906622179110977*z
	g = -0.9787954765557776*x + 1.916254377395988*y + 0.03344287339036697*z
	b = 0.07195539255794736*x - 0.2289767598151819*y + 1.4053860351131178*z

	return LinearSrgbToSrgb(r, g, b)
}

// Conversion path (4 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
//	-> Linear Display P3
func LchToLinearDisplayP3(l, c, h float64) (r, g, b float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	r = 2.4039341218554973*x - 0.9900304424955934*y - 0.39761363181465614*z
	g = -0.8422700161454687*x + 1.7989580161067076*y + 0.016045624770904755*z
	b = 0.04819381686413314*x - 0.09738519815446052*y + 1.2736713693321269*z

	return
}

// Conversion path (5 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
//	-> Linear Display P3
//	-> Display P3
func LchToDisplayP3(l, c, h float64) (r, g, b float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	r = 2.4039341218554973*x - 0.9900304424955934*y - 0.39761363181465614*z
	g = -0.8422700161454687*x + 1.7989580161067076*y + 0.016045624770904755*z
	b = 0.04819381686413314*x - 0.09738519815446052*y + 1.2736713693321269*z

	return LinearDisplayP3ToDisplayP3(r, g, b)
}

// Conversion path (4 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
//	-> Linear Adobe RGB (1998)
func LchToLinearA98(l, c, h float64) (r, g, b float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	r = 1.9624670363768812*x - 0.6107423404815076*y - 0.34135809808271556*z
	g = -0.9787954765557776*x + 1.9162543773959881*y + 0.03344287339036699*z
	b = 0.02870443944957115*x - 0.14067486633170695*y + 1.3489141814137942*z

	return
}

// Conversion path (5 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
//	-> Linear Adobe RGB (1998)
//	-> Adobe RGB (1998)
func LchToA98(l, c, h float64) (r, g, b float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	r = 1.9624670363768812*x - 0.6107423404815076*y - 0.34135809808271556*z
	g = -0.9787954765557776*x + 1.9162543773959881*y + 0.03344287339036699*z
	b = 0.02870443944957115*x - 0.14067486633170695*y + 1.3489141814137942*z

	return LinearA98ToA98(r, g, b)
}

// Conversion path (3 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> Linear ProPhoto
func LchToLinearProPhoto(l, c, h float64) (r, g, b float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	r = 1.3457989731028281*x - 0.2555801000799754*y - 0.05110628506753401*z
	g = -0.5446224939028346*x + 1.5082327413132781*y + 0.020536032391479723*z
	b = 1.2119675456389454 * z

	return
}

// Conversion path (4 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> Linear ProPhoto
//	-> ProPhoto
func LchToProPhoto(l, c, h float64) (r, g, b float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	r = 1.3457989731028281*x - 0.2555801000799754*y - 0.05110628506753401*z
	g = -0.5446224939028346*x + 1.5082327413132781*y + 0.020536032391479723*z
	b = 1.2119675456389454 * z

	return LinearProPhotoToProPhoto(r, g, b)
}

// Conversion path (4 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
//	-> Linear Rec. 2020
func LchToLinearRec2020(l, c, h float64) (r, g, b float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	r = 1.6471849046717661*x - 0.3936818981316474*y - 0.23595963848828277*z
	g = -0.6826641074173821*x + 1.6477146127444076*y + 0.01281708338512088*z
	b = 0.02966887665275662*x - 0.06292589642970013*y + 1.2535578201865771*z

	return
}

// Conversion path (5 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
//	-> Linear Rec. 2020
//	-> Rec. 2020
func LchToRec2020(l, c, h float64) (r, g, b float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	r = 1.6471849046717661*x - 0.3936818981316474*y - 0.23595963848828277*z
	g = -0.6826641074173821*x + 1.6477146127444076*y + 0.01281708338512088*z
	b = 0.02966887665275662*x - 0.06292589642970013*y + 1.2535578201865771*z

	return LinearRec2020ToRec2020(r, g, b)
}

// Conversion path (6 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HSL
func LchToHsl(l, c, h float64) (float64, float64, float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	r := 3.1341358529001186*x - 1.6173859980180432*y - 0.4906622179110977*z
	g := -0.9787954765557776*x + 1.916254377395988*y + 0.03344287339036697*z
	b = 0.07195539255794736*x - 0.2289767598151819*y + 1.4053860351131178*z

	r, g, b = LinearSrgbToSrgb(r, g, b)
	return SrgbToHsl(r, g, b)
}

// Conversion path (6 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HSV
func LchToHsv(l, c, h float64) (float64, float64, float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	r := 3.1341358529001186*x - 1.6173859980180432*y - 0.4906622179110977*z
	g := -0.9787954765557776*x + 1.916254377395988*y + 0.03344287339036697*z
	b = 0.07195539255794736*x - 0.2289767598151819*y + 1.4053860351131178*z

	r, g, b = LinearSrgbToSrgb(r, g, b)
	return SrgbToHsv(r, g, b)
}

// Conversion path (6 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HWB
func LchToHwb(l, c, h float64) (float64, float64, float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	r := 3.1341358529001186*x - 1.6173859980180432*y - 0.4906622179110977*z
	g := -0.9787954765557776*x + 1.916254377395988*y + 0.03344287339036697*z
	b = 0.07195539255794736*x - 0.2289767598151819*y + 1.4053860351131178*z

	r, g, b = LinearSrgbToSrgb(r, g, b)
	return SrgbToHwb(r, g, b)
}

// Conversion path (3 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE Luv
func LchToLuv(l, c, h float64) (float64, float64, float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)
	return XyzD50ToLuv(x, y, z)
}

// Conversion path (4 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE Luv
//	-> CIE LChuv
func LchToLchuv(l, c, h float64) (float64, float64, float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)
	l, u, v := XyzD50ToLuv(x, y, z)
	return LuvToLchuv(l, u, v)
}

// Conversion path (4 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
//	-> Oklab
func LchToOklab(l, c, h float64) (float64, float64, float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	f1 := 0.770700042043117*x + 0.34924840261939605*y - 0.11202351884164682*z
	f2 := 0.005596492483688392*x + 0.9370723401136769*y + 0.0697256883625278*z
	f3 := 0.046337142621910646*x + 0.25277531574310524*y + 0.851458076746796*z

	f1 = math.Cbrt(f1)
	f2 = math.Cbrt(f2)
	f3 = math.Cbrt(f3)

	l = 0.210454268309314*f1 + 0.7936177747023054*f2 - 0.0040720430116193*f3
	a = 1.9779985324311684*f1 - 2.42859224204858*f2 + 0.450593709617411*f3
	b = 0.0259040424655478*f1 + 0.7827717124575296*f2 - 0.8086757549230774*f3

	return l, a, b
}

// Conversion path (5 steps):
//
//	CIE LCh
//	-> CIE Lab
//	-> CIE XYZ D50
//	-> CIE XYZ D65
//	-> Oklab
//	-> Oklch
func LchToOklch(l, c, h float64) (float64, float64, float64) {
	l, a, b := LchToLab(l, c, h)
	x, y, z := LabToXyzD50(l, a, b)

	f1 := 0.770700042043117*x + 0.34924840261939605*y - 0.11202351884164682*z
	f2 := 0.005596492483688392*x + 0.9370723401136769*y + 0.0697256883625278*z
	f3 := 0.046337142621910646*x + 0.25277531574310524*y + 0.851458076746796*z

	f1 = math.Cbrt(f1)
	f2 = math.Cbrt(f2)
	f3 = math.Cbrt(f3)

	l = 0.210454268309314*f1 + 0.7936177747023054*f2 - 0.0040720430116193*f3
	a = 1.9779985324311684*f1 - 2.42859224204858*f2 + 0.450593709617411*f3
	b = 0.0259040424655478*f1 + 0.7827717124575296*f2 - 0.8086757549230774*f3

	return OklabToOklch(l, a, b)
}
