// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package convert

// Calls [LinearRec2020ToSrgb]
//
// Conversion path (4 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
func LinearRec2100ToSrgb(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToSrgb(r, g, b)
}

// Calls [LinearRec2020ToLinearSrgb]
//
// Conversion path (3 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear sRGB
func LinearRec2100ToLinearSrgb(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToLinearSrgb(r, g, b)
}

// Calls [LinearRec2020ToDisplayP3]
//
// Conversion path (4 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear Display P3
//	-> Display P3
func LinearRec2100ToDisplayP3(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToDisplayP3(r, g, b)
}

// Calls [LinearRec2020ToLinearDisplayP3]
//
// Conversion path (3 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear Display P3
func LinearRec2100ToLinearDisplayP3(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToLinearDisplayP3(r, g, b)
}

// Calls [LinearRec2020ToA98]
//
// Conversion path (4 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear Adobe RGB (1998)
//	-> Adobe RGB (1998)
func LinearRec2100ToA98(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToA98(r, g, b)
}

// Calls [LinearRec2020ToLinearA98]
//
// Conversion path (3 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear Adobe RGB (1998)
func LinearRec2100ToLinearA98(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToLinearA98(r, g, b)
}

// Calls [LinearRec2020ToProPhoto]
//
// Conversion path (5 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> Linear ProPhoto
//	-> ProPhoto
func LinearRec2100ToProPhoto(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToProPhoto(r, g, b)
}

// Calls [LinearRec2020ToLinearProPhoto]
//
// Conversion path (4 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> Linear ProPhoto
func LinearRec2100ToLinearProPhoto(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToLinearProPhoto(r, g, b)
}

// Calls [LinearRec2020ToRec2020]
//
// Conversion path (2 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> Rec. 2020
func LinearRec2100ToRec2020(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToRec2020(r, g, b)
}

// Calls [LinearRec2020ToRec2020OETF]
//
// Conversion path (2 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> Rec. 2020 Scene Referred
func LinearRec2100ToRec2020OETF(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToRec2020OETF(r, g, b)
}

// Conversion path (1 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
func LinearRec2100ToLinearRec2020(r, g, b float64) (float64, float64, float64) {
	return r, g, b
}

// Conversion path (1 steps):
//
//	Linear Rec. 2100
//	-> Rec. 2100 PQ
func LinearRec2100ToRec2100PQ(r, g, b float64) (float64, float64, float64) {
	return Rec2100PQEncode(r), Rec2100PQEncode(g), Rec2100PQEncode(b)
}

// Conversion path (1 steps):
//
//	Linear Rec. 2100
//	-> Rec. 2100 HLG
func LinearRec2100ToRec2100HLG(r, g, b float64) (float64, float64, float64) {
	return Rec2100HLGEncode(r), Rec2100HLGEncode(g), Rec2100HLGEncode(b)
}

// Calls [LinearRec2020ToXyzD50]
//
// Conversion path (3 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
func LinearRec2100ToXyzD50(r, g, b float64) (x, y, z float64) {
	return LinearRec2020ToXyzD50(r, g, b)
}

// Calls [LinearRec2020ToXyzD65]
//
// Conversion path (2 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
func LinearRec2100ToXyzD65(r, g, b float64) (x, y, z float64) {
	return LinearRec2020ToXyzD65(r, g, b)
}

// Calls [LinearRec2020ToXyzAbsD65]
//
// Conversion path (3 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Absolute XYZ D65
func LinearRec2100ToXyzAbsD65(r, g, b float64) (x, y, z float64) {
	return LinearRec2020ToXyzAbsD65(r, g, b)
}

// Calls [LinearRec2020ToXyYD50]
//
// Conversion path (4 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE xyY
func LinearRec2100ToXyYD50(r, g, b float64) (x, y, luminance float64) {
	return LinearRec2020ToXyYD50(r, g, b)
}

// Calls [LinearRec2020ToXyYD65]
//
// Conversion path (3 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE xyY
func LinearRec2100ToXyYD65(r, g, b float64) (x, y, luminance float64) {
	return LinearRec2020ToXyYD65(r, g, b)
}

// Calls [LinearRec2020ToLabD50]
//
// Conversion path (4 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE Lab D50
func LinearRec2100ToLabD50(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToLabD50(r, g, b)
}

// Calls [LinearRec2020ToLchD50]
//
// Conversion path (5 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE Lab D50
//	-> CIE LCh D50
func LinearRec2100ToLchD50(r, g, b float64) (l, c, h float64) {
	return LinearRec2020ToLchD50(r, g, b)
}

// Calls [LinearRec2020ToLabD65]
//
// Conversion path (3 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE Lab D65
func LinearRec2100ToLabD65(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToLabD65(r, g, b)
}

// Calls [LinearRec2020ToLchD65]
//
// Conversion path (4 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE Lab D65
//	-> CIE LCh D65
func LinearRec2100ToLchD65(r, g, b float64) (l, c, h float64) {
	return LinearRec2020ToLchD65(r, g, b)
}

// Calls [LinearRec2020ToLuvD50]
//
// Conversion path (4 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE Luv D50
func LinearRec2100ToLuvD50(r, g, b float64) (l, u, v float64) {
	return LinearRec2020ToLuvD50(r, g, b)
}

// Calls [LinearRec2020ToLchuvD50]
//
// Conversion path (5 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE Luv D50
//	-> CIE LChuv D50
func LinearRec2100ToLchuvD50(r, g, b float64) (l, c, h float64) {
	return LinearRec2020ToLchuvD50(r, g, b)
}

// Calls [LinearRec2020ToLuvD65]
//
// Conversion path (3 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE Luv D65
func LinearRec2100ToLuvD65(r, g, b float64) (l, u, v float64) {
	return LinearRec2020ToLuvD65(r, g, b)
}

// Calls [LinearRec2020ToLchuvD65]
//
// Conversion path (4 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE Luv D65
//	-> CIE LChuv D65
func LinearRec2100ToLchuvD65(r, g, b float64) (l, c, h float64) {
	return LinearRec2020ToLchuvD65(r, g, b)
}

// Calls [LinearRec2020ToOklab]
//
// Conversion path (3 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Oklab
func LinearRec2100ToOklab(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToOklab(r, g, b)
}

// Calls [LinearRec2020ToOklch]
//
// Conversion path (4 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Oklab
//	-> Oklch
func LinearRec2100ToOklch(r, g, b float64) (l, c, h float64) {
	return LinearRec2020ToOklch(r, g, b)
}

// Calls [LinearRec2020ToHsl]
//
// Conversion path (5 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HSL
func LinearRec2100ToHsl(r, g, b float64) (h, s, l float64) {
	return LinearRec2020ToHsl(r, g, b)
}

// Calls [LinearRec2020ToHsv]
//
// Conversion path (5 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HSV
func LinearRec2100ToHsv(r, g, b float64) (h, s, v float64) {
	return LinearRec2020ToHsv(r, g, b)
}

// Calls [LinearRec2020ToHwb]
//
// Conversion path (5 steps):
//
//	Linear Rec. 2100
//	-> Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HWB
func LinearRec2100ToHwb(r, g, b float64) (float64, float64, float64) {
	return LinearRec2020ToHwb(r, g, b)
}
