// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package convert

import (
	"math"
)

// Conversion path (3 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
func LinearRec2020ToSrgb(r, g, b float64) (float64, float64, float64) {
	f1 := 1.6604910021084345*r - 0.5876411387885498*g - 0.07284986331988486*b
	f2 := -0.12455047452159054*r + 1.13289989712596*g - 0.008349422604369473*b
	f3 := -0.01815076335490522*r - 0.10057889800800737*g + 1.1187296613629125*b

	return linearSrgbToSrgb(f1), linearSrgbToSrgb(f2), linearSrgbToSrgb(f3)
}

// Conversion path (2 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear sRGB
func LinearRec2020ToLinearSrgb(r, g, b float64) (float64, float64, float64) {
	f1 := 1.6604910021084345*r - 0.5876411387885498*g - 0.07284986331988486*b
	f2 := -0.12455047452159054*r + 1.13289989712596*g - 0.008349422604369473*b
	f3 := -0.01815076335490522*r - 0.10057889800800737*g + 1.1187296613629125*b
	return f1, f2, f3
}

// Conversion path (3 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear Display P3
//	-> Display P3
func LinearRec2020ToDisplayP3(r, g, b float64) (float64, float64, float64) {
	f1 := 1.3435782525843316*r - 0.2821796705261357*g - 0.061398582058196184*b
	f2 := -0.06529745278911954*r + 1.075787915848574*g - 0.010490463059454965*b
	f3 := 0.0028217872617010515*r - 0.019598494524494175*g + 1.0167767072627927*b

	return linearSrgbToSrgb(f1), linearSrgbToSrgb(f2), linearSrgbToSrgb(f3)
}

// Conversion path (2 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear Display P3
func LinearRec2020ToLinearDisplayP3(r, g, b float64) (float64, float64, float64) {
	f1 := 1.3435782525843316*r - 0.2821796705261357*g - 0.061398582058196184*b
	f2 := -0.06529745278911954*r + 1.075787915848574*g - 0.010490463059454965*b
	f3 := 0.0028217872617010515*r - 0.019598494524494175*g + 1.0167767072627927*b
	return f1, f2, f3
}

// Conversion path (3 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear Adobe RGB (1998)
//	-> Adobe RGB (1998)
func LinearRec2020ToA98(r, g, b float64) (float64, float64, float64) {
	f1 := 1.1519783947159163*r - 0.09750305530240852*g - 0.05447533941350763*b
	f2 := -0.12455047452159049*r + 1.13289989712596*g - 0.008349422604369452*b
	f3 := -0.022530382781055815*r - 0.049806507428388914*g + 1.072336890209445*b

	return linearA98ToA98(f1), linearA98ToA98(f2), linearA98ToA98(f3)
}

// Conversion path (2 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear Adobe RGB (1998)
func LinearRec2020ToLinearA98(r, g, b float64) (float64, float64, float64) {
	f1 := 1.1519783947159163*r - 0.09750305530240852*g - 0.05447533941350763*b
	f2 := -0.12455047452159049*r + 1.13289989712596*g - 0.008349422604369452*b
	f3 := -0.022530382781055815*r - 0.049806507428388914*g + 1.072336890209445*b
	return f1, f2, f3
}

// Conversion path (4 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> Linear ProPhoto
//	-> ProPhoto
func LinearRec2020ToProPhoto(r, g, b float64) (float64, float64, float64) {
	f1 := 0.8351932494374541*r + 0.04886530848171695*g + 0.11594144208082868*b
	f2 := 0.054034572682208695*r + 0.9289098956999433*g + 0.017055531617847765*b
	f3 := -0.002342038970725345*r + 0.036332153161694594*g + 0.9660098858090308*b

	return linearProPhotoToProPhoto(f1), linearProPhotoToProPhoto(f2), linearProPhotoToProPhoto(f3)
}

// Conversion path (3 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> Linear ProPhoto
func LinearRec2020ToLinearProPhoto(r, g, b float64) (float64, float64, float64) {
	f1 := 0.8351932494374541*r + 0.04886530848171695*g + 0.11594144208082868*b
	f2 := 0.054034572682208695*r + 0.9289098956999433*g + 0.017055531617847765*b
	f3 := -0.002342038970725345*r + 0.036332153161694594*g + 0.9660098858090308*b
	return f1, f2, f3
}

// Conversion path (1 steps):
//
//	Linear Rec. 2020
//	-> Rec. 2020
func LinearRec2020ToRec2020(r, g, b float64) (float64, float64, float64) {
	return linearRec2020ToRec2020(r), linearRec2020ToRec2020(g), linearRec2020ToRec2020(b)
}

// Conversion path (1 steps):
//
//	Linear Rec. 2020
//	-> Rec. 2020 Scene Referred
func LinearRec2020ToRec2020OETF(r, g, b float64) (float64, float64, float64) {
	return linearRec2020ToRec2020OETF(r), linearRec2020ToRec2020OETF(g), linearRec2020ToRec2020OETF(b)
}

// Conversion path (1 steps):
//
//	Linear Rec. 2020
//	-> Linear Rec. 2100
func LinearRec2020ToLinearRec2100(r, g, b float64) (float64, float64, float64) {
	return r, g, b
}

// Conversion path (2 steps):
//
//	Linear Rec. 2020
//	-> Linear Rec. 2100
//	-> Rec. 2100 PQ
func LinearRec2020ToRec2100PQ(r, g, b float64) (float64, float64, float64) {
	return rec2100PQEncode(r), rec2100PQEncode(g), rec2100PQEncode(b)
}

// Conversion path (2 steps):
//
//	Linear Rec. 2020
//	-> Linear Rec. 2100
//	-> Rec. 2100 HLG
func LinearRec2020ToRec2100HLG(r, g, b float64) (float64, float64, float64) {
	return rec2100HLGEncode(r), rec2100HLGEncode(g), rec2100HLGEncode(b)
}

// Conversion path (2 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
func LinearRec2020ToXyzD50(r, g, b float64) (x, y, z float64) {
	x = 0.6735154631882759*r + 0.16569726370390456*g + 0.12508294953738702*b
	y = 0.27905900514112053*r + 0.6753180057491096*g + 0.04562298910976964*b
	z = -0.001932427134004343*r + 0.029977826792829176*g + 0.7970592028516353*b
	return
}

// Conversion path (1 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
func LinearRec2020ToXyzD65(r, g, b float64) (x, y, z float64) {
	x = 0.6369580483012911*r + 0.14461690358620835*g + 0.16888097516417208*b
	y = 0.262700212011267*r + 0.6779980715188709*g + 0.05930171646986195*b
	z = 0.028072693049087435*g + 1.0609850577107909*b
	return
}

// Conversion path (2 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Absolute XYZ D65
func LinearRec2020ToXyzAbsD65(r, g, b float64) (x, y, z float64) {
	x = 0.6369580483012911*r + 0.14461690358620835*g + 0.16888097516417208*b
	y = 0.262700212011267*r + 0.6779980715188709*g + 0.05930171646986195*b
	z = 0.028072693049087435*g + 1.0609850577107909*b

	return XyzD65ToXyzAbsD65(x, y, z)
}

// Conversion path (3 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE xyY
func LinearRec2020ToXyYD50(r, g, b float64) (x, y, luminance float64) {
	x = 0.6735154631882759*r + 0.16569726370390456*g + 0.12508294953738702*b
	y = 0.27905900514112053*r + 0.6753180057491096*g + 0.04562298910976964*b
	z := -0.001932427134004343*r + 0.029977826792829176*g + 0.7970592028516353*b

	return XyzToXyY(x, y, z)
}

// Conversion path (2 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE xyY
func LinearRec2020ToXyYD65(r, g, b float64) (x, y, luminance float64) {
	x = 0.6369580483012911*r + 0.14461690358620835*g + 0.16888097516417208*b
	y = 0.262700212011267*r + 0.6779980715188709*g + 0.05930171646986195*b
	z := 0.028072693049087435*g + 1.0609850577107909*b

	return XyzToXyY(x, y, z)
}

// Conversion path (3 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE Lab D50
func LinearRec2020ToLabD50(r, g, b float64) (float64, float64, float64) {
	x := 0.6735154631882759*r + 0.16569726370390456*g + 0.12508294953738702*b
	y := 0.27905900514112053*r + 0.6753180057491096*g + 0.04562298910976964*b
	z := -0.001932427134004343*r + 0.029977826792829176*g + 0.7970592028516353*b

	return XyzD50ToLabD50(x, y, z)
}

// Conversion path (4 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE Lab D50
//	-> CIE LCh D50
func LinearRec2020ToLchD50(r, g, b float64) (l, c, h float64) {
	x := 0.6735154631882759*r + 0.16569726370390456*g + 0.12508294953738702*b
	y := 0.27905900514112053*r + 0.6753180057491096*g + 0.04562298910976964*b
	z := -0.001932427134004343*r + 0.029977826792829176*g + 0.7970592028516353*b

	l, a, b := XyzD50ToLabD50(x, y, z)
	return LxyToLch(l, a, b)
}

// Conversion path (2 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE Lab D65
func LinearRec2020ToLabD65(r, g, b float64) (float64, float64, float64) {
	x := 0.6369580483012911*r + 0.14461690358620835*g + 0.16888097516417208*b
	y := 0.262700212011267*r + 0.6779980715188709*g + 0.05930171646986195*b
	z := 0.028072693049087435*g + 1.0609850577107909*b

	return XyzD65ToLabD65(x, y, z)
}

// Conversion path (3 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE Lab D65
//	-> CIE LCh D65
func LinearRec2020ToLchD65(r, g, b float64) (l, c, h float64) {
	x := 0.6369580483012911*r + 0.14461690358620835*g + 0.16888097516417208*b
	y := 0.262700212011267*r + 0.6779980715188709*g + 0.05930171646986195*b
	z := 0.028072693049087435*g + 1.0609850577107909*b

	l, a, b := XyzD65ToLabD65(x, y, z)
	return LxyToLch(l, a, b)
}

// Conversion path (3 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE Luv D50
func LinearRec2020ToLuvD50(r, g, b float64) (l, u, v float64) {
	x := 0.6735154631882759*r + 0.16569726370390456*g + 0.12508294953738702*b
	y := 0.27905900514112053*r + 0.6753180057491096*g + 0.04562298910976964*b
	z := -0.001932427134004343*r + 0.029977826792829176*g + 0.7970592028516353*b

	return XyzD50ToLuvD50(x, y, z)
}

// Conversion path (4 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE Luv D50
//	-> CIE LChuv D50
func LinearRec2020ToLchuvD50(r, g, b float64) (l, c, h float64) {
	x := 0.6735154631882759*r + 0.16569726370390456*g + 0.12508294953738702*b
	y := 0.27905900514112053*r + 0.6753180057491096*g + 0.04562298910976964*b
	z := -0.001932427134004343*r + 0.029977826792829176*g + 0.7970592028516353*b

	l, u, v := XyzD50ToLuvD50(x, y, z)
	return LxyToLch(l, u, v)
}

// Conversion path (2 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE Luv D65
func LinearRec2020ToLuvD65(r, g, b float64) (l, u, v float64) {
	x := 0.6369580483012911*r + 0.14461690358620835*g + 0.16888097516417208*b
	y := 0.262700212011267*r + 0.6779980715188709*g + 0.05930171646986195*b
	z := 0.028072693049087435*g + 1.0609850577107909*b

	return XyzD65ToLuvD65(x, y, z)
}

// Conversion path (3 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> CIE Luv D65
//	-> CIE LChuv D65
func LinearRec2020ToLchuvD65(r, g, b float64) (l, c, h float64) {
	x := 0.6369580483012911*r + 0.14461690358620835*g + 0.16888097516417208*b
	y := 0.262700212011267*r + 0.6779980715188709*g + 0.05930171646986195*b
	z := 0.028072693049087435*g + 1.0609850577107909*b

	l, u, v := XyzD65ToLuvD65(x, y, z)
	return LxyToLch(l, u, v)
}

// Conversion path (2 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Oklab
func LinearRec2020ToOklab(r, g, b float64) (float64, float64, float64) {
	f1 := 0.6167557848654442*r + 0.36019840122646335*g + 0.023045813908092305*b
	f2 := 0.2651330593926367*r + 0.6358393720678491*g + 0.09902756853951414*b
	f3 := 0.10010262952034828*r + 0.20390652261661443*g + 0.6959908478630372*b

	f1 = math.Cbrt(f1)
	f2 = math.Cbrt(f2)
	f3 = math.Cbrt(f3)

	l := 0.210454268309314*f1 + 0.7936177747023054*f2 - 0.0040720430116193*f3
	a := 1.9779985324311684*f1 - 2.42859224204858*f2 + 0.450593709617411*f3
	b = 0.0259040424655478*f1 + 0.7827717124575296*f2 - 0.8086757549230774*f3

	return l, a, b
}

// Conversion path (3 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Oklab
//	-> Oklch
func LinearRec2020ToOklch(r, g, b float64) (l, c, h float64) {
	f1 := 0.6167557848654442*r + 0.36019840122646335*g + 0.023045813908092305*b
	f2 := 0.2651330593926367*r + 0.6358393720678491*g + 0.09902756853951414*b
	f3 := 0.10010262952034828*r + 0.20390652261661443*g + 0.6959908478630372*b

	f1 = math.Cbrt(f1)
	f2 = math.Cbrt(f2)
	f3 = math.Cbrt(f3)

	l = 0.210454268309314*f1 + 0.7936177747023054*f2 - 0.0040720430116193*f3
	a := 1.9779985324311684*f1 - 2.42859224204858*f2 + 0.450593709617411*f3
	b = 0.0259040424655478*f1 + 0.7827717124575296*f2 - 0.8086757549230774*f3

	return LxyToLch(l, a, b)
}

// Conversion path (4 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HSL
func LinearRec2020ToHsl(r, g, b float64) (h, s, l float64) {
	f1 := 1.6604910021084345*r - 0.5876411387885498*g - 0.07284986331988486*b
	f2 := -0.12455047452159054*r + 1.13289989712596*g - 0.008349422604369473*b
	f3 := -0.01815076335490522*r - 0.10057889800800737*g + 1.1187296613629125*b

	r, g, b = linearSrgbToSrgb(f1), linearSrgbToSrgb(f2), linearSrgbToSrgb(f3)
	return SrgbToHsl(r, g, b)
}

// Conversion path (4 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HSV
func LinearRec2020ToHsv(r, g, b float64) (h, s, v float64) {
	f1 := 1.6604910021084345*r - 0.5876411387885498*g - 0.07284986331988486*b
	f2 := -0.12455047452159054*r + 1.13289989712596*g - 0.008349422604369473*b
	f3 := -0.01815076335490522*r - 0.10057889800800737*g + 1.1187296613629125*b

	r, g, b = linearSrgbToSrgb(f1), linearSrgbToSrgb(f2), linearSrgbToSrgb(f3)
	return SrgbToHsv(r, g, b)
}

// Conversion path (4 steps):
//
//	Linear Rec. 2020
//	-> CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HWB
func LinearRec2020ToHwb(r, g, b float64) (float64, float64, float64) {
	f1 := 1.6604910021084345*r - 0.5876411387885498*g - 0.07284986331988486*b
	f2 := -0.12455047452159054*r + 1.13289989712596*g - 0.008349422604369473*b
	f3 := -0.01815076335490522*r - 0.10057889800800737*g + 1.1187296613629125*b

	r, g, b = linearSrgbToSrgb(f1), linearSrgbToSrgb(f2), linearSrgbToSrgb(f3)
	return SrgbToHwb(r, g, b)
}
