// Code generated by running "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package convert

import ()

var (
	D50 = [3]float64{0.9642956764295677, 1, 0.8251046025104602}
	D65 = [3]float64{0.9504559270516716, 1, 1.0890577507598784}
)
