// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package convert

const (
	d50X = 0.9642956764295677
	d50Y = 1
	d50Z = 0.8251046025104602

	d50InvX = 1 / d50X
	d50InvY = 1 / d50Y
	d50InvZ = 1 / d50Z
)

const (
	d65X = 0.9504559270516716
	d65Y = 1
	d65Z = 1.0890577507598784

	d65InvX = 1 / d65X
	d65InvY = 1 / d65Y
	d65InvZ = 1 / d65Z
)
