// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package convert

import (
	"math"
)

// Conversion path (2 steps):
//
//	CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
func XyzD65ToSrgb(x, y, z float64) (r, g, b float64) {
	r = 3.2409699419045226*x - 1.5373831775700944*y - 0.49861076029300344*z
	g = -0.9692436362808796*x + 1.8759675015077204*y + 0.041555057407175605*z
	b = 0.05563007969699363*x - 0.2039769588889765*y + 1.0569715142428784*z

	return SrgbEncode(r), SrgbEncode(g), SrgbEncode(b)
}

// Conversion path (1 steps):
//
//	CIE XYZ D65
//	-> Linear sRGB
func XyzD65ToLinearSrgb(x, y, z float64) (r, g, b float64) {
	r = 3.2409699419045226*x - 1.5373831775700944*y - 0.49861076029300344*z
	g = -0.9692436362808796*x + 1.8759675015077204*y + 0.041555057407175605*z
	b = 0.05563007969699363*x - 0.2039769588889765*y + 1.0569715142428784*z
	return
}

// Conversion path (2 steps):
//
//	CIE XYZ D65
//	-> Linear Display P3
//	-> Display P3
func XyzD65ToDisplayP3(x, y, z float64) (r, g, b float64) {
	r = 2.493496911941425*x - 0.9313836179191237*y - 0.40271078445071684*z
	g = -0.8294889695615748*x + 1.7626640603183463*y + 0.023624685841943584*z
	b = 0.03584583024378445*x - 0.07617238926804179*y + 0.956884524007687*z

	return SrgbEncode(r), SrgbEncode(g), SrgbEncode(b)
}

// Conversion path (1 steps):
//
//	CIE XYZ D65
//	-> Linear Display P3
func XyzD65ToLinearDisplayP3(x, y, z float64) (r, g, b float64) {
	r = 2.493496911941425*x - 0.9313836179191237*y - 0.40271078445071684*z
	g = -0.8294889695615748*x + 1.7626640603183463*y + 0.023624685841943584*z
	b = 0.03584583024378445*x - 0.07617238926804179*y + 0.956884524007687*z
	return
}

// Conversion path (2 steps):
//
//	CIE XYZ D65
//	-> Linear Adobe RGB (1998)
//	-> Adobe RGB (1998)
func XyzD65ToA98(x, y, z float64) (r, g, b float64) {
	r = 2.041587903810747*x - 0.5650069742788597*y - 0.34473135077832967*z
	g = -0.9692436362808796*x + 1.8759675015077206*y + 0.04155505740717561*z
	b = 0.013444280632031149*x - 0.11836239223101841*y + 1.0151749943912058*z

	return A98Encode(r), A98Encode(g), A98Encode(b)
}

// Conversion path (1 steps):
//
//	CIE XYZ D65
//	-> Linear Adobe RGB (1998)
func XyzD65ToLinearA98(x, y, z float64) (r, g, b float64) {
	r = 2.041587903810747*x - 0.5650069742788597*y - 0.34473135077832967*z
	g = -0.9692436362808796*x + 1.8759675015077206*y + 0.04155505740717561*z
	b = 0.013444280632031149*x - 0.11836239223101841*y + 1.0151749943912058*z
	return
}

// Conversion path (3 steps):
//
//	CIE XYZ D65
//	-> CIE XYZ D50
//	-> Linear ProPhoto
//	-> ProPhoto
func XyzD65ToProPhoto(x, y, z float64) (r, g, b float64) {
	r = 1.403202937830471*x - 0.2230228699288895*y - 0.10161047851795578*z
	g = -0.5262303211926755*x + 1.4816174225598397*y + 0.017025089072738666*z
	b = -0.011202265286221492*x + 0.018246403479621*y + 0.9112472274915048*z

	return ProPhotoEncode(r), ProPhotoEncode(g), ProPhotoEncode(b)
}

// Conversion path (2 steps):
//
//	CIE XYZ D65
//	-> CIE XYZ D50
//	-> Linear ProPhoto
func XyzD65ToLinearProPhoto(x, y, z float64) (r, g, b float64) {
	r = 1.403202937830471*x - 0.2230228699288895*y - 0.10161047851795578*z
	g = -0.5262303211926755*x + 1.4816174225598397*y + 0.017025089072738666*z
	b = -0.011202265286221492*x + 0.018246403479621*y + 0.9112472274915048*z
	return
}

// Conversion path (2 steps):
//
//	CIE XYZ D65
//	-> Linear Rec. 2020
//	-> Rec. 2020
func XyzD65ToRec2020(x, y, z float64) (r, g, b float64) {
	r = 1.7166511879712683*x - 0.35567078377639255*y - 0.2533662813736599*z
	g = -0.6666843518324892*x + 1.6164812366349393*y + 0.015768545813911142*z
	b = 0.01763985744531079*x - 0.04277061325780853*y + 0.9421031212354739*z

	return Rec2020Encode(r), Rec2020Encode(g), Rec2020Encode(b)
}

// Conversion path (2 steps):
//
//	CIE XYZ D65
//	-> Linear Rec. 2020
//	-> Rec. 2020 Scene Referred
func XyzD65ToRec2020OETF(x, y, z float64) (r, g, b float64) {
	r = 1.7166511879712683*x - 0.35567078377639255*y - 0.2533662813736599*z
	g = -0.6666843518324892*x + 1.6164812366349393*y + 0.015768545813911142*z
	b = 0.01763985744531079*x - 0.04277061325780853*y + 0.9421031212354739*z

	return Rec2020OETFEncode(r), Rec2020OETFEncode(g), Rec2020OETFEncode(b)
}

// Conversion path (1 steps):
//
//	CIE XYZ D65
//	-> Linear Rec. 2020
func XyzD65ToLinearRec2020(x, y, z float64) (r, g, b float64) {
	r = 1.7166511879712683*x - 0.35567078377639255*y - 0.2533662813736599*z
	g = -0.6666843518324892*x + 1.6164812366349393*y + 0.015768545813911142*z
	b = 0.01763985744531079*x - 0.04277061325780853*y + 0.9421031212354739*z
	return
}

// Calls [XyzD65ToLinearRec2020]
//
// Conversion path (2 steps):
//
//	CIE XYZ D65
//	-> Linear Rec. 2020
//	-> Linear Rec. 2100
func XyzD65ToLinearRec2100(x, y, z float64) (r, g, b float64) {
	return XyzD65ToLinearRec2020(x, y, z)
}

// Conversion path (3 steps):
//
//	CIE XYZ D65
//	-> Linear Rec. 2020
//	-> Linear Rec. 2100
//	-> Rec. 2100 PQ
func XyzD65ToRec2100PQ(x, y, z float64) (r, g, b float64) {
	r = 1.7166511879712683*x - 0.35567078377639255*y - 0.2533662813736599*z
	g = -0.6666843518324892*x + 1.6164812366349393*y + 0.015768545813911142*z
	b = 0.01763985744531079*x - 0.04277061325780853*y + 0.9421031212354739*z

	return Rec2100PQEncode(r), Rec2100PQEncode(g), Rec2100PQEncode(b)
}

// Conversion path (3 steps):
//
//	CIE XYZ D65
//	-> Linear Rec. 2020
//	-> Linear Rec. 2100
//	-> Rec. 2100 HLG
func XyzD65ToRec2100HLG(x, y, z float64) (r, g, b float64) {
	r = 1.7166511879712683*x - 0.35567078377639255*y - 0.2533662813736599*z
	g = -0.6666843518324892*x + 1.6164812366349393*y + 0.015768545813911142*z
	b = 0.01763985744531079*x - 0.04277061325780853*y + 0.9421031212354739*z

	return Rec2100HLGEncode(r), Rec2100HLGEncode(g), Rec2100HLGEncode(b)
}

// Conversion path (1 steps):
//
//	CIE XYZ D65
//	-> CIE XYZ D50
func XyzD65ToXyzD50(x, y, z float64) (float64, float64, float64) {
	f1 := 1.0479297925449966*x + 0.02294687060160958*y - 0.05019226628920522*z
	f2 := 0.029627808770055834*x + 0.9904344267538798*y - 0.0170737990634188*z
	f3 := -0.009243040646204511*x + 0.015055191490298162*y + 0.751874281428137*z
	return f1, f2, f3
}

// Conversion path (2 steps):
//
//	CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE xyY
func XyzD65ToXyYD50(x, y, z float64) (float64, float64, float64) {
	f1 := 1.0479297925449966*x + 0.02294687060160958*y - 0.05019226628920522*z
	f2 := 0.029627808770055834*x + 0.9904344267538798*y - 0.0170737990634188*z
	f3 := -0.009243040646204511*x + 0.015055191490298162*y + 0.751874281428137*z

	return XyzToXyY(f1, f2, f3)
}

// Conversion path (1 steps):
//
//	CIE XYZ D65
//	-> CIE xyY
func XyzD65ToXyYD65(x, y, z float64) (float64, float64, float64) {
	return XyzToXyY(x, y, z)
}

// Conversion path (2 steps):
//
//	CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE Lab D50
func XyzD65ToLabD50(x, y, z float64) (l, a, b float64) {
	f1 := 1.0479297925449966*x + 0.02294687060160958*y - 0.05019226628920522*z
	f2 := 0.029627808770055834*x + 0.9904344267538798*y - 0.0170737990634188*z
	f3 := -0.009243040646204511*x + 0.015055191490298162*y + 0.751874281428137*z

	return XyzD50ToLabD50(f1, f2, f3)
}

// Conversion path (3 steps):
//
//	CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE Lab D50
//	-> CIE LCh D50
func XyzD65ToLchD50(x, y, z float64) (l, c, h float64) {
	f1 := 1.0479297925449966*x + 0.02294687060160958*y - 0.05019226628920522*z
	f2 := 0.029627808770055834*x + 0.9904344267538798*y - 0.0170737990634188*z
	f3 := -0.009243040646204511*x + 0.015055191490298162*y + 0.751874281428137*z

	l, a, b := XyzD50ToLabD50(f1, f2, f3)
	return LxyToLch(l, a, b)
}

// Conversion path (2 steps):
//
//	CIE XYZ D65
//	-> CIE Lab D65
//	-> CIE LCh D65
func XyzD65ToLchD65(x, y, z float64) (l, c, h float64) {
	l, a, b := XyzD65ToLabD65(x, y, z)
	return LxyToLch(l, a, b)
}

// Conversion path (2 steps):
//
//	CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE Luv D50
func XyzD65ToLuvD50(x, y, z float64) (l, u, v float64) {
	f1 := 1.0479297925449966*x + 0.02294687060160958*y - 0.05019226628920522*z
	f2 := 0.029627808770055834*x + 0.9904344267538798*y - 0.0170737990634188*z
	f3 := -0.009243040646204511*x + 0.015055191490298162*y + 0.751874281428137*z

	return XyzD50ToLuvD50(f1, f2, f3)
}

// Conversion path (3 steps):
//
//	CIE XYZ D65
//	-> CIE XYZ D50
//	-> CIE Luv D50
//	-> CIE LChuv D50
func XyzD65ToLchuvD50(x, y, z float64) (l, c, h float64) {
	f1 := 1.0479297925449966*x + 0.02294687060160958*y - 0.05019226628920522*z
	f2 := 0.029627808770055834*x + 0.9904344267538798*y - 0.0170737990634188*z
	f3 := -0.009243040646204511*x + 0.015055191490298162*y + 0.751874281428137*z

	l, u, v := XyzD50ToLuvD50(f1, f2, f3)
	return LxyToLch(l, u, v)
}

// Conversion path (2 steps):
//
//	CIE XYZ D65
//	-> CIE Luv D65
//	-> CIE LChuv D65
func XyzD65ToLchuvD65(x, y, z float64) (l, c, h float64) {
	l, u, v := XyzD65ToLuvD65(x, y, z)
	return LxyToLch(l, u, v)
}

// Conversion path (1 steps):
//
//	CIE XYZ D65
//	-> Oklab
func XyzD65ToOklab(x, y, z float64) (l, a, b float64) {
	f1 := 0.819022437996703*x + 0.3619062600528904*y - 0.1288737815209879*z
	f2 := 0.0329836539323885*x + 0.9292868615863434*y + 0.0361446663506424*z
	f3 := 0.0481771893596242*x + 0.2642395317527308*y + 0.6335478284694309*z

	f1 = math.Cbrt(f1)
	f2 = math.Cbrt(f2)
	f3 = math.Cbrt(f3)

	l = 0.210454268309314*f1 + 0.7936177747023054*f2 - 0.0040720430116193*f3
	a = 1.9779985324311684*f1 - 2.42859224204858*f2 + 0.450593709617411*f3
	b = 0.0259040424655478*f1 + 0.7827717124575296*f2 - 0.8086757549230774*f3

	return
}

// Conversion path (2 steps):
//
//	CIE XYZ D65
//	-> Oklab
//	-> Oklch
func XyzD65ToOklch(x, y, z float64) (l, c, h float64) {
	f1 := 0.819022437996703*x + 0.3619062600528904*y - 0.1288737815209879*z
	f2 := 0.0329836539323885*x + 0.9292868615863434*y + 0.0361446663506424*z
	f3 := 0.0481771893596242*x + 0.2642395317527308*y + 0.6335478284694309*z

	f1 = math.Cbrt(f1)
	f2 = math.Cbrt(f2)
	f3 = math.Cbrt(f3)

	l = 0.210454268309314*f1 + 0.7936177747023054*f2 - 0.0040720430116193*f3
	a := 1.9779985324311684*f1 - 2.42859224204858*f2 + 0.450593709617411*f3
	b := 0.0259040424655478*f1 + 0.7827717124575296*f2 - 0.8086757549230774*f3

	return LxyToLch(l, a, b)
}

// Conversion path (3 steps):
//
//	CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HSL
func XyzD65ToHsl(x, y, z float64) (h, s, l float64) {
	r := 3.2409699419045226*x - 1.5373831775700944*y - 0.49861076029300344*z
	g := -0.9692436362808796*x + 1.8759675015077204*y + 0.041555057407175605*z
	b := 0.05563007969699363*x - 0.2039769588889765*y + 1.0569715142428784*z

	r, g, b = SrgbEncode(r), SrgbEncode(g), SrgbEncode(b)
	return SrgbToHsl(r, g, b)
}

// Conversion path (3 steps):
//
//	CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HSV
func XyzD65ToHsv(x, y, z float64) (h, s, v float64) {
	r := 3.2409699419045226*x - 1.5373831775700944*y - 0.49861076029300344*z
	g := -0.9692436362808796*x + 1.8759675015077204*y + 0.041555057407175605*z
	b := 0.05563007969699363*x - 0.2039769588889765*y + 1.0569715142428784*z

	r, g, b = SrgbEncode(r), SrgbEncode(g), SrgbEncode(b)
	return SrgbToHsv(r, g, b)
}

// Conversion path (3 steps):
//
//	CIE XYZ D65
//	-> Linear sRGB
//	-> sRGB
//	-> HWB
func XyzD65ToHwb(x, y, z float64) (h, w, b float64) {
	r := 3.2409699419045226*x - 1.5373831775700944*y - 0.49861076029300344*z
	g := -0.9692436362808796*x + 1.8759675015077204*y + 0.041555057407175605*z
	b = 0.05563007969699363*x - 0.2039769588889765*y + 1.0569715142428784*z

	r, g, b = SrgbEncode(r), SrgbEncode(g), SrgbEncode(b)
	return SrgbToHwb(r, g, b)
}
