// Code generated by "go generate ./gen" in github.com/thmalt/colors. DO NOT EDIT.

package mixer

import (
	"github.com/thmalt/colors/interp"
)

func (m UnsafeMixer) Mix3(a1, a2, a3, aa float64, b1, b2, b3, ba float64, t float64) (c1, c2, c3, ca float64) {
	switch m.hueIndex {
	case 0:
		switch m.hue {
		case interp.HueLonger:
			c1 = interp.LerpHueLonger(a1, b1, t)
		case interp.HueIncreasing:
			c1 = interp.LerpHueIncreasing(a1, b1, t)
		case interp.HueDecreasing:
			c1 = interp.LerpHueDecreasing(a1, b1, t)
		default:
			c1 = interp.LerpHueShorter(a1, b1, t)
		}

		if m.premultiplied {
			w1, w2 := aa*(1-t), ba*t
			ca = w1 + w2
			c2 = a2*w1 + b2*w2
			c3 = a3*w1 + b3*w2

			if ca != 0 {
				inv := 1 / ca
				c2 *= inv
				c3 *= inv
			}
		} else {
			ca = aa + (ba-aa)*t
			c2 = a2 + (b2-a2)*t
			c3 = a3 + (b3-a3)*t
		}
		return
	case 2:
		switch m.hue {
		case interp.HueLonger:
			c3 = interp.LerpHueLonger(a3, b3, t)
		case interp.HueIncreasing:
			c3 = interp.LerpHueIncreasing(a3, b3, t)
		case interp.HueDecreasing:
			c3 = interp.LerpHueDecreasing(a3, b3, t)
		default:
			c3 = interp.LerpHueShorter(a3, b3, t)
		}

		if m.premultiplied {
			w1, w2 := aa*(1-t), ba*t
			ca = w1 + w2
			c1 = a1*w1 + b1*w2
			c2 = a2*w1 + b2*w2

			if ca != 0 {
				inv := 1 / ca
				c1 *= inv
				c2 *= inv
			}
		} else {
			ca = aa + (ba-aa)*t
			c1 = a1 + (b1-a1)*t
			c2 = a2 + (b2-a2)*t
		}
		return
	default:
		if m.premultiplied {
			w1, w2 := aa*(1-t), ba*t
			ca = w1 + w2
			c1 = a1*w1 + b1*w2
			c2 = a2*w1 + b2*w2
			c3 = a3*w1 + b3*w2

			if ca != 0 {
				inv := 1 / ca
				c1 *= inv
				c2 *= inv
				c3 *= inv
			}
		} else {
			ca = aa + (ba-aa)*t
			c1 = a1 + (b1-a1)*t
			c2 = a2 + (b2-a2)*t
			c3 = a3 + (b3-a3)*t
		}
		return
	}
}
